### ISSUE TITLE
[Yeoman Doctor] Uh oh, I found potential errors on your machine

### ISSUE THREAD

**Issue by addagulla** [jhipster/generator-jhipster#955]
Hi,

when i install yo by running npm install -g yo command i am getting following error and i am able to detect the yo. but i unable to create a project when i run yo jhipster command i tryed to solve the issue but i unable to solve can some one helpme

thanks 

[Yeoman Doctor] Uh oh, I found potential errors on your machine
---------------

[Error] npm root value is not in your NODE_PATH
  [info]
    NODE_PATH = :\home\npm\lib\node_modules
    npm root  = module.js:340
    throw err;
          ^
Error: Cannot find module 'C:\Users\bharath.a\AppData\Roaming\npm\node_modules\n
pm\bin\npm-cli.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

  [Fix] Append the npm root value to your NODE_PATH variable
    If you're using cmd.exe, run this command to fix the issue:
      setx NODE_PATH "%NODE_PATH%;module.js:340
    throw err;
          ^
Error: Cannot find module 'C:\Users\bharath.a\AppData\Roaming\npm\node_modules\n
pm\bin\npm-cli.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3"
    Then restart your command line. Otherwise, you can setup NODE_PATH manually:

      https://github.com/sindresorhus/guides/blob/master/set-environment-variabl
es.md#windows

yo@1.3.3 C:\Users\bharath.a\AppData\Roaming\npm\node_modules\yo
├── is-root@1.0.0
├── fullname@1.0.0
├── opn@1.0.1
├── sudo-block@1.1.0
├── underscore.string@2.4.0
├── async@0.9.0
├── shelljs@0.3.0
├── lodash@2.4.1
├── yeoman-doctor@1.1.1 (user-home@1.1.0)
├── string-length@1.0.0 (strip-ansi@2.0.0)
├── yeoman-character@1.0.0 (supports-color@1.2.0)
├── findup@0.1.5 (colors@0.6.2, commander@2.1.0)
├── nopt@3.0.1 (abbrev@1.0.5)
├── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0
.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
├── multiline@1.0.1 (strip-indent@1.0.0)
├── yosay@1.0.1 (ansi-regex@1.1.0, strip-ansi@2.0.0, ansi-styles@2.0.0, minimist
@1.1.0, pad-component@0.0.1, word-wrap@1.0.0, taketalk@0.1.1)
├── configstore@0.3.2 (object-assign@2.0.0, xdg-basedir@1.0.0, user-home@1.1.0,
osenv@0.1.0, graceful-fs@3.0.5, uuid@2.0.1, mkdirp@0.5.0, js-yaml@3.2.5)
├── update-notifier@0.2.2 (is-npm@1.0.0, semver-diff@2.0.0, latest-version@1.0.0
)
├── insight@0.4.3 (object-assign@1.0.0, os-name@1.0.1, tough-cookie@0.12.1, loda
sh.debounce@2.4.1, request@2.51.0, inquirer@0.6.0)
├── yeoman-generator@0.17.7 (dargs@2.1.0, diff@1.2.1, class-extend@0.1.1, rimraf
@2.2.8, text-table@0.2.0, mime@1.2.11, isbinaryfile@2.0.3, mkdirp@0.5.0, iconv-l
ite@0.4.5, github-username@1.0.0, grouped-queue@0.3.0, debug@1.0.4, cross-spawn@
0.2.3, findup-sync@0.1.3, run-async@0.1.0, file-utils@0.2.1, glob@4.3.2, request
@2.51.0, cheerio@0.17.0, gruntfile-editor@0.2.0, download@1.0.7, inquirer@0.7.3)

└── yeoman-environment@1.1.1 (log-symbols@1.0.1, diff@1.2.1, text-table@0.2.0, u
ntildify@1.0.0, grouped-queue@0.3.0, debug@2.1.1, glob@4.3.2, mem-fs@1.0.0, inqu
irer@0.8.0)

**Comment by jdubois** [comment]
This is an issue with installing Yeoman, you should go to the Yeoman forums/discussion boards for this
