### ISSUE TITLE
Enforced cache provider in gateway applications

### ISSUE THREAD

**Issue by Hawkurane** [jhipster/generator-jhipster#9557]
##### **Overview of the feature request**

Currently, when generating a gateway application, the cache is overwritten by hazelcast when a service discovery is defined for rate-limiting purposes. By default, the rate-limiting is set as false.

##### **Motivation for or Use Case**

Generate an application that has a cacheProvider specified. cacheProvider given, the generated application should either:
  - Use the specified cache and warn the user when the cache does not support rate-limiting.
  - ~~Keep it as is but at least allow memcached to not be overwritten~~.

##### **Related issues or PR**

[jhipster-core related issue](https://github.com/jhipster/jhipster-core/issues/317)

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by Hawkurane** [comment]
It seems from the pom.xml that we are using [simple-spring-memcached](https://github.com/ragnor/simple-spring-memcached) for memcached. After looking at it, I haven't seen any mention of the JSR107 or using jcache's API which makes sure that scaling is supported. It may be supported but just in case it's better to specify that it doesn't.

**Comment by pascalgrimaud** [comment]
Closing this, as https://github.com/jhipster/generator-jhipster/pull/9558 has been merged
