### ISSUE TITLE
grunt wiredep command not working

### ISSUE THREAD

**Issue by andidev** [jhipster/generator-jhipster#956]
The `grunt wiredep` task is not working. It should automatically include new installed bower js and css files into index.html.

It seems that grunt-wiredep was added in #501 but the configuration in Gruntfile.js and index.html was not. Is this with purpose for some reason that I don't know?

**Comment by jdubois** [comment]
To be honest, I have no idea what this task does :-)
So you probably know better than me :-)

**Comment by andidev** [comment]
Thats a shame =) It's a really nice task that adds javascripts of installed bower packages to the `index.html` file in `<script>`-tags.
 
I'l provide a PR asap.

**Comment by jdubois** [comment]
Oh yes! I didn't code this part, but indeed it is useful!
