### ISSUE TITLE
Questions about a previously proposed feature" Proposed new keyword: "readonly" #8800"

### ISSUE THREAD

**Issue by hdaniel93** [jhipster/generator-jhipster#9562]
Hi guys.

In reference to this previous closed post https://github.com/jhipster/generator-jhipster/issues/8800

Myself and a few others on our team are thinking about working on this as its a use case thats common in our company.

Having never worked on an open source project before, can anyone point me to in the codebase some examples of a  keyword in JDL and how it effects what is generated? functionality we can use as a base? At its core its simply adding @ Immutable to the JPA class and not generating certain stuff which seems simple enough

**Comment by jdubois** [comment]
Awesome @hdaniel93 ! And happy to help you!
First have a look at https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md

For what you are doing:

- First generate a simple project, commit it, and do your changes on it. Then by doing a "diff" you will see what you need to do, and it looks like it shouldn't be too complex.
- then, a specific issue for you is that the domain language is defined in https://github.com/jhipster/jhipster-core - so you'll need to update the domain language first, and then use it in https://github.com/jhipster/generator-jhipster
- You'll probably only work on the entities, and mostly on the server-side, so it will be in that directory: https://github.com/jhipster/generator-jhipster/tree/master/generators/entity-server

I don't have a good example for you at the moment - I'll get back to you if I remember something good, or maybe other people will help?

**Comment by hdaniel93** [comment]
Should I be opening this as an issue in jhipster-core too then?

**Comment by jdubois** [comment]
No this one is enough, it's under the same organization anyway

**Comment by pascalgrimaud** [comment]
@hdaniel93 : don't hesitate to share code on GitHub, if you need help or advice !

**Comment by hdaniel93** [comment]
@pascalgrimaud @ I have made a few changes https://github.com/hdaniel93/jhipster-core/tree/9562-ReadOnly 

I see in the "contributing" section of JHipster there is information about getting NPM to use your version of the generator, how do I do similar for the core? I want to try a jhipster import-jdl ./my-jdl-file.jdl --json-only. Im assuming I can somehow set the  "jhipster-core" in the package.json of the generator to be my branch of core

**Comment by pascalgrimaud** [comment]
In jhipster-core, which is your fork and you modified it:
- npm link

In generator-jhipster, which id your fork with new modifications:
- npm link jhipster-core
- npm link

Now, in an empty folder, where you want to create a project:
- npm link generator-jhipster

If it doesn't work, try:
- npm link jhipster-core
- npm link generator-jhipster

Tell me if it works fine plz

**Comment by pascalgrimaud** [comment]
@hdaniel93 : did you advance on this feature ?

**Comment by pascalgrimaud** [comment]
The initial feature request was asked in november 2018, this 2nd one since april.
We agree it would be cool to have it, but as it didn't advance and as there is no news, I'm closing this.

You can do directly PR as soon as it's ready.
