### ISSUE TITLE
Error in Pom with jhipster dependencies snapshot

### ISSUE THREAD

**Issue by casseb** [jhipster/generator-jhipster#9571]
Some days ago i was used the 3.0.0-SNAPSHOT version and works fine and it's stay in my locally .m2 folder. When i tried to use the versin 3.0.1-SNAPSHOT, pom file don't locate the dependence and don't work, because this i stay using the 3.0.0 version.

Now I tried remove my m2 for test this two versions but none can download using maven, now it's work only with i copy my old 3.0.0 .m2 version in my pc. with i try to download again, i have this error in mvnw:

`[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not find artifact io.github.jhipster:jhipster-dependencies:pom:3.0.1-SNAPSHOT @ line 89, column 25
[ERROR] 'dependencies.dependency.version' for io.github.jhipster:jhipster-framework:jar is missing. @ line 101, column 21
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-cache:jar is missing. @ line 106, column 21
[ERROR] 'dependencies.dependency.version' for com.fasterxml.jackson.datatype:jackson-datatype-hibernate5:jar is missing. @ line 110, column 21
[ERROR] 'dependencies.dependency.version' for com.fasterxml.jackson.datatype:jackson-datatype-hppc:jar is missing. @ line 114, column 21
[ERROR] 'dependencies.dependency.version' for com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar is missing. @ line 118, column 21
[ERROR] 'dependencies.dependency.version' for com.fasterxml.jackson.module:jackson-module-afterburner:jar is missing. @ line 122, column 21
[ERROR] 'dependencies.dependency.version' for com.h2database:h2:jar is missing. @ line 815, column 29
[ERROR] 'dependencies.dependency.version' for com.jayway.jsonpath:json-path:jar is missing. @ line 131, column 21
[ERROR] 'dependencies.dependency.version' for io.springfox:springfox-swagger2:jar is missing. @ line 137, column 21
[ERROR] 'dependencies.dependency.version' for io.springfox:springfox-bean-validators:jar is missing. @ line 141, column 21
[ERROR] 'dependencies.dependency.version' for com.zaxxer:HikariCP:jar is missing. @ line 145, column 21
[ERROR] 'dependencies.dependency.version' for commons-io:commons-io:jar is missing. @ line 149, column 21
[ERROR] 'dependencies.dependency.version' for org.apache.commons:commons-lang3:jar is missing. @ line 153, column 21
[ERROR] 'dependencies.dependency.version' for javax.cache:cache-api:jar is missing. @ line 157, column 21
[ERROR] 'dependencies.dependency.version' for mysql:mysql-connector-java:jar is missing. @ line 161, column 21
[ERROR] 'dependencies.dependency.version' for org.assertj:assertj-core:jar is missing. @ line 165, column 21
[ERROR] 'dependencies.dependency.version' for org.ehcache:ehcache:jar is missing. @ line 170, column 21
[ERROR] 'dependencies.dependency.version' for org.hibernate:hibernate-jpamodelgen:jar is missing. @ line 174, column 21
[ERROR] 'dependencies.dependency.version' for org.hibernate:hibernate-core:jar is missing. @ line 179, column 21
[ERROR] 'dependencies.dependency.version' for org.hibernate:hibernate-envers:jar is missing. @ line 183, column 21
[ERROR] 'dependencies.dependency.version' for org.hibernate.validator:hibernate-validator:jar is missing. @ line 187, column 21
[ERROR] 'dependencies.dependency.version' for org.liquibase:liquibase-core:jar is missing. @ line 191, column 21
[ERROR] 'dependencies.dependency.version' for net.logstash.logback:logstash-logback-encoder:jar is missing. @ line 195, column 21
[ERROR] 'dependencies.dependency.version' for org.mapstruct:mapstruct:jar is missing. @ line 199, column 21
[ERROR] 'dependencies.dependency.version' for org.mapstruct:mapstruct-processor:jar is missing. @ line 203, column 21
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-configuration-processor:jar is missing. @ line 208, column 21
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-loader-tools:jar is missing. @ line 213, column 21
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-actuator:jar is missing. @ line 217, column 21
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-aop:jar is missing. @ line 221, column 21
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-data-jpa:jar is missing. @ line 225, column 21
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-logging:jar is missing. @ line 229, column 21
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-mail:jar is missing. @ line 233, column 21
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-security:jar is missing. @ line 237, column 21
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-thymeleaf:jar is missing. @ line 241, column 21
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-web:jar is missing. @ line 245, column 21
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-test:jar is missing. @ line 249, column 21
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-test:jar is missing. @ line 254, column 21
[ERROR] 'dependencies.dependency.version' for org.springframework.security:spring-security-test:jar is missing. @ line 259, column 21
[ERROR] 'dependencies.dependency.version' for org.zalando:problem-spring-web:jar is missing. @ line 264, column 21
[ERROR] 'dependencies.dependency.version' for io.jsonwebtoken:jjwt-api:jar is missing. @ line 268, column 21
[ERROR] 'dependencies.dependency.version' for io.jsonwebtoken:jjwt-impl:jar is missing. @ line 272, column 21
[ERROR] 'dependencies.dependency.version' for io.jsonwebtoken:jjwt-jackson:jar is missing. @ line 277, column 21
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-cloud-connectors:jar is missing. @ line 283, column 21
[ERROR] 'dependencies.dependency.version' for org.springframework.security:spring-security-data:jar is missing. @ line 288, column 21
[ERROR] 'dependencies.dependency.version' for io.micrometer:micrometer-registry-prometheus:jar is missing. @ line 292, column 21
[ERROR] 'dependencies.dependency.version' for io.dropwizard.metrics:metrics-core:jar is missing. @ line 296, column 21
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-undertow:jar is missing. @ line 806, column 29
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-devtools:jar is missing. @ line 810, column 29`

This application was created using maven and all others defaults options, i tried using other pc and other network but the same error appear.

Someone have the same problem?

**Comment by casseb** [comment]
I tried in gradle and the same problem happened

**Comment by jdubois** [comment]
That's normal it's a snapshot, you need to point to the snapshot repo -> I don't know who did this, but there's an error in our side here
@casseb you need to checkout jhipster/jhipster and do a "mvnw clean install" to build the snapshot yourself

**Comment by casseb** [comment]
@jdubois Thanks for the support

I have doubts about this problem... i'm doing customizations in Jhipster locally, because this i install with npm install and npm link.

When i used a normal JHipster version it was possible to download the snapshot for link: io.github.jhipster:jhipster-dependencies:pom:3.0.1-SNAPSHOT but now it's not possible,

How i create my own snapshot?  mvnw clean install in jhipster folder isn't possible because it's not have mvnw file, in generated application i try to execute this command but the same error appears.

It's necessary to make some change in generated application pom.xml?

**Comment by pascalgrimaud** [comment]
@casseb : you need to clone this repo https://github.com/jhipster/jhipster

Then, you need to launch `./mvnw clean install -Dgpg.skip=true`

So, you'll be able to use the snapshot version

**Comment by pascalgrimaud** [comment]
And our documentation didn't mention that: https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md

**Comment by jdubois** [comment]
@pascalgrimaud when we start to use a snapshot release, we're supposed to add the snapshot repo in the application configuration.

**Comment by pascalgrimaud** [comment]
You're right @jdubois !
It has been forgotten here https://github.com/jhipster/generator-jhipster/commit/40f88a143e659353da0a9adf06a7fe4032dadb11

We need to take snapshot repo from here: https://github.com/jhipster/generator-jhipster/commit/d3da18a760de17ec9c2e9923b36c9f29695e460b

**Comment by casseb** [comment]
Generating a new snapshot works fine, thanks for the help, this is a amazing tool and it's fun use it!
