### ISSUE TITLE
Some improvements in generating test data with faker.js

### ISSUE THREAD

**Issue by pmverma** [jhipster/generator-jhipster#9579]
##### **Overview of the feature request**

Some improvement in generating fake test data.

##### **Motivation for or Use Case**

With the introduction `fakerjs fake data, mapsid, unique key, etc.`, generating the relationship fake data in `entity.csv` without taking care of those, is causing some exceptions in liquibase during app startup.

Problem 1:
If the relationship value is marked as `unique`, some random number between 1 and 10 will be used. And this results in unique key constraint violation error.

Problem 2:
With OneToOne or MapsId, if the relationship is required, then same as above problem 1 because OneToOne association is based on a foreign key that is constrained to be unique.

Suggested Fix for 1 and 2:
Do not use some random number. But use current array index so that relationship ids do not conflicts. 
https://github.com/jhipster/generator-jhipster/blob/master/generators/entity-server/templates/src/main/resources/config/liquibase/data/table.csv.ejs#L136-L144

Problem 3:
If the other entity in relationship is required and is User, only user id 1 and 2 has been used which is not enough if OneToOne/MapsId is used or unique key constrained is applied.

Suggested Fix for 3:
Generate more 6 users, total 10 in `user.csv` so that association value can be applied without worrying for value conflicting.

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Thanks for your analyze @pmverma

As we didn't detect this in our CI, maybe it means we don't have test with 'unique' in our entities ? I need to have a look. And we could improve this part too, when fixing this ticket.

**Comment by pascalgrimaud** [comment]
So we don't have a relationship with `unique` in our CI entities, that explains why we didn't detect it.
@pmverma : do you have a solution for fixing this bug ? Would you like to PR plz ?

**Comment by pmverma** [comment]
@pascalgrimaud Thanks for checking. I will do the PR once I am back from my vacation next week.

**Comment by jdubois** [comment]
Yes sorry about this, it's my fault.
Ok on everything but please don't create more users as it will be annoying to have all those in production (there's a difference for users, that data is also going to production).

**Comment by ruddell** [comment]
The reasoning for only two users is that OAuth [only generates two](https://github.com/jhipster/generator-jhipster/blob/20ffe910f23eef53aeb5dc3a17b38b384909f566/generators/server/templates/src/main/resources/config/liquibase/users.csv.ejs#L4) default users ([commit](https://github.com/jhipster/generator-jhipster/commit/8e08fe54ca8f354d83fa10102c71369ad388636d), related to https://github.com/jhipster/generator-jhipster/issues/9347).

**Comment by pascalgrimaud** [comment]
I didn't have a look in details to faker.js but maybe we can do the same as with Protractor:
https://github.com/jhipster/generator-jhipster/blob/master/generators/entity-client/templates/react/src/test/javascript/e2e/entities/entity.spec.ts.ejs#L38-L44

Not sure we can generate proper datas when there is 'required'

**Comment by pmverma** [comment]
Thanks @pascalgrimaud Problem 1 and 2 can be fixed with suggested fix by using array index number than some random number.
Main challenge here is handling user mapid relationship (including chained/nested association such as `User->MyUser->MySomeAnotherEntityWhichIsMeantToBeOneToOneWithUserToo`) which are `unique`. Because we have max 4 users by default, then the record should be `4 -> 4 -> 4->`.

I have not tried to fix this yet but I believe this can be done.

**Comment by pascalgrimaud** [comment]
I didn't follow closely this ticket
@pmverma : do you think all issues with Faker.js were fixed ?

**Comment by pmverma** [comment]
I also have not followed all the related PR closely but I think `unique` key constraints still have to be fixed.
I am afraid I will have very little time to work on PRs until early next month.

**Comment by geyuqiu** [comment]
I am also having some breaking IntegrationTests generated from JHipster that fails after adding unique constraint:
**org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException**

 Can it be grouped into this issue?
Cheers

**Comment by pmverma** [comment]
@geyuqiu,
Unique key constraints issue was already fixed in last version.
Can you test with latest version and see if the problem has been solved or not?
Otherwise, please create a new issue  with all the details.
Of course, it can be grouped here if it was not identified previously.

**Comment by pmverma** [comment]
This issue has specified 3 problems.
Among them, 1 and 2 have been fixed.
Problem 3 can't be fixed as we have only 4 users (in the JWT and session case) and only 2 users in the case of OAuth. In that case, the developer has to manage the fake data by himself/herself.

I would like to close this issue as per the above comment.

**Comment by devsparkles** [comment]
ok roger that
