### ISSUE TITLE
MIssing methods in LoginService.ts

### ISSUE THREAD

**Issue by wayne-optin** [jhipster/generator-jhipster#9588]
##### **Overview of the issue**

Generated gateway webapp LoginService is missing methods "isAuthenticated()" and "logoutDirectly()" if you generate using "UAA" option and no internationalization

##### **Motivation for or Use Case**

Want a Gateway, using UAA and no i18n

##### **Reproduce the error**

Generate Gateway, select UAA and no translation. Run mvnw - the webapp compilation will fail in webapp/app/blocks/interceptor/auth-expired.interceptor.ts due to calling the un-generated methods.

##### **Suggest a Fix**

Maybe the the test on [line 81 of login.service.ts.ejs](https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/src/main/webapp/app/core/login/login.service.ts.ejs#L81)

Workaround: select internationalization, choose only the primary language.

##### **JHipster Version(s)**

6.0.0-beta.0
##### **JHipster configuration**

````
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
gateway@0.0.0 C:\Users\wayne\dev\tmp\gateway
`-- generator-jhipster@6.0.0-beta.0

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.optin.spike.jhipster.gateway",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.0.0-beta.0",
    "applicationType": "gateway",
    "baseName": "gateway",
    "packageName": "com.optin.spike.jhipster.gateway",
    "packageFolder": "com/optin/spike/jhipster/gateway",
    "serverPort": "8080",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false
  }
}

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>


##### **Environment and Tools**

java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

git version 2.21.0.windows.1

node: v11.12.0

npm: 6.9.0

yeoman: 2.0.5

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

INFO! Congratulations, JHipster execution is complete!           
````

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
no entities generated

##### **Browsers and Operating System**

Windows 10

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Thanks for reporting the issue, @wayne-optin 
Don't hesitate to directly PR the fix, as you pointed the correct line :)
Anyway, I'm fixing this, right now
