### ISSUE TITLE
Websocket connection error

### ISSUE THREAD

**Issue by eapriansyah** [jhipster/generator-jhipster#9591]
##### **Overview of the issue**
Generated simple monolith application and using websocket to send data from the backend to the front end doesn't work.

##### **Motivation for or Use Case**
Use websocket to send data from the back end.

##### **Reproduce the error**
- Generate Monolith, select Websocket. 
- Run apps, and open http://localhost:9000/admin/jhi-tracker
- Check at devtools console

##### **JHipster Version(s)**
6.0.0-beta.0

##### **JHipster configuration**
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "6.0.0-beta.0",
    "applicationType": "monolith",
    "baseName": "testws",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "NGZkMDFlMjNkMTg3MzViZTc4MDIyMzBlNTc1MGMwNjhlZjRjM2Q3YTFhYTNiYWZiMmI3N2U0ZDRkYTFkODU2MWE3Nzk2Y2M2MzE5YjRhMTY3ZWI1YTM3MzZjYjYzODI0YTZlZDllODNmOTE0NzA5NmIwNTZlNmRkNjNhYmFiMjA=",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false
  }
}
##### **Browsers and Operating System**
D:\Users\dev>java -version
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)

D:\Users\dev>npm --version
6.9.0

D:\Users\dev>node --version
v10.15.3

Google Chrome
Version 73.0.3683.103 (Official Build) (64-bit)

Windows 10 64Bit

-   [ yes] Checking this box is mandatory (this is just to show you read everything)

##### **Change in Code**
file changed: tracker.service.ts

original -> result
![prior](https://user-images.githubusercontent.com/1936249/56461422-ff60ce00-63dc-11e9-83f8-fe343ed41a49.jpg)

line 41
url = '//' + loc.host + loc.pathname + 'websocket/tracker';
to
url = '//' + loc.host + '/websocket/tracker';

![after](https://user-images.githubusercontent.com/1936249/56461425-0687dc00-63dd-11e9-8e7f-4781aec31c0b.jpg)

line 46
const socket = new SockJS(url);
to
const socket = new WebSocket('ws:' + url);
![with-websocket](https://user-images.githubusercontent.com/1936249/56461428-0be52680-63dd-11e9-9564-1401523afd96.png)

**Comment by ruddell** [comment]
This is related to the removal of the `#` from the URL (https://github.com/jhipster/generator-jhipster/pull/9098).  Looks like I forgot to test websockets, sorry about that.  

I could get it working by updating [ClientForwardController.java](https://github.com/jhipster/generator-jhipster/blob/53ff2b634c143b6cd28ba4ea27d8bb49755d4e1d/generators/server/templates/src/main/java/package/web/rest/ClientForwardController.java.ejs#L31) to exclude paths starting with `websocket`, along with the removal of `loc.pathname` that you mentioned.

```
-    @GetMapping(value = "/**/{path:[^\\.]*}")
+    @GetMapping(value = "/**/{path:^(?!websocket)[^\\.]*}")
```

The `loc.pathname` was for context-paths, instead we should get the [base href](https://github.com/jhipster/generator-jhipster/blob/53ff2b634c143b6cd28ba4ea27d8bb49755d4e1d/generators/client/templates/angular/src/main/webapp/index.html.ejs#L22) (now required to be set when using a context-path) and use that instead.

**Comment by gantispam** [comment]
Same issue on Jhipster 6.5.0 :
![image](https://user-images.githubusercontent.com/15685552/68957965-6efc3780-07cb-11ea-9251-211b7dc34a3b.png)
