### ISSUE TITLE
Remove the _search prefix on elastic endpoints

### ISSUE THREAD

**Issue by Tcharl** [jhipster/generator-jhipster#9594]
##### **Overview of the feature request**

Elastic endpoint are generated with endpoint beginning with _search, I think we can remove this prefix...

##### **Motivation for or Use Case**

REST is resource oriented, and _search doesn't express any resource.
Doing this, we're basically doing SOAP like endpoints which may encourage our end user to follow that (wrong) Path.
The idea would be to merge the getAll endpoint to handle either the All or the search queries. 

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@Tcharl : I think it was done like this, to match with the search in Elasticsearch API.
See https://www.elastic.co/guide/en/elasticsearch/reference/current/search.html

Let's discuss.

**Comment by pascalgrimaud** [comment]
As no one commented this, I supposed it's not a must have
I propose to stick with Elasticsearch API for now, we can wait opinion from other people

Let's close this ticket, as we have so much bugs to fix
