### ISSUE TITLE
Installing generator-jhipster globally with yarn fails due to event-stream vulnerability

### ISSUE THREAD

**Issue by Larkenx** [jhipster/generator-jhipster#9611]
##### **Overview of the issue**

Installing the yeoman generator for jhipster fails globally with yarn due to a dependency on event-stream-3.3.6. 

```
[steven@work yeoman-workspace]$ yarn global add generator-jhipster
yarn global v1.13.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/event-stream/-/event-stream-3.3.6.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/Users/n0311891/.config/yarn/global/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```
##### **Suggest a Fix**

Make sure to audit or list all dependencies that use either event-stream or flat-map-stream, and update the versions of event-stream. Check out https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident for more details.

##### **Browsers and Operating System**

macOS

```
[steven@work ~]$ yarn -v
1.13.0
```
-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by Larkenx** [comment]
opened issue in yarn instead https://github.com/yarnpkg/yarn/issues/7224

**Comment by ruddell** [comment]
For reference, I could not reproduce locally on my Mac, or in an Ubuntu docker container with a fresh node installation.
```
root@8cf8b33e6009:~# nvm install --lts
Installing latest LTS version.
Downloading and installing node v10.15.3...
root@8cf8b33e6009:~# npm install -g yarn
root@8cf8b33e6009:~# yarn global add generator-jhipster
yarn global v1.15.2
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "generator-jhipster@5.8.2" with binaries:
      - jhipster
Done in 27.62s.
root@8cf8b33e6009:~# 
```

Running `yarn why flat-map-stream` or `yarn why event-stream` shows that they are not depended on by JHipster
