### ISSUE TITLE
Jhipster gae does not work on version 6

### ISSUE THREAD

**Issue by Tonterias** [jhipster/generator-jhipster#9617]
##### **Overview of the issue**

jhipster gae on version 6 gives an error:

\Jhipster\jhv6betak8smvn>jhipster gae
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:gae
INFO! Options: from-cli: true
Welcome to Google App Engine Generator (Beta)
WARNING! This sub-generator is still in development, please report bugs on Github

Installing App Engine Java SDK
... Running: gcloud components install app-engine-java --quiet
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn gcloud ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

##### **Motivation for or Use Case**

Can you deploy a demo app to Google App Engine?

##### **Reproduce the error**

I created a one entity demo app (which works locally) and tried to execute:

jhv6betak8smvn>jhipster gae
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:gae
INFO! Options: from-cli: true
Welcome to Google App Engine Generator (Beta)
WARNING! This sub-generator is still in development, please report bugs on Github

Installing App Engine Java SDK
... Running: gcloud components install app-engine-java --quiet
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn gcloud ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

##### **JHipster Version(s)**

v6.beta

##### **JHipster configuration**

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.jhv6betak8s.web",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.0.0-beta.0",
    "applicationType": "monolith",
    "baseName": "jhv6betak8smvn",
    "packageName": "com.jhv6betak8s.web",
    "packageFolder": "com/jhv6betak8s/web",
    "serverPort": "8080",
    "authenticationType": "session",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "rememberMeKey": "4f4901199be7d63dbc56ab12562158009e83f50ea86f4e465c714d87747af35dfd841f44cfc22c2a6639d31acd517d7d39ac",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en", "es"]
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

entity Profile {
    creationDate Instant required
    gender Gender required
    optionalsn String maxlength(50)
    sibblings Integer min(-1) max(20)
    pet Boolean
}

// ENUMS:
enum Gender {
    MALE, FEMALE, OTHER
}

// Set pagination options
//paginate all with infinite-scroll
paginate all with pagination

// DTO for all
dto * with mapstruct

// Set service options to all except few
// service all with serviceImpl
service all with serviceClass

//Filtering
filter *

##### **Browsers and Operating System**

does it matter? W10 Chrome.

Thanks

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by PierreBesson** [comment]
Hi @Tonterias,

It looks like you don't have the gcloud command installed. See https://www.jhipster.tech/gcp/
Also please note that
on v6 we have migrated to jar packaging. However GAE need a war so you will need to package your app with the `war` profile. `./mvnw appengine:deploy -DskipTests -Pprod,prod-gae,war`

**Comment by pascalgrimaud** [comment]
Same issue than https://github.com/jhipster/generator-jhipster/issues/9605 ?
You are both using Windows

**Comment by Tonterias** [comment]
Yes, you can close it. Sorry

**Comment by Tonterias** [comment]
Hi @PierreBesson 

I can create a project from the google cloud sdk command.

D:\BasuraTemporal\Jhipster\jhv6betak8smvn>mvnw appengine:deploy -DskipTests -Pprod,prod-gae,war
Found "D:\BasuraTemporal\Jhipster\jhv6betak8smvn\.mvn\wrapper\maven-wrapper.jar"
[INFO] Scanning for projects...
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml (14 kB at 15 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml (20 kB at 23 kB/s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.719 s
[INFO] Finished at: 2019-04-25T18:44:54+02:00
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "prod-gae" could not be activated because it does not exist.
[ERROR] No plugin found for prefix 'appengine' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (C:\Users\usuario\.m2\repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException

I really love kubernetes!

Do you want me to try to explain the k8s persistent problem with another wording so you may see what is going on. On the end, it is quite simple. Can you make a database persist on your k8s projects?

Thanks Pierre
