### ISSUE TITLE
Full Microservice Stack generation fails with EBADF: bad file descriptor, close

### ISSUE THREAD

**Issue by crowne** [jhipster/generator-jhipster#9619]
##### **Overview of the issue**
Cannot generate the app as per the [tutorial](https://medium.com/jhipster/create-full-microservice-stack-using-jhipster-domain-language-under-30-minutes-ecc6e7fc3f77) by @deepu105 

jhipster seems to spawn 3 parallel processes for concurrent generation of the apps
declared in the jdl (store, invoice, notification)

store and invoice are generated successfully
notification seems to crash with an error - ERROR! EBADF: bad file descriptor, close
Full stacktrace pasted below:

PS E:\projects\jhipster\ecommerce> jhipster import-jdl app.jdl
INFO! Using JHipster version installed globally
INFO! Executing import-jdl app.jdl
INFO! Options: from-cli: true
INFO! The JDL is being parsed.
warn: An Entity name 'User' was used: 'User' is an entity created by default by JHipster. All relationships toward it will be kept but any attributes and relationships from it will be disregarded.
warn: An Entity name 'User' was used: 'User' is an entity created by default by JHipster. All relationships toward it will be kept but any attributes and relationships from it will be disregarded.
warn: An Entity name 'User' was used: 'User' is an entity created by default by JHipster. All relationships toward it will be kept but any attributes and relationships from it will be disregarded.
INFO! Found entities: Product, ProductCategory, Customer, ProductOrder, OrderItem, Invoice, Shipment, Notification.
INFO! The JDL has been successfully parsed
INFO! Generating 3 applications.
INFO! Generating application store in a new parallel process
INFO! Generating application invoice in a new parallel process
INFO! Generating application notification in a new parallel process
INFO! Executing jhipster:app on E:\projects\jhipster\ecommerce\store
INFO! Options: fromCli: true, withEntities: true, force: true, from-cli: true, with-entities: true
INFO! Executing jhipster:app on E:\projects\jhipster\ecommerce\invoice
INFO! Executing jhipster:app on E:\projects\jhipster\ecommerce\notification
INFO! Options: fromCli: true, withEntities: true, force: true, from-cli: true, with-entities: true
INFO! Options: fromCli: true, withEntities: true, force: true, from-cli: true, with-entities: true

        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝

                            https://www.jhipster.tech

Welcome to JHipster v5.8.2
Application files will be generated in folder: E:\projects\jhipster\ecommerce\store
 _______________________________________________________________________________________________________________

  Documentation for creating an application is at https://www.jhipster.tech/creating-an-app/
  If you find JHipster useful, consider sponsoring the project at https://opencollective.com/generator-jhipster
 _______________________________________________________________________________________________________________

ERROR! EBADF: bad file descriptor, close
{ Error: EBADF: bad file descriptor, close
    at Object.closeSync (fs.js:401:3)
    at Object.closeSync (C:\Users\Neil\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\graceful-fs\graceful-fs.js:52:27)
    at Function.writeFileSync [as sync] (C:\Users\Neil\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\write-file-atomic\index.js:228:16)
    at Conf.set store [as store] (C:\Users\Neil\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\insight\node_modules\conf\index.js:142:19)
    at new Conf (C:\Users\Neil\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\insight\node_modules\conf\index.js:44:14)
    at new Insight (C:\Users\Neil\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\insight\lib\index.js:40:35)
    at Statistics.configInsight (C:\Users\Neil\AppData\Roaming\npm\node_modules\generator-jhipster\generators\statistics.js:59:25)
    at new Statistics (C:\Users\Neil\AppData\Roaming\npm\node_modules\generator-jhipster\generators\statistics.js:49:14)
    at get (C:\Users\Neil\AppData\Roaming\npm\node_modules\generator-jhipster\generators\statistics.js:238:27)
    at Object.<anonymous> (C:\Users\Neil\AppData\Roaming\npm\node_modules\generator-jhipster\generators\statistics.js:244:18) errno: -4083, syscall: 'close', code: 'EBADF' }
INFO! App: child process exited with code 1

        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝

                            https://www.jhipster.tech

Welcome to JHipster v5.8.2
Application files will be generated in folder: E:\projects\jhipster\ecommerce\invoice

##### **Motivation for or Use Case**

It is expected that the tutorial should work.

##### **Reproduce the error**

Follow the tutorial at:
https://medium.com/jhipster/create-full-microservice-stack-using-jhipster-domain-language-under-30-minutes-ecc6e7fc3f77

##### **Related issues**

None found

##### **JHipster configuration**

v5.8.2

##### **Browsers and Operating System**

Windows 10 Pro, 64 bit

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by crowne** [comment]
Interesting observation, I managed to generate the app with the same jdl using JHipster Online
https://start.jhipster.tech/#/design-entities

Although generating the 3 apps in a single repository seems incorrect.

https://github.com/crowne/ecommerce/tree/jhipster-entities-ecommerce-855412220369417

**Comment by crowne** [comment]
This could be related to this problem on NodeJS https://github.com/nodejs/node/issues/25335
I am running node v10.13.0

**Comment by crowne** [comment]
This issue is resolved by upgrading to node v10.15.3

**Comment by pascalgrimaud** [comment]
good to know that node v10.13.0 is broken !
Thanks for your feedback

**Comment by crowne** [comment]
@pascalgrimaud ... Damn, I spoke too soon! I reran it and got another EBADF error.
I won't reopen it though, because I this seems to be a node issue and not a jhipster issue.
It seems to happen every send time I try to regenerate the full stack microservice app or a variant thereof.

**Comment by pascalgrimaud** [comment]
@crowne : as you are with Windows, can you tell me which terminal you use ?
I don't have Windows machine, but I got a VM, I can try to reproduce.

**Comment by crowne** [comment]
@pascalgrimaud I'm using Powershell on Windows 10 (64 bit)

**Comment by crowne** [comment]
@pascalgrimaud It looks like its a problem with Insight.
No problems if I run the generator as follows.
> jhipster import-jdl app.jdl --no-insight

Original stacktrace in more readable format shows the error being thrown from Insight.

![image](https://user-images.githubusercontent.com/3218673/56847934-a9ab8a80-68e2-11e9-81ba-f658e92ef24a.png)

**Comment by Crazie-ash** [comment]
![image](https://user-images.githubusercontent.com/45698249/58178040-11c37580-7cc3-11e9-95b2-cbc8e3660b90.png)
npm  v6.4.1
node v10.15.3


> This issue is resolved by upgrading to node v10.15.3

**Comment by crowne** [comment]
Hi Ash, sorry ... it wasn't resolved I'm still getting the issue.
I will reopen here for this comment to be seen more broadly.
However I don't think this is a JHipster issue it does seem to be a an issue with some of the NodeJs components when running on windows.
The only way that I have managed to work-around this issue is by running JHipster in a docker container, using this [image](https://hub.docker.com/r/jhipster/jhipster/).
Also see this part of the installation [guide](https://www.jhipster.tech/installation/#docker-installation-for-advanced-users-only).
Using the docker image I was able to generate the full-stack app, however I wasn't able to build the apps using the docker image due to some kind of container incompatibility with the symlinks generated under node_modules.
So after generating the app with the docker image, I then deleted node_modules and recompiled the app in a native windows powershell.

**Comment by pascalgrimaud** [comment]
@crowne :
- could you try with generator-jhipster v6.0.1
- then, we have a devbox which workd well, https://github.com/jhipster/jhipster-devbox

On my side, I'll try to reproduce your issue in a Windows VM

**Comment by pascalgrimaud** [comment]
I tested with a Windows VM and everythings work well for me. So it comes from your environment.
- Windows 10 under VM
- generator-jhipster v6.0.1
- node v10.15.3 LTS
- npm 6.4.1

See my screenshot:
![Capture d’écran de 2019-05-25 11-14-06](https://user-images.githubusercontent.com/9156882/58367365-9f2ee180-7ede-11e9-8094-a80c4e1970d3.png)

I suggest to test our DevBox if you can't resolve your environment issue.
As it doesn't come from generator-jhipster, there is no bug on our side, I'm closing this. But don't hesitate to comment if you find what's wrong with your machine.

**Comment by Crazie-ash** [comment]
Thanks for the response... i will try to figure it out once fixed!!
