### ISSUE TITLE
Spring Websocket does not work on CloudFoundry

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#963]
When deploying our app, with Spring Websocket, on the Pivotal Cloudfoundry PAAS, we get a 
```
 Opening Web Socket...
a88d8126.vendor.js:10 WebSocket connection to 'ws://breizhjug.cfapps.io/websocket/activity/927/jcgk78no/websocket' failed: Error during WebSocket handshake: Unexpected response code: 400
http://breizhjug.cfapps.io/websocket/activity/927/e26zo7jp/xhr_streaming Failed to load resource: the server responded with a status of 403 (Forbidden)
a88d8126.vendor.js:10 POST http://breizhjug.cfapps.io/websocket/activity/927/ykzlu5p1/xhr 403 (Forbidden)
a88d8126.vendor.js:10 Whoops! Lost connection to undefined
```
This is probably caused by the router, as it works elsewhere.

Ping @sdeleuze as I know he has made this working correctly.

**Comment by jdubois** [comment]
It's a Pivotal issue: it works on our own CF-based cloud at Ippon Technology, but it doesn't work on the Pivotal CF, probably because they don't have the right front-end router.
Anyway, this is not a JHipster issue, as I have it working on our CF instance.

**Comment by svennela** [comment]
In Cloud Foundry on PWS, all secure web socket traffic is routed on port 4443, can you check the your client is using port 4443? Please let me know.

**Comment by jdubois** [comment]
I'm not using HTTPS, do you mean that Websocket traffic must be encrypted?

**Comment by sdeleuze** [comment]
@jdubois I think that means you should connect to `wss://breizhjug.cfapps.io:4443/websocket/`

**Comment by jdubois** [comment]
Thanks, I'm reopening this and I will check
