### ISSUE TITLE
Ignore the generated files/folders from sonar/jacoco metrics

### ISSUE THREAD

**Issue by vraravam** [jhipster/generator-jhipster#9631]
##### **Overview of the feature request**

When using jHipster, we end up with generated code inside `build/generated` folder. Can this folder be automatically ignored from sonar and/or jacoco metrics? Based on different SO answers, this is possible with setting the following in `gradle\sonar.gradle` file:

```
test {
    jacoco {
        excludes += ['build/generated/**']
    }
}

jacocoTestReport {
    afterEvaluate {
        classDirectories = files(classDirectories.files.collect {
            fileTree(dir: it, exclude: [
                    '**/*_.class'
            ])
        })
    }
}
```
_Note_: For my codebase, I only found that the generated domain classes end with the underscore - and thus was able to filter them out of the coverage percentage calculations as well as the report. If there is a better way, please implement that.

##### **Motivation for or Use Case**

Coverage metrics should only be shown for code that we write. For any generated/boiler-plate code, it is more like "noise" in the reports.

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
Is this a jacoco problem or in sonar? As far as I can see these classes are not part of the sonar analysis so in sonar everything looks fine. Do you mean in the jacoco html report?

**Comment by vraravam** [comment]
@atomfrede :  Yes - they show up in the html report.

**Comment by atomfrede** [comment]
Thats in fact a jacoco problem (I know of). You have to exclude the generated classes from analysis and tell the reporting of jacoco not to take them into account as the reporting does not honor the exclusions from the analysis phase.

**Comment by vraravam** [comment]
Between the 2 (agent and report) - I agree that the report should be more "intelligent".

But, since jHipster is a _code generator_, imo, this can be added to the appropriate yeoman files for generating the gradle files.

**Comment by atomfrede** [comment]
Which jhipster version are you using? according to https://github.com/jacoco/jacoco/releases classes annotated with `@Generated` should be excluded (for both report and agent as far as I understand, but maybe it just for the coverage report generation).

**Comment by vraravam** [comment]
jhipster version: 5.8.2
jacoco version: 0.8.3

The `@Generated` annotation is working (to be ignored - IF it is present) - but, as a user, I do not want to edit the *generated* files with these annotations.

**Comment by atomfrede** [comment]
@jhipster/developers Personally I think we can put this to our documentation/tips & tricks section as it only affects the html report. What do you think?

**Comment by pascalgrimaud** [comment]
It could be there too: https://www.jhipster.tech/code-quality/
So the user can decide what to do

**Comment by pascalgrimaud** [comment]
@vraravam @atomfrede : can one of you PR and update this page plz ? https://www.jhipster.tech/code-quality/

**Comment by atomfrede** [comment]
I will do it. Will have a look at maven too.

**Comment by atomfrede** [comment]
As the documentation is merged we can close this imho.
