### ISSUE TITLE
Index listing of entities can show some more info

### ISSUE THREAD

**Issue by vraravam** [jhipster/generator-jhipster#9632]
##### **Overview of the feature request**

If there are no entities in the datastore, the table can be replaced with a "no XXX found" message.
Also, above the table you can show the total number of entities - this is complimentary to the pagination links because without this, the pagination links seem incomplete.

##### **Motivation for or Use Case**

Better UI for the end-user of the generated app.

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by avdev4j** [comment]
Hi @vraravam 
I think it's could be a good improvement. Would you like to do this PR?

**Comment by vraravam** [comment]
unfortunately, im not a angular/react dev - will have to pass on this.

**Comment by avdev4j** [comment]
Ok I see.
If you want to do a first step in Angular or React environnement don't hesitate we can help you.
Otherwise we can wait for some motivated new contributors. (If we find no one I will take a look ;)).

**Comment by wmarques** [comment]
Hi @vraravam thanks for your feedback.
I can help on this next week probably, for the Angular part
