### ISSUE TITLE
onetomany relationship not shown (the same for manytomany right side)

### ISSUE THREAD

**Issue by cirotarini** [jhipster/generator-jhipster#9639]
##### **Overview of the issue**
1) father/son issue: when you create a “relationship OneToMany”, the many to one side of the relation is NOT shown (in the son I can see the father, in the father I cannot see the sons).
So in the OneToMany relationship  (below) WishList{product} to Product{wishList(title)}, the whishlist ‘father’ element does not show the Product ‘son elements’
2)ManyToMany issue;: in a ManyToMany relationship, from a left hand element I can choose the right hand elements and they are they are  shown, while the opposite does not happen:  from a right hand element I can choose only one left  hand element, that is correctly shown.
--Reference--
This is an old issue well described for angular js (2017) here, with fix: https://dadtechblog.com/2017/05/27/creating-a-master-detail-relationship-with-jhipster/

No stack trace is generated for this issue.

##### **Motivation for or Use Case**
I believe that this is a bug because this behavior is not coherent: the child in a */tomany relation should be always shown: why to define a relation if it is not shown?

##### **Reproduce the error**

to reproduce the error
- build a jhipster app with the info below
- create a category and some  product for that category: then look at that category: the product are shown
- create some new category and then a new product: (error!) you can see that you can associate only one element
- crearte a whishlist, then some product associating that whishlist to the product: then (error!) you will see that in in that whishlist the related products are not shown

##### **Related issues**
I could not find one

##### **Suggest a Fix**
- workaround:
1) starting point: workaround shown above (https://dadtechblog.com/2017/05/27/creating-a-master-detail-relationshipwith-jhipster/)
2) I will write an update (2019) of the fix
- fix: implement this functionality in the generator, using as a starting point how the manytomany relations are actually shwn in the left hand.

##### **JHipster Version(s)**
jhipsterVersion": "5.8.2",

##### **JHipster configuration**

INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
default-mod@0.0.0 /home/ciro/jy/defaultMod
└── generator-jhipster@5.8.2 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
    "generator-jhipster": {
        "promptValues": {
            "packageName": "it.plansoft"
        },
        "jhipsterVersion": "5.8.2",
        "applicationType": "monolith",
        "baseName": "defaultMod",
        "packageName": "it.plansoft",
        "packageFolder": "it/plansoft",
        "serverPort": "8080",
        "authenticationType": "jwt",
        "cacheProvider": "ehcache",
        "enableHibernateCache": true,
        "websocket": false,
        "databaseType": "sql",
        "devDatabaseType": "h2Disk",
        "prodDatabaseType": "postgresql",
        "searchEngine": false,
        "messageBroker": false,
        "serviceDiscoveryType": "eureka",
        "buildTool": "maven",
        "enableSwaggerCodegen": false,
        "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
        "clientFramework": "angularX",
        "useSass": true,
        "clientPackageManager": "npm",
        "testFrameworks": [],
        "jhiPrefix": "jhi",
        "entitySuffix": "",
        "dtoSuffix": "DTO",
        "otherModules": [],
        "enableTranslation": false
    }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Category {
  description String required,
  sortOrder Integer,
  dateAdded LocalDate,
  dateModified LocalDate,
  status CategoryStatus
}
entity Product {
  title String required,
  keywords String,
  description String,
  rating Integer,
  dateAdded LocalDate,
  dateModified LocalDate
}
entity Customer {
  firstName String,
  lastName String,
  email String,
  telephone String
}
entity Address {
  address1 String,
  address2 String,
  city String,
  postcode String required maxlength(10),
  country String required maxlength(2)
}
entity WishList {
  title String required,
  restricted Boolean
}

enum CategoryStatus {
  AVAILABLE,
  RESTRICTED,
  DISABLED
}

relationship OneToMany {
  WishList{product} to Product{wishList(title)},
  Customer{address} to Address{customer(firstName)},
  Customer{wishList} to WishList{customer(firstName)}
}
relationship ManyToOne {
  Category{parent} to Category
}
relationship ManyToMany {
  Category{product(title)} to Product{category(description)}
}

paginate Category, Customer with pagination
paginate Product with infinite-scroll
paginate Address with pager
service Category with serviceClass

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

git version 2.11.0

node: v8.15.1

npm: 6.9.0

INFO! Congratulations, JHipster execution is complete!

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
N/A
##### **Browsers and Operating System**

Linux+windows, all browswers

**Comment by cirotarini** [comment]
I have now a very simple workaround:
* you want to have a onetomany relationship between owners and pets, without the issue above **

1)
generate a jhipster app with this relation:
entity Owner {
    name String required
}
entity Pet {
    name String required,
    species String required
} 
relationship OneToMany {
    Owner{pet} to Pet{owner}
}


2) 
generate another jhipster app with the same relationship but now as ManyToMany

3)
in OwnerRepository, copy in the onetomany app the methods of the manytomany app:
    @Query(value = "select distinct owner from Owner owner left join fetch owner.pets",
        countQuery = "select count(distinct owner) from Owner owner")
    Page<Owner> findAllWithEagerRelationships(Pageable pageable);
    @Query(value = "select distinct owner from Owner owner left join fetch owner.pets")
    List<Owner> findAllWithEagerRelationships();
    @Query("select owner from Owner owner left join fetch owner.pets where owner.id =:id")
    Optional<Owner> findOneWithEagerRelationships(@Param("id") Long id);

4) 
in owner.java, add this decorator [@JsonIgnoreProperties("owner")]  to     private Set<Pet> 

5)
in src/main/webapp/app/entities/owner, copy  copy in the onetomany app those files from the manytomany app:

I don't know  yeoman so I can't do this fix by myself, but you should now have clear what to fix and how, if you want.
Hope this helps :)

**Comment by pascalgrimaud** [comment]
Hi @cirotarini,
Thanks for opening your 1st ticket with full detail. It's really appreciated.

I try to reproduce the issue you mentionned.
- I generated the project with the config you mentionned
- I generated the tables with your JDL
- I started the application and tried to reproduce each points

> create a category and some product for that category: then look at that category: the product are shown

It's OK for that point

> create some new category and then a new product: (error!) you can see that you can associate only one element

I created a new category.
Then go to product page, create some new products
Back to the previous category, and associate it to new products
It's OK for me here

> crearte a whishlist, then some product associating that whishlist to the product: then (error!) you will see that in in that whishlist the related products are not shown

That's the normal behavior, as it's defined like this, in your JDL.

To resume, I don't see any issue here, it's how your JDL and relationships work.
Then, don't forget the generated pages here are very simple. It should be used as example for implementing other complex pages. That's why we can't think about all use cases.

**Comment by pascalgrimaud** [comment]
I'm closing this as I think there is no issue.
Don't hesitate to comment if I'm wrong, then we can discuss and reopen if needed

**Comment by cirotarini** [comment]
Hi Pascal
I believe that, if you apply my workaround (posted above 6 days ago), the generated app will show the  onetomany relation more properly: if i click to see a  wishList, is good to have also all the Products listed.
with my workaround you have this with almost no work.
I believe that implementing this change in JHIPSTER will improve the tool, anyway I will propose this workaround in a little tutorial.
If my workaround is interesting but not clear enough pls let me know.

**Comment by pascalgrimaud** [comment]
Thanks @cirotarini !

If I understand well, you'd like to achieve the `Details for the owner Andrew with owned pets displayed.` screen in this article: https://dadtechblog.com/2017/05/27/creating-a-master-detail-relationship-with-jhipster/

So, it's an improvement and can be done by different ways:
- a tips at https://www.jhipster.tech/tips/ -> maybe the simpliest
- contributions directly to generator-jhipster -> I'm afraid our team don't have the bandwidth to do this, so your contributions are welcome. In that case, I can reopen this ticket if needed.  But if you decide to go this way, you should test with MongoDB and Couchbase too. Then, there will be Angular, React and Vue.js part. So for me, it's a lot of work for screens which will probably not used by real app in production.

**Comment by cirotarini** [comment]
let's go with the tip. Below there  is the tip that I propose. 
If you believe it helps, pls give me some istructions reg how to post it or post it directly
thanks :)!!

*******
--->>> Show childs (pets) in a one-to-many relationship (Owner->pets) 

When you create a one-to-many relationship (owners, pet), maybe you want that when the owner are listed, also the related pets are listed; and the same when you see the detail of a single owner: Maybe you want that related pets are shown.

Suppose you have those relations:
->Mary
->-> Leo
->-> Mac
->-Mark
->-> Sam
->TED

 in JHIPSTER, when you see Mary,  Pets Leo and  Mac are not listed – but, when you see Leo, Mary is listed as owner.

If you want that the pets are listed together with owners, let’s use this tip:

1)
generate a jhipster app with this relation:
entity Owner {
name String required
}
entity Pet {
name String required,
species String required
}
relationship OneToMany {
Owner{pet} to Pet{owner}
}

2)
generate another jhipster app with the same relationship but now as ManyToMany

3)
in OwnerRepository, copy in the onetomany app the methods of the manytomany app:
@query(value = "select distinct owner from Owner owner left join fetch owner.pets",
countQuery = "select count(distinct owner) from Owner owner")
Page findAllWithEagerRelationships(Pageable pageable);
@query(value = "select distinct owner from Owner owner left join fetch owner.pets")
List findAllWithEagerRelationships();
@query("select owner from Owner owner left join fetch owner.pets where owner.id =:id")
Optional findOneWithEagerRelationships(@param("id") Long id);
4)
in owner.java, add this decorator [@JsonIgnoreProperties("owner")] to private Set

5)
in src/main/webapp/app/entities/owner, copy in the onetomany app those files from the manytomany app in src/main/webapp/app/entities/owner:
owner-detail.component.html
owner.component.html


Hope this helps :)

**Comment by pascalgrimaud** [comment]
You can see the full list of tips here:
- https://www.jhipster.tech/tips/

About instructions:
- on GitHub, fork https://github.com/jhipster/jhipster.github.io
- clone locally your fork: https://github.com/cirotarini/jhipster.github.io
- go into this folder
- add upstream: `git remote add upstream https://github.com/jhipster/jhipster.github.io` -> so you'll be able to update your fork later
- then, create a branch with git
- create new page in `tips` folder, with your instruction
- update the summary: `pages/tips.md`
- git add and git commit your modification
- push to your fork project
- then, open a new pull request at https://github.com/jhipster/jhipster.github.io

If you have docker-compose, you can use it to test the site

**Comment by extraclassi** [comment]
Thanks @cirotarini !

I really need to make this work, thanks for your tips.

Just a quick question, when you say "generate another jhipster app with the same relationship but now as ManyToMany"

is it enough to write just :

ManyToMany{
Owner{pet} to Pet{owner}
}

?
