### ISSUE TITLE
When/How do you use ApplicationWebXml.java?

### ISSUE THREAD

**Issue by hooligan495** [jhipster/generator-jhipster#964]
Hi, 
  I'm trying to deploy a version of a Jhipster app to Jboss.  (it's failing but that's not why I'm writing this).  
In trying to debug I've started traveling down the road of the .war and .war.original that get generated.  I've changed the tomcat stuff from "compile" to "providedRuntime" but this lead me to thinking... (FWIW I am using the gradle part)

How should I be thinking about the different between gradle run (or bootRun) and building and deploying a war file?  Should I be doing something different for creating the war (by designating the main class as ApplicationWebXml vs just Application) Why are the 2 files there and when would I prefer one over the other?  

Also is there an easy way to specify the war file to be the unincluded tomcat stuff (the war.original)?
In reading the documentation I was left a little more confused than when I started so I thought I'd ask these questions and find the answers and if they were pertinent I could submit a pull request to the documentation of Jhipster?

**Comment by atomfrede** [comment]
I dont't know if that works but according to the [gradle documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#build-tool-plugins-gradle-packaging) 
> you need to mark the embedded container dependencies as belonging to a configuration named “providedRuntime”

Running
``./gradlew build``

Creates both the `.war` and `.war.original` file in `build/libs` as mentioned in the [official jhipster documentation](jhipster.github.io/production.html).

**Comment by jdubois** [comment]
For me this is more a Spring Boot question: we just offer you what Spring Boot gives by default.
Indeed, you have several ways of running the application: if you do want to use a WAR file, you either have one with an embedded Tomcat, or a "normal" one (this is the ".original"). Both should work on JBoss, but I would recommend using the "normal" one.
