### ISSUE TITLE
Can't logout/authenticate again because of CSRF token

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#965]
Here is how to trigger this issue:

- Log in
- Log out
- Log in again

You can't log in again, unless you refresh your browser.

Put the Spring Security logs to debug (or directly debug the CsrfFilter class, the issue is with the "actualToken") -> the issue is that the log out process has cancelled the CSRF cookie (which is normal, as when you log out everything should be cleared up), so when the CsrfFilter tries to check its token, it is failing.

I guess we should clear the token when a user logs out, but it might be more complex (what happens when a session times out?).

Ping @tgillieron as he coded this feature!

**Comment by tgillieron** [comment]
Off the top of my head, I would say that the removal of the authentication_check.if is the cause of this problem.

As you said on logout the CSRF cookie is cleared but the token is also removed from the spring session and the next time you will go through the filter chain a new token will be created.

Before the removal of the gif this next call would have been the
/protected/authentication_check.if request, creating new token and cookie as it is a GET request and is not checked for CSRF.

As a result of the removal of the gif the next call is the authentication, which is a POST and thus checked, causing the error.

To keep CSRF working we will need to retrieve a new token and keeping a call on state change to do that seems the more transparent solution for me. The call needs to trigger the filter chain.

**Comment by jdubois** [comment]
OK, this is quite complex to solve (I have spent a few hours on this and couldn't find a solution).
I will remove the CSRF protection for the moment (as we have currently in the v1.x releases), and re-schedule this for after the v2.x release.

**Comment by gzsombor** [comment]
Couldn't we add a simple exception to the CSRF filter, to allow calling the login method without the CSRF token ?

**Comment by jdubois** [comment]
@gzsombor good idea, I'll try it.

**Comment by jdubois** [comment]
This blog post from Pivotal is supposed to do the trick: http://spring.io/blog/2015/01/12/the-login-page-angular-js-and-spring-security-part-ii

**Comment by jdubois** [comment]
There is the same issue with the blog post from Pivotal...

**Comment by jdubois** [comment]
OK, the trick is to keep the X-CSRF-TOKEN when the user logs out

**Comment by gzsombor** [comment]
Is it works for you ? With these change, I still have the same login problem, but in this case the client sends the old csrf token, but -  because the http session has invalidated before (when the user logged out) - the CsrfFilter couldn't retreive it from the CsrfTokenRepository (which stores the token inside the session), so it will throw the MissingCsrfTokenException.
 So either, we should have a dummy backend method, just to initialize the session, with a new CSRF token,  ( for example GET /api/initSession ) - which needs to be called before login. Or we need to configure the CsrfFilter to allow posting to the /api/authentication without token

**Comment by tgillieron** [comment]
Removing the CSRF protection on the /api/authentification would not be my
preferred solution and implementing a dummy resource to initialize the
token before login would not be sufficient. It might allow login to work
but other no-authenticated option would still be broken (like
registration).

An other solution could be to have an http interceptor make the call to the
dummy resource before every POST/PUT/DELETE call that do not present a CSRF
token to initialize it.

Thomas GILLIERON
thomas.gillieron@gmail.com | +66 (0)6 86 20 29 37


2015-01-13 15:12 GMT+01:00 Zsombor <notifications@github.com>:

**Comment by gzsombor** [comment]
It would be very inefficient to create a separate http request before every login/registration/etc call, that would hurt the latency a bit, that's why I dont favor it.

**Comment by gzsombor** [comment]
I think, this ticket should be re-opened.

**Comment by jdubois** [comment]
It works for me... I'm reopening it, but we need to check what works and what doesn't work

**Comment by gzsombor** [comment]
Could you check, which request cause the re-generation of the token, before the /api/authentication call is fired ? 
 When I test with my test app, after I click on the 'logout' link, the login form appears, and when the login is tried, the post request either doesn't contain a token - with your fix - or contains, an invalid token, without your fix. In both case, the CsrfFilter blocks the attempt.

**Comment by jdubois** [comment]
@gzsombor I couldn't find how to re-generate the token, that's why I used my fix -> it also seems to be what other people (like Dave from the Pivotal blog), and it looks correct to me
So with my fix you should always have the token : I don't understand why you have an empty token

**Comment by gzsombor** [comment]
The token generation happens in the org.springframework.security.web.csrf.CsrfFilter.
With your solution :
 If you don't delete the CSRF-TOKEN cookie, then the client will send the old token - but the server could not validate it, because the session is already closed, when the user logged out. And the server stores the token inside the session. I guess, you somehow calls a different rest method - a http get , after the logout, but before the 'authentication' request, so you get a new token, both on the client and server side. Do you refresh the page ?

**Comment by jdubois** [comment]
@gzsombor I have the error too... It used to work, I'm sure of it!! More work to do on this part!

**Comment by gzsombor** [comment]
Good to know, that the error is not in my side :-)

**Comment by jdubois** [comment]
I've disabled CSRF again, can't find a solution :-(

**Comment by jgribonvald** [comment]
Just my 2 cents !
Did you watch on this example : https://spring.io/blog/2015/01/12/the-login-page-angular-js-and-spring-security-part-ii, the source code is given for tests

**Comment by jdubois** [comment]
@jgribonvald yes I tested it and they have the same issue!

**Comment by jgribonvald** [comment]
Ok yes i'm facing same problem, else is the problem related to this problem that was solved here : https://github.com/aditzel/spring-security-csrf-token-interceptor/issues/1

**Comment by jgribonvald** [comment]
This patch should work, at least it worked for me on last jhipster version.

The problem where on Angular apps side, the localStorageService.clearAll() was called before logout post request on server and after that a request on server side is needed to refresh in the browser the new csrf cookie.

Also i found something odd on app.js
//Cache everything except rest api requests
        httpRequestInterceptorCacheBusterProvider.setMatchlist([/.*rest.*/, /.*protected.*/], true);
this should not be 
//Cache everything except rest api requests
        httpRequestInterceptorCacheBusterProvider.setMatchlist([/.*api.*/, /.*protected.*/], true);
replace rest by api ?

And on _SecurityConfiguration.java
this line can be deleted .deleteCookies("JSESSIONID");
as the cookie deletion is normaly well managed automatically, expected maybe for hazelcast.

**Comment by svennela** [comment]
I ran into similar issue:

Click on Register
Click on login ( which is below register)
Try to login (it will redirect to register).
I am using OAuth with Jhipster 2.0. Any help
Really stuck.

**Comment by fromi** [comment]
I solved the problem this way:
`http.csrf().ignoringAntMatchers("/login")`

**Comment by yxly2008** [comment]
> I solved the problem this way:
> `http.csrf().ignoringAntMatchers("/login")`

thanks,it's worked for me

**Comment by vishal423** [comment]
>  http.csrf().ignoringAntMatchers("/login")

that's bad from security perspective.

**Comment by yxly2008** [comment]
> > http.csrf().ignoringAntMatchers("/login")
> 
> that's bad from security perspective.

you are right~my project is cas + springsecurity，but csrf makes single logout not work，i haven't another way to solve this problem.

**Comment by sameer123** [comment]
> > I solved the problem this way:
> > `http.csrf().ignoringAntMatchers("/login")`
> 
> thanks,it's worked for me

Please can you send in which file and where i have to put above line??

**Comment by gmarziou** [comment]
In SecurityConfiguration.java

**Comment by YehAndy** [comment]
I solve the problem by redirect to login url:
return "redirect:/login";
