### ISSUE TITLE
Need to document regarding deprecated stuff 

### ISSUE THREAD

**Issue by pmverma** [jhipster/generator-jhipster#9652]
##### **Overview of the issue**

In https://github.com/jhipster/generator-jhipster/pull/9384/files, method `getJhipsterAppConfig()` has been removed but respective doc has not been update at 
https://www.jhipster.tech/modules/creating-a-module/

This effect some module such as https://github.com/oktadeveloper/generator-jhipster-ionic/issues/68
##### **Motivation for or Use Case**

With updated doc, it is easy to migrate to new module version.

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by antarus** [comment]
Update documentation for gatling 3
