### ISSUE TITLE
Fake data generation doesn't honor validation rules (excepted maxlength)

### ISSUE THREAD

**Issue by murdos** [jhipster/generator-jhipster#9665]
##### **Overview of the issue**

Fields can have validation rules: https://www.jhipster.tech/jdl/#available-field-types-and-constraints
However generated data only take into account the maxlength one (for string), so this can lead to error when loading the data with liquibase.

##### **Motivation for or Use Case**

Have initial data that are coherent and won't generate errors when you try to update them.

##### **Reproduce the error**

The following JDL illustrates some issues, ~~uniqueness is described in #9579~~
```
entity A {
  myString String minlength(20) pattern(/[A-E]+/)
  myInteger Integer min(50) max(100)
  lang Language unique
  foo Boolean required unique
}

enum Language {
    FRENCH, ENGLISH, SPANISH, GERMAN, ITALIAN
}

```

generates:
```
id;my_string;my_integer;lang;foo
1;mobile Fish;77969;FRENCH;false
2;Trace;33370;FRENCH;false
3;transmitter Implementation Electronics;99221;FRENCH;true
4;Grocery Home;52477;FRENCH;false
5;Licensed Savings Account;38246;FRENCH;true
6;Yuan Renminbi Centers;1326;FRENCH;false
7;Public-key;24102;FRENCH;true
8;Salad;39106;FRENCH;true
9;convergence;20794;FRENCH;true
10;Views e-enable Communications;72727;FRENCH;true
```

Expected sample:
```
id;my_string;my_integer;lang;foo
1;ABABABABABABABABABABABAB;99;FRENCH;false
2;ABCDEABCDEABCDEABCDE;61;ENGLISH;true
```
There are only 2 lines because the boolean field is unique, so we can't generate more.

##### **Related issues**

~~#9579~~

##### **JHipster Version(s)**

6.0.0

**Comment by pascalgrimaud** [comment]
As we know there are some issues with Faker.js, shouldn't we regroup this ticket in https://github.com/jhipster/generator-jhipster/issues/9579 ?

**Comment by murdos** [comment]
There are different issues, each one with a different solution, so I would kept them separate.
#9579 issue is mainly about relationships. This one is about validation rules.

**Comment by murdos** [comment]
FYI I've updated the description to complete the JDL and better illustrate the issues.

**Comment by clement26695** [comment]
I started a PR to solve some of these issues.

Concerning uniqueness, there is a function in faker that could help (https://github.com/Marak/faker.js/blob/a9a11ee55ae1ae528ffc14c869a4c8353e2ba419/lib/unique.js#L6), but it is not in the latest release of fake.js (which was done in february 2017).

**Comment by clement26695** [comment]
And for regular expression, maybe use a tool like https://github.com/fent/randexp.js ?

**Comment by clement26695** [comment]
> And for regular expression, maybe use a tool like https://github.com/fent/randexp.js ?

I didn't saw we already used it for generating integration tests, so it should be ok. 

I'm open to reviews, if someone has the time to check my PR.

**Comment by pmverma** [comment]
@clement26695 @pascalgrimaud I would like to request to re-open this issue.
Because with some commit from #9736, now no fake records are being generated.
The exact line is 
https://github.com/jhipster/generator-jhipster/commit/2f7d58992c656ca196b2f681cd1ef6d89c71b81b

When I try to regenerate entity with master branch:

![image](https://user-images.githubusercontent.com/5289123/57943297-b3c91380-78f9-11e9-9ab4-5e41930f1ff8.png)

I tried with following entity.
```
{
    "fluentMethods": true,
    "clientRootFolder": "",
    "relationships": [],
    "fields": [
        {
            "fieldName": "myImage",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "myAnyBlob",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "any",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "myText",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "text",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20190514153814",
    "dto": "mapstruct",
    "searchEngine": false,
    "service": "serviceImpl",
    "entityTableName": "entity1",
    "databaseType": "sql",
    "jpaMetamodelFiltering": false,
    "pagination": "no"
}

```
If I revert to old condition `if (line.length > 0)`, it works.

**Comment by clement26695** [comment]
Indeed, I wanted to test that the line length was correct, but I didn't expect that 2 "fields" were added for each blob field.

It should be good with #9774. @pmverma, can you tell me if it's ok for you ?
