### ISSUE TITLE
Should the limitation on the password length (50 chars) be removed?

### ISSUE THREAD

**Issue by gomesp** [jhipster/generator-jhipster#967]
I noticed that the default password strength validation does not allow passwords longer than 50 chars. 

Is there any reason for it, since the passwords are stored as BCrypt hashes (which are actually 59 or 60 chars long ([ref 1][1], [ref 2][2], [ref 3][3])? Ideally there should be no reason to limit users on password length. Additionally, we can fix T_USER's password column to varchar(60) if what I am saying is correct. :)

ps: I am not a security expert, so please correct me where I am wrong.

[1]: http://stackoverflow.com/questions/5881169/what-column-type-length-should-i-use-for-storing-a-bcrypt-hashed-password-in-a-d
[2]: http://security.stackexchange.com/questions/6623/pre-hash-password-before-applying-bcrypt-to-avoid-restricting-password-length
[3]: http://en.wikipedia.org/wiki/Bcrypt

**Comment by jdubois** [comment]
- no reason to limit to 50 chars as far as I'm concerned, but this looks "big enough" for me
- I didn't know for the BCrypt hashes, but as it currently works, they are not 59 ou 60 chars long (otherwise nobody could change his password).

**Comment by jdubois** [comment]
In Liquibase, the field length is 100, that's why it's not a problem at the moment -> I agree it should be 60 (I checked it's 60 indeed), but it doesn't hurt to have more, and if people change the algorithm they might have an issue if we reduce the size
