### ISSUE TITLE
Adduser command broken docker image build with jdk11

### ISSUE THREAD

**Issue by ivan86to** [jhipster/generator-jhipster#9676]
##### **Overview of the issue**

Jenkins pipeline failed when build docker image because command adduser in exit with code: 1
-D and -s params not exist. 

##### **Motivation for or Use Case**

# adduser --help
adduser [--home DIR] [--shell SHELL] [--no-create-home] [--uid ID]
[--firstuid ID] [--lastuid ID] [--gecos GECOS] [--ingroup GROUP | --gid ID]
[--disabled-password] [--disabled-login] [--add_extra_groups] USER
   Add a normal user

adduser --system [--home DIR] [--shell SHELL] [--no-create-home] [--uid ID]
[--gecos GECOS] [--group | --ingroup GROUP | --gid ID] [--disabled-password]
[--disabled-login] [--add_extra_groups] USER
   Add a system user

adduser --group [--gid ID] GROUP
addgroup [--gid ID] GROUP
   Add a user group

addgroup --system [--gid ID] GROUP
   Add a system group

adduser USER GROUP
   Add an existing user to an existing group

general options:
  --quiet | -q      don't give process information to stdout
  --force-badname   allow usernames which do not match the
                    NAME_REGEX configuration variable
  --help | -h       usage message
  --version | -v    version number and copyright
  --conf | -c FILE  use FILE as configuration file

##### **Suggest a Fix**

Change RUN adduser -D -s /bin/sh jhipster
in
RUN adduser --shell /bin/sh --disabled-password --gecos "" jhipster
when use openjdk:11-jre-slim-stretch

##### **JHipster Version(s)**

6.0.0

##### **JHipster configuration**

JHipster UAA microservice

**Comment by pascalgrimaud** [comment]
@ivan86to : do you want to contribute and PR your fix ?

**Comment by ivan86to** [comment]
yes, of course! 
tnk!

**Comment by pascalgrimaud** [comment]
Fixed by https://github.com/jhipster/generator-jhipster/pull/9680
