### ISSUE TITLE
Generated Dockerfile expects war, but apps are packaged as jar

### ISSUE THREAD

**Issue by pdelaby** [jhipster/generator-jhipster#9677]
##### **Overview of the issue**

With Jhipster 6.0.0, the docker configuration expects a war : 
* `Dockerfile` add the application as a war `ADD *.war app.war` 
* The `entrypoint.sh` expect a war `exec java ${JAVA_OPTS} -noverify -XX:+AlwaysPreTouch -Djava.security.egd=file:/dev/./urandom -jar "${HOME}/app.war" "$@"`

But the application is packaged as jar  
* `<packaging>jar</packaging>` from `pom.xml`
* ` archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true` and ` sh "cp target/*.jar target/docker/"` in `Jenkinsfile` 

I can't explain why, but the build with maven jib works fine. 

##### **Motivation for or Use Case**

Cannot build the docker image

##### **Reproduce the error**

1. Generate jhipster 6.0.0 project 
2. use the ci-cd goal to build in jenkins
3. fix the adduser bug in dockerfile https://github.com/jhipster/generator-jhipster/issues/9676
4. launch a build 

You can also just generate the project, then build and try the dockerbuild in local

##### **Suggest a Fix**

*  `ADD *.jar app.jar` in `Dockerfile`
* `exec java ${JAVA_OPTS} -noverify -XX:+AlwaysPreTouch -Djava.security.egd=file:/dev/./urandom -jar "${HOME}/app.jar" "$@"`  in `entrypoint.sh`

##### **JHipster Version(s)**

6.0.0
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "fr.intoo.noda.passerelle.afludia",
      "nativeLanguage": "fr"
    },
    "jhipsterVersion": "6.0.0",
    "applicationType": "microservice",
    "baseName": "NodaPasserelleAfludia",
    "packageName": "fr.intoo..passerelle.afludia",
    "packageFolder": "fr/intoo/noda/passerelle/afludia",
    "serverPort": "8089",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "nop",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "clientPackageManager": "npm",
    "nativeLanguage": "fr",
    "languages": [
      "fr"
    ],
    "skipClient": true,
    "skipUserManagement": true,
    "enableHibernateCache": false
  }
}
</pre>

##### **Browsers and Operating System**

java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) Client VM (build 25.211-b12, mixed mode, sharing)

git version 2.21.0.windows.1

node: v10.13.0

npm: 6.4.1

yeoman: 2.0.5

yarn: 1.9.4

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
In fact, the generated Dockerfile in src/main/docker is not used anymore. It is still generated because some users asked to keep it.
But you're right, maybe we could improve it, and change from war to jar.

**Comment by pdelaby** [comment]
Thanks you very much for the correction. 
But I think the Dockerfile is still used by Jenkins : if you select "build docker image" and " when using the goal "jhipster ci-cd", it will genereate the following code (Jenkins pipeline)

```groovy
    def dockerImage
    stage('build docker') {
        sh "cp -R src/main/docker target/"
        sh "cp target/*.jar target/docker/"
        dockerImage = docker.build('my-docker-login/myprojectname', 'target/docker')
    }
```

And `docker.build` uses the `Dockerfile`. Is this a bug ? Shoud it use maven/graddle and jib ?

**Comment by pascalgrimaud** [comment]
Exactly, you're right @pdelaby ! It is still used by Jenkinsfile (just discovered it)

I think it would be better to be consistent and use jib for building Docker image in Jenkins pipelines too.

**Comment by PierreBesson** [comment]
The Dockerfile should be removed

**Comment by PierreBesson** [comment]
>I can't explain why, but the build with maven jib works fine.

This is because jib does not use a Dockerfile but has it's own internal mechanism that you configure in the pom.

**Comment by PierreBesson** [comment]
Removing the Dockerfile shouldn't cause much problems as jib will release the offline mode in the coming days: https://github.com/GoogleContainerTools/jib/milestone/31?closed=1

After jib 1.2.0 release, I will update our jib version and refresh our docker docs.

**Comment by trixprod** [comment]
Moreover using "RUN adduser -D -s /bin/sh jhipster" with openjdk:11-jre-slim-stretch is broken.

```
Step 3/10 : RUN adduser -D -s /bin/sh jhipster
 ---> Running in 2abf79f1d781
[91mOption d is ambiguous (debug, disabled-login, disabled-password)
Option s is ambiguous (shell, system)
[0madduser [--home DIR] [--shell SHELL] [--no-create-home] [--uid ID]
[--firstuid ID] [--lastuid ID] [--gecos GECOS] [--ingroup GROUP | --gid ID]
[--disabled-password] [--disabled-login] [--add_extra_groups] USER
   Add a normal user

adduser --system [--home DIR] [--shell SHELL] [--no-create-home] [--uid ID]
[--gecos GECOS] [--group | --ingroup GROUP | --gid ID] [--disabled-password]
[--disabled-login] [--add_extra_groups] USER
   Add a system user
```

Please, can we get an upgrade for jenkins ci-cd to generate jib build and deploy docker image.

**Comment by PierreBesson** [comment]
I don't understand what dockerfile you are talking about ? Anyway if it's the one in stc/main/docker it's going to be removed.
For the Jenkinsfile that uses jib, you can have a look at my PR : https://github.com/jhipster/generator-jhipster/pull/9688

I would greatly appreciate feedback on it.

**Comment by amatosg** [comment]
@pascalgrimaud I'm surprised and very curious about this, why is the generated dockerfile not used anymore?

**Comment by pascalgrimaud** [comment]
See https://twitter.com/fdelbrayelle/status/1127236438586793984?s=19
It's in french. In needed, I can translate to you later (when I'll be with computer instead of phone)

**Comment by PierreBesson** [comment]
To translate my twitter post:
> Actually, we don't generate a Dockerfile anymore and the docker build is no longer copying a fatjar in a  unique docker layer. Jib let us have something more optimized with maven dependency and application bytecode in separate layers in order to make a better use of docker caching.
> Moreover, the application is started with `java -cp` rather than executing the jar which help us improve startup time slightly as we don't have to decompress the jar anymore.
> And the best benefit is that Jib can create a docker image without using the docker daemon (which needs to be root   😱). This is very useful for CI and to avoid "docker in docker".

> Question: A while ago I ran `./mvnw -Pprod verify jib:dockerBuild` and got an error as my docker daemon was stopped. However it is stated that "Jib builds optimized Docker (...) without a Docker daemon". Is it normal ?

> Answer: Actually you need to do a `mvn jib:build` to use this mode (`mvn jib:dockerBuild` delegates to the docker daemon). However it requires a connection to a docker registry as the built image still needs to go somewhere if you don't have docker installed.
