### ISSUE TITLE
Invalid access token on swagger-ui

### ISSUE THREAD

**Issue by ArnaudPiroelle** [jhipster/generator-jhipster#968]
With last development version, i have this unexpected error when i try to access to swagger when i'm connected as admin user: 
```
{"error":"invalid_token","error_description":"Invalid access token: c8c2c9a4-997f-4637-bcc7-1ef8f53a9a2a"}
```

My config is:
```
{
  "generator-jhipster": {
    "baseName": "myApp",
    "packageName": "com.arnaudpiroelle.app",
    "packageFolder": "com/arnaudpiroelle/app",
    "authenticationType": "token",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "hazelcast",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "useCompass": false,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "javaVersion": "8"
  }
}
```

**Comment by flythebluesky** [comment]
I may be seeing a similar problem. Does this happen after your login times
out? (i.e. log in an wait until the login token has expired)
You can reset this by deleting the token from the browser's local storage.
For example, in then Chrome browser, go to developer console -> resources
-> local storage

**Comment by jdubois** [comment]
Yes, it is an issue with CSRF, so I'm linking this to #965

As this is very complex to solve, I will disable CSRF protection for the moment (like we had for v1), and schedule it for after the v2 release

**Comment by jdubois** [comment]
OK, now I've work this issue better: if your login times out, and you use "cookie based authentication", there is no solution possible.
I'm closing this as it's not possible to fix it, but of course I'm not happy with this answer!
