### ISSUE TITLE
Refreshing react web page result in a error:Error occured while trying to proxy to: localhost:9000/login

### ISSUE THREAD

**Issue by sandyway** [jhipster/generator-jhipster#9683]
##### **Overview of the issue**
If I directly open any react web page not from the main page,or refresh a web page which is not main page,there will be a error:Error occured while trying to proxy to: localhost:9000/somePageNotMain

example:
If I input "http://localhost:9000/login" to the chrome url,then return,there will be a error:
"Error occured while trying to proxy to: localhost:9000/login"

![11](https://user-images.githubusercontent.com/6972903/57267853-2a714000-70b4-11e9-89ad-f8d1bc744470.png)

##### **Motivation for or Use Case**
we need to jump to a web page directly,not from the main page.

##### **Reproduce the error**

1. Generate a new project by online application generator from https://start.jhipster.tech/#/generate-application
2. Execute "npm i"
3. Execute "npm start" to open the web page "http://localhost:9000".
4. Click the sign in button to open the web page "http://localhost:9000/login".
5. refresh the web page "http://localhost:9000/login",then I get a error:"Error occured while trying to proxy to: localhost:9000/login".

##### **JHipster Version(s)**
6.0.0

##### **JHipster configuration**
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
track-server@0.0.0 /Users/songway/Downloads/trackServer
└── generator-jhipster@6.0.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "gitCompany": "",
    "baseName": "trackServer",
    "packageName": "mobi.kehan.track",
    "packageFolder": "mobi/kehan/track",
    "serverPort": 8156,
    "serviceDiscoveryType": false,
    "authenticationType": "jwt",
    "uaaBaseName": "../uaa",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "enableSwaggerCodegen": "true",
    "messageBroker": false,
    "buildTool": "maven",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "zh-cn",
      "zh-tw",
      "en"
    ],
    "clientFramework": "react",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "6.0.0",
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "clientTheme": "none",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": []
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.20.1 (Apple Git-117)

node: v10.15.0

npm: 6.9.0

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

INFO! Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**
browser: Chrome 73.0.3683.103
Operating System: mac os 10.14.4

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
Do you have the backend started? From the reproduction instructions, I don't see you running `./mvnw` or `./gradlew`

**Comment by pascalgrimaud** [comment]
Just tested and it works well, if you start the backend, with `maven`, as suggested by @ruddell (thanks to  you !)
I'm closing this.
