### ISSUE TITLE
CORS not working properly with newly generated setup

### ISSUE THREAD

**Issue by mai1015** [jhipster/generator-jhipster#9684]
##### **Overview of the issue**
In development mode, CORS setting not working. CORS header “Access-Control-Allow-Origin” missing.

##### **Motivation for or Use Case**
I deploy keycloak at different domain from jhipster application. It is not allow to access other domain's resource.

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://open.example.com/auth/realms/jhipster/protocol/openid-connect/auth?response_type=code&client_id=web_app&scope=openid%20roles%20phone%20address%20jhipster%20email%20offline_access%20web-origins%20profile&state=oXgoERs2kV9ljdgvbsDm3IhrcJh_QHt9mD6vY_eTvok%3D&redirect_uri=http://localhost:8080/login/oauth2/code/oidc. (Reason: CORS header “Access-Control-Allow-Origin” missing).
```

##### **Reproduce the error**
Generate the project with command. Then setup the oauth url to different domain. Start the project with `./gradlew` then access.
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://open.example.com/auth/realms/jhipster/protocol/openid-connect/auth?response_type=code&client_id=web_app&scope=openid%20roles%20phone%20address%20jhipster%20email%20offline_access%20web-origins%20profile&state=oXgoERs2kV9ljdgvbsDm3IhrcJh_QHt9mD6vY_eTvok%3D&redirect_uri=http://localhost:8080/login/oauth2/code/oidc. (Reason: CORS header “Access-Control-Allow-Origin” missing).
```

##### **Related issues**
none, the header is absent.

##### **Suggest a Fix**
Cors configuration is not working

##### **JHipster Version(s)**
6.0.0

##### **JHipster configuration**

INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
app-data@0.0.0 /home/coder/project/jhipster/AppData
└── generator-jhipster@6.0.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "top.furry.app.data",
      "nativeLanguage": "zh-cn"
    },
    "jhipsterVersion": "6.0.0",
    "applicationType": "monolith",
    "baseName": "AppData",
    "packageName": "top.furry.app.data",
    "packageFolder": "top/furry/app/data",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mariadb",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": true,
    "clientFramework": "react",
    "clientTheme": "solar",
    "clientThemeVariant": "primary",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "zh-cn",
    "languages": ["zh-cn", "zh-tw", "en"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment (build 11.0.2+9-Ubuntu-3ubuntu118.04.3)
OpenJDK 64-Bit Server VM (build 11.0.2+9-Ubuntu-3ubuntu118.04.3, mixed mode, sharing)

git version 2.17.1

node: v10.15.3

npm: 6.4.1

yeoman: 2.0.6

Docker version 18.09.5, build e8ff056

docker-compose version 1.24.0, build 0aa59064

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
none

##### **Browsers and Operating System**
Ubuntu 18.04
Firefox 66.0.4

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
If you set a different domain, you need to update the web origins in Keycloak. This is not a JHipster issue.

**Comment by pascalgrimaud** [comment]
Matt is probably right, that's why I'm closing this.
Don't hesitate to comment if needed

**Comment by tiagodiogo** [comment]
hello @mraible and @pascalgrimaud 
i am experiencing the same problem reported by @mai1015 
i have adjusted the web origins to * and valid redirect urls to * for testing purposes and the CORS header is still missing.

i have generated a fresh and clean application using the latest jhipster version for this (v6.4.1)
can you confirm this problem or am i missing additional configurations?
![image](https://user-images.githubusercontent.com/4720374/67276351-6b231100-f4bc-11e9-9599-73aa41b59507.png)

**Comment by tiagodiogo** [comment]
further information...
![image](https://user-images.githubusercontent.com/4720374/67276429-9574ce80-f4bc-11e9-9891-a1b636903952.png)

**Comment by mai1015** [comment]
@tiagodiogo I tested few month ago, I don't really remember how it works. I assume the CORS does not apply to this URL since CORS is not present in the response header. I tried to modify with reverse proxy using Nginx. It works well without warming. So, I assume it is the way jhipster implements CORS does not apply to the home page. BTW, I do not know if the access is really necessary.

**Comment by tiagodiogo** [comment]
@mai1015 
thank you for taking the time to reply
setting the cors header on the reverse proxy seems like a hack to me but so far the only way to go around this issue.
there is a newer issue referring to this situation: https://github.com/jhipster/generator-jhipster/issues/10642
maybe you wan't to keep an eye on it
