### ISSUE TITLE
aws generator throws Error: EISDIR 

### ISSUE THREAD

**Issue by kr0** [jhipster/generator-jhipster#9685]
##### **Overview of the issue**
Using the aws generator with a fresh app produces this error during "Upload JAR to S3" step: 
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, read
```

##### **Motivation for or Use Case**
I am trying to deploy an application to aws.

##### **Reproduce the error**
After installing jhipster/having appropriate aws credentials, Create a new folder, run jhipster, run jhipster aws.

##### **Related issues**
This error reads the same as #2447.

##### **JHipster Version(s)**

```
app@0.0.0 /Users/me/Developer
└── generator-jhipster@6.0.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.myapp"
    },
    "jhipsterVersion": "6.0.0",
    "applicationType": "monolith",
    "baseName": "app",
    "packageName": "com.myapp",
    "packageFolder": "com/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "rememberMeKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "clientFramework": "react",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.3+7, mixed mode)

git version 2.8.1

node: v8.16.0

npm: 6.4.1

yeoman: 1.8.5

yarn: 1.4.0

Docker version 18.09.1, build 4c52b90

docker-compose version 1.23.2, build 1110ad01
##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
In the team, we have no possibility to test and maintain this sub generator, as AWS doesn't sponsor us.

@kr0 : so feel free to analyze the error and submit the fix with a PR.

If no one want to do it, I'll suggest to remove this sub generator, as it is useless to keep something broken for long time.

**Comment by kr0** [comment]
Ok, I'll look into it. For the record, I tried various lts node releases as well. My hunch is that it is related to a missing / somewhere. Will report back if anything. Also, deployment using boxfuse seems to work at the moment.

**Comment by jdubois** [comment]
This was done by the Ippon team in Australia, @pascalgrimaud could you contact them? I had the same concern when I merged it, but they told me they would maintain it.
Otherwise yes let's remove this.

**Comment by pascalgrimaud** [comment]
Ok, I'll try to find maintainers at Ippon
Thanks for your help @kr0
