### ISSUE TITLE
Broken Link header 

### ISSUE THREAD

**Issue by gordolio** [jhipster/generator-jhipster#9690]
##### **Overview of the issue**

The `Link` header in api responses does not include the full base path.

##### **Motivation for or Use Case**

This prevents the use of the header to get the next page of a result set, or number of pages.

##### **Reproduce the error**

Create an app with the following config...
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "6.0.0",
    "applicationType": "monolith",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "",
    "clientFramework": "react",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-swagger-cli",
        "version": "3.0.1"
      },
      {
        "name": "generator-jhipster-audit-helper",
        "version": "1.0.3"
      },
      {
        "name": "generator-jhipster-administration-database",
        "version": "1.0.4"
      },
      {
        "name": "generator-jhipster-jgitver",
        "version": "0.1.0"
      }
    ],
    "enableTranslation": false
  }
}

```
1. Open dev tools
2. Login to a jhipster app.
3. Administration >> User Management
The `Link` header does not include full path.

`Link: <http://localhost:8080?sort=id%2Casc&page=0&size=20>; rel="last",<http://localhost:8080?sort=id%2Casc&page=0&size=20>; rel="first"`

##### **Related issues**

Issues with the Link header have been reported previously, but I believe this particular issue is new due to new usage of UriComponentsBuilder from spring-web to generate this link in jhipster 6.

##### **Suggest a Fix**

Modify io.github.jhipster.web.util.PaginationUtil to get the correct info from UriComponentsBuilder...

However, it looks like org.springframework.web.util.ServletUriComponentsBuilder isn't getting the full path.
`org.springframework.web.util.UrlPathHelper.getPathWithinServletMapping` returns a blank string.

##### **JHipster Version(s)**

6.0.0

##### **JHipster configuration**

Configuration is above

##### **Browsers and Operating System**

MacOS 10.14.4, Google Chrome 74.0.3729.131
-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by gordolio** [comment]
It looks like UriComponentsBuilderMethodArgumentResolver only gives the context path ("/deployed-context") rather than the full HttpRequestPath ("/deployed-context/api/users").

The argument type UriComponentsBuilder should not be used to build requests for the PaginationUtil where the full request path is necessary.

The way I see it, there are 2 options...
1. Refactor the generator to no longer use UriComponentsBuilder as an argument to all the pagination resources.
2. Create a jhipster version of UriComponentsBuilderMethodArgumentResolver that will provide a UriComponentsBuilder using the method `ServletUriComponentsBuilder.fromRequest(HttpServletRequest)` rather than the method `ServletUriComponentsBuilder.fromServletMapping(HttpServletRequest)`.

**Comment by pascalgrimaud** [comment]
Can you have a look at this file ?
https://github.com/jhipster/jhipster/blob/master/jhipster-framework/src/main/java/io/github/jhipster/web/util/PaginationUtil.java

If you can help to fix this, PR are welcome !

**Comment by jdubois** [comment]
Yes that was changed recently - if you can do a "git blame" I believe the author will help.

**Comment by DanielFran** [comment]
See #https://github.com/jhipster/generator-jhipster/pull/9379

@cbornet Can you check this please?

**Comment by jdubois** [comment]
For me this could be a good first issue.
I'm adding a bug bounty to motivate people.

**Comment by duderoot** [comment]
I need in one of my JHipster projects to dig in more to understand what headers values are we using and I think that we need to put in the path. In Sprig  exist an issue [#21449](https://github.com/spring-projects/spring-framework/issues/21449) where is tald that one need to add the path to the UriComponentsBuilder.

**Comment by DanielFran** [comment]
@gordiolo Can you test PR from @duderoot and confirm if it fixes the ussue, please?
