### ISSUE TITLE
React UI: enum values incorrectly displayed as "[object Object]" 

### ISSUE THREAD

**Issue by standors** [jhipster/generator-jhipster#9694]
##### **Overview of the issue**

React UI: entity enum values incorrectly displayed as "[object Object]" 
 instead of enum value as is defined in JDL file.
The same is if you click enum field and drop down list contains all items with the same values: "[object Object]" 
"[object Object]" 
....
"[object Object]" 

##### **Reproduce the error**

1. generate new src with jhipster generator "jhipsterVersion": "6.0.0"
language is "sk" 
2. JDL with ENUMS imported 
3. start web application
4. select Entity "Price Category"  .... this entity contains 3 enum values.

5. click "create new" entity.
in opened view all entity filds of type Enum shows always text: "[object Object]"  instead of enum value as is defined in JDL file.

##### **JHipster Version(s)**
jhipster version 6.0.0

##### **JHipster configuration**

INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
##### **JHipster Version(s)**

```
sse@0.0.0 /home/myproj/proj/myproj/src/sse
└── generator-jhipster@6.0.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "se",
      "nativeLanguage": "sk"
    },
    "jhipsterVersion": "6.0.0",
    "applicationType": "monolith",
    "baseName": "sse",
    "packageName": "se",
    "packageFolder": "se",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": ",,,,,",
    "clientFramework": "react",
    "clientTheme": "flatly",
    "clientThemeVariant": "primary",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "sk",
    "languages": ["sk"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity PriceCategory {
  meteringPlaceType MeteringPlaceType,
  categoryDone CategoryDone,
  employmentType EmploymentType,
  dateCreated LocalDate,
  above1000 Boolean,
  price Float
}
entity EmploymentTypeHistory {
  employmentType EmploymentType,
  date LocalDate
}
entity Employee {
  assignedFirstname String maxlength(50),
  assignedLastname String maxlength(50),
  username String maxlength(50),
  email String maxlength(255),
  mobileNumber String maxlength(255)
}
entity MeteringPlaceOwner
entity MeteringPlace {
  meteringPlaceId Long
}
entity ItinerarMeteringPlace {
  itinerarMeteringPlaceSystemId Long,
  itinerarId Long,
  objectIdentifier Long,
  placeIdentifier Long,
  meteringPlaceType MeteringPlaceType,
  operatorId Long,
  batchId Long,
  routeId Long,
  routeDate LocalDate,
  batchSystemId String maxlength(255),
  meteringDate LocalDate
}
entity CategoryDoneRange {
  categoryDone CategoryDone unique,
  lower Float,
  upper Float
}
entity EmployeePlanCorrection {
  correctionRd Integer,
  correctionBd Integer,
  correctionLaz Integer,
  correctionAnomal Integer,
  correctionDate LocalDate
}

enum MeteringPlaceType {
  BD,
  RD,
  LAZ
}

enum CategoryDone {
  DONE_100,
  DONE_98,
  DONE_95,
  DONE_92,
  DONE_50,
  DONE_0
}

enum EmploymentType {
  FAKTURANT,
  DVP
}

relationship OneToMany {
  Employee{employmentType} to EmploymentTypeHistory{employee(assignedLastname)},
  Employee{itinerarMeteringPlace} to ItinerarMeteringPlace{employee(assignedLastname)},
  Employee{employeePlanCorrection} to EmployeePlanCorrection{employee(assignedLastname)}
}

dto PriceCategory, EmploymentTypeHistory, Employee, MeteringPlaceOwner, MeteringPlace, ItinerarMeteringPlace, CategoryDoneRange, EmployeePlanCorrection with mapstruct
paginate PriceCategory, EmploymentTypeHistory, Employee, MeteringPlaceOwner, MeteringPlace, ItinerarMeteringPlace, CategoryDoneRange, EmployeePlanCorrection with pagination
service PriceCategory, EmploymentTypeHistory, Employee, MeteringPlaceOwner, MeteringPlace, ItinerarMeteringPlace, CategoryDoneRange, EmployeePlanCorrection with serviceClass
filter PriceCategory, EmploymentTypeHistory, Employee, MeteringPlaceOwner, MeteringPlace, ItinerarMeteringPlace, CategoryDoneRange, EmployeePlanCorrection

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

git version 2.11.0

node: v8.15.0

npm: 6.9.0

yeoman: 2.0.5

yarn: 1.12.3

Docker version 18.09.2, build 6247962

docker-compose version 1.22.0, build f46880fe

INFO! Congratulations, JHipster execution is complete!
##### **Browsers and Operating System**

 -->
The same problem is with browsers: Firefox 66.0.4 (64-bit) and Chromium (Version 73.0.3683.75 (Developer Build) built on Debian 9.8, running on Debian 9.7 (64-bit))

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by SoniaLahi** [comment]
Hi, 

This is not linked to enums. The tags inside the <option> are not interpreted apparently.
Replacing the tag <Translate/> with the related javascript method translate solves the problem. 

Meaning, to display the translations in the list, changing :
<option value="SPANISH">
  **<Translate contentKey="jhipsterEnumApp.Language.SPANISH" />**
</option>

to the following works :
<option value="SPANISH">
  **{translate("jhipsterEnumApp.Language.SPANISH")}**
</option>

**Comment by pascalgrimaud** [comment]
It looks like to be a valid solution, as I can see `{translate("...")}` is used everywhere too.
Would you like to contribute and PR your fix @SoniaLahi ?

**Comment by SoniaLahi** [comment]
yes, I can @pascalgrimaud

**Comment by MathieuAA** [comment]
It may be because that having the `Translate` component  inside a basic `option` tag doesn't render it as expected (object instead of a string)...
