### ISSUE TITLE
Unable to use underscore in appFolders when using jdl file

### ISSUE THREAD

**Issue by asmolabs** [jhipster/generator-jhipster#9699]
##### **Overview of the issue**

We can use an underscore in baseName. When we use it, jhipster generate a folder with and underscore.

But we can't use an underscore in appFolders array. Jhipster generate a regex exception

##### **Motivation for or Use Case**
If we can use an underscore in baseName we must we able to use it in appFolders

##### **Reproduce the error**

Generate an microservice app and a gateway with underscore in baseName.
Try to use folder name with and underscore in appFolders in jdl files

##### **JHipster Version(s)**
6.0.0

##### **Browsers and Operating System**
Ubuntu 18.04

**Comment by pascalgrimaud** [comment]
It seems related to:
- https://github.com/jhipster/generator-jhipster/issues/9335
- https://github.com/jhipster/jhipster-core/pull/312

Could you provide more information, with some JDL and your `jhipster info` ? So it will be easier to try to reproduce

**Comment by asmolabs** [comment]
Jdl File

//gateway
application {
  config {
    baseName com_xxx,
    packageName com.xxx.gateway,
    buildTool maven,
    applicationType gateway,
    authenticationType oauth2,
    databaseType sql,
    prodDatabaseType mysql,
    devDatabaseType mysql,
    nativeLanguage fr,
    languages    [fr, nl],
    serviceDiscoveryType eureka,
    serverPort 8080,
    useSass true,
    testFrameworks[protractor, gatling]
  }
  entities *
}
 
//adresse 
application {
 config {
    baseName com_xxx_core,
    packageName com.xxx.core,
    applicationType microservice,
    buildTool maven,
    authenticationType oauth2,
    messageBroker kafka,
    prodDatabaseType mysql,
    devDatabaseType mysql,
    serviceDiscoveryType eureka,
    searchEngine elasticsearch,
    serverPort 8081
  }
  entities Test
}
microservice Test with com_core

//common
dto * with mapstruct
service all with serviceImpl
paginate * with pagination

deployment {
  deploymentType docker-compose
  appsFolders [com_xxx,, com_xxx_core]
  dockerRepositoryName "xxx"
  monitoring elk
}

Jhipster info
INFO! Using JHipster version installed globally
INFO! Executing jhipster:info
INFO! Options: from-cli: true
##### **JHipster Version(s)**

```
/home/vagrant/Dev/Civadis/Csd/Rd/frt-bo
└── (empty)

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>


##### **Environment and Tools**

openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.18.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

git version 2.17.1

node: v10.15.3

npm: 6.4.1

**Comment by asmolabs** [comment]
INFO! The JDL is being parsed.
error: Error message:
        The appsFolders property name must match: /^[A-Za-z][A-Za-z0-9]*$/
        at line: 49, column: 16
The appsFolders property name must match: /^[A-Za-z][A-Za-z0-9]*$/
        at line: 49, column: 25
SyntaxError: Error: The appsFolders property name must match: /^[A-Za-z][A-Za-z0-9]*$/
        at line: 49, column: 16
The appsFolders property name must match: /^[A-Za-z][A-Za-z0-9]*$/
        at line: 49, column: 25
ERROR! Error while parsing applications and entities from the JDL SyntaxError: Error: The appsFolders property name must match: /^[A-Za-z][A-Za-z0-9]*$/
        at line: 49, column: 16
The appsFolders property name must match: /^[A-Za-z][A-Za-z0-9]*$/
        at line: 49, column: 25
SyntaxError: Error: The appsFolders property name must match: /^[A-Za-z][A-Za-z0-9]*$/
        at line: 49, column: 16

**Comment by Shaolans** [comment]
To be able to use underscore on appsFolders, we need to change ```ALPHANUMERIC``` to ```ALPHANUMERIC_UNDERSCORE``` [here](https://github.com/jhipster/jhipster-core/blob/master/lib/dsl/validator.js#L194-L198)

**Comment by Shaolans** [comment]
And your jdl still can't be parsed because of ```microservice Test with com_core``` due to [here](https://github.com/jhipster/jhipster-core/blob/master/lib/dsl/validator.js#L472)

**Comment by pascalgrimaud** [comment]
So do you confirm the issue @Shaolans or not ?
If yes, do you have a fix for that ?

**Comment by Shaolans** [comment]
Looks like it is, I think we can simply change the validation pattern. I will investigate deeper to confirm that fix.
