### ISSUE TITLE
Let bower/wiredep install non compass boostrap files

### ISSUE THREAD

**Issue by andidev** [jhipster/generator-jhipster#970]
At the moment the bootsrap files for a non compass project is included in the template of the generator rather than it is included in the bower.json (where the bootstrap-sass is for some reason included instead). The installation should be made by bower/wiredep.

Fix this issue after the PR of #956 is merged.

**Comment by andidev** [comment]
Issue is fixed, awaiting PR #969 to be merged

**Comment by jdubois** [comment]
PR merged!

**Comment by andidev** [comment]
Actually this issue is not fixed. PR #969 did not remove the bootstrap-sass dependency on non compass generated projects.

I'll provide you with a PR right away.

**Comment by andidev** [comment]
see question in #1007 before merging this
