### ISSUE TITLE
Access to microservice from gateway failed after 5 minute idle, re authentication required

### ISSUE THREAD

**Issue by eapriansyah** [jhipster/generator-jhipster#9707]
##### **Overview of the issue**
When the user is idle for more than 5 minutes, access from the browser to microservice is not authenticated.

##### **Motivation for or Use Case**
After 5 minute idle, access to the entire menu in the gateway, no need for authentication, only related to the microservice that needs authentication. For public users, it will be a bit confusing.

##### **Reproduce the error**

1. Create a gateway application with security oauth2.
2. Create a microservice application with security oauth2.
3. Create one entity with the description field on microservice.
4. run "jhipster entity Data1" from the command prompt
5. Copy entity to gateway, do same thing with command "jhipster entity Data1 --skip-server"
6. Run gateway and microservice, open Data-1 from entities->Data 1

##### **Gateway Configuration **
jhipster info
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
gateway@0.0.0 D:\tmp\check-zuul\gw
`-- generator-jhipster@6.0.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany"
    },
    "jhipsterVersion": "6.0.0",
    "applicationType": "gateway",
    "baseName": "gateway",
    "packageName": "com.mycompany",
    "packageFolder": "com/mycompany",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "ehcache",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Data1 {
  description String
}
dto Data1 with mapstruct
paginate Data1 with pagination
service Data1 with serviceClass
microservice Data1 with svc
clientRootFolder Data1 with svc

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)

git version 2.19.1.windows.1

node: v10.15.3

npm: 6.9.0

yeoman: 2.0.6

yarn: 1.9.4

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

##### **Microservice Configuration **
jhipster info
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
svc@0.0.0 D:\tmp\check-zuul\svc
`-- generator-jhipster@6.0.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany"
    },
    "jhipsterVersion": "6.0.0",
    "applicationType": "microservice",
    "baseName": "svc",
    "packageName": "com.mycompany",
    "packageFolder": "com/mycompany",
    "serverPort": "8082",
    "authenticationType": "oauth2",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "clientPackageManager": "npm",
    "skipClient": true,
    "skipUserManagement": true
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Data1 {
  description String
}
dto Data1 with mapstruct
paginate Data1 with pagination
service Data1 with serviceClass
microservice Data1 with svc
clientRootFolder Data1 with svc

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)

git version 2.19.1.windows.1

node: v10.15.3

npm: 6.9.0

yeoman: 2.0.6

yarn: 1.9.4

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

-   [x] Checking this box is mandatory (this is just to show you read everything)

First Open Page:

![image](https://user-images.githubusercontent.com/1936249/57406096-2eaf7180-720a-11e9-9c2d-842ec1022781.png)

After 5 Minute, and click edit in Form:
![image](https://user-images.githubusercontent.com/1936249/57406429-e5abed00-720a-11e9-9462-1b26b743a22a.png)

![image](https://user-images.githubusercontent.com/1936249/57406439-ecd2fb00-720a-11e9-8656-e0ec657a9435.png)

**Comment by mraible** [comment]
You mentioned "Microsoft". Are you using Microsoft as your OIDC provider? If so, does the same behavior happen with Keycloak?

**Comment by eapriansyah** [comment]
No that is typo, I mean microservice.

**Comment by mraible** [comment]
Hmmm, it sounds like Spring Security might not be fetching refresh tokens and renewing access tokens for you. I'm not sure how to fix just yet.

**Comment by ruddell** [comment]
It looks like the path name is included in the OAuth2 redirect [here](https://github.com/jhipster/generator-jhipster/blob/a88374f1001e82177540b7d57ada6a56291f3ca3/generators/client/templates/angular/src/main/webapp/app/core/login/login.service.ts.ejs#L44-L55), it should only include the base HREF and not the path.  I did a fix for websockets which had a similar issue ([changes](https://github.com/jhipster/generator-jhipster/pull/9593/files#diff-0fafb68cae8b1df22c864e2357efb964))

**Comment by Tcharl** [comment]
Same behavior here: no refresh token fetched from Keycloak (part of the OAuth2AuthenticationToken)

**Comment by Tcharl** [comment]
Let me historize what I'm doing within my current project to have a 6.0.0 oauth2+Microservice support.
Feel free to comment (or even implement a PR based on it if you're sure that's the right way, I'm not that available ATM but will try to make something if I don't see it implemented in a month). I'll continue to amend that comment until I'll have something which 'just works'.

* Angular login.service
Use the trick by @ruddell  to redirect to the base href
const baseHref = document.querySelector('base').getAttribute('href').replace(/\/$/, '');
```

    location.href = `//${location.hostname}${port}${baseHref}/oauth2/authorization/oidc`;
```

- expired and error interceptors

Change `err.url.includes('/api/account')` by `err.url.includes('api/account')`

- create an angular component and route to avoid it complaining about non existing mapping at the token response
```

export const OAUTH_ROUTE: Route = {
  path: 'login/oauth2/code/oidc',
  component: OauthComponent,
};
export const AUTH_ROUTES = [LOGIN_ROUTE, OAUTH_ROUTE];

@Component({
  selector: 'jhi-login',
  templateUrl: './login.component.html',
  styleUrls: ['login.component.scss']
})
export class OauthComponent implements OnInit {
  constructor(private router: Router, private logger: NGXLogger) {}

  ngOnInit() {
    this.router.navigate(['/']).then(() => this.logger.debug('redirected user after auth'));
  }
}

```

- Security configuration
redirect oauth auth to a login page that calls the login service if not authenticated on init
```
       .and()
            .oauth2Login()
            .loginPage("/")
```

- Create a JwtConfiguration containing the decoder to be able to consume it as a bean (not mandatory)

- Create an implementation of JwtAuthenticationConverter
```

@Configuration
public class AuthorityConfiguration extends JwtAuthenticationConverter {

    public AuthorityConfiguration() {
    }

    protected Collection<GrantedAuthority> extractAuthorities(Jwt jwt) {
        return SecurityUtils.extractAuthorityFromClaims(jwt.getClaims());
    }
}
public static List<GrantedAuthority> extractAuthorityFromClaims(Map<String, Object> claims) {
        return ((JSONArray)((JSONObject)claims.get("realm_access")).get("roles")).stream()
            .map(group -> ((String) group))
            .filter(group -> group.startsWith("ROLE_"))
            .map(SimpleGrantedAuthority::new).collect(Collectors.toList());
    }
```

- Amend the AuthorizationHeaderUtil to handle either Oauth2AccessToken (gateway) and Jwt (service to service with Feign). Also Throw an exception while the token as expired (may be we can throw it in another place like a filter?

```
public Optional<String> getAuthorizationHeader() {
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        if (authentication instanceof OAuth2AuthenticationToken) {
            OAuth2AuthenticationToken oauthToken = (OAuth2AuthenticationToken) authentication;
            String name =  oauthToken.getName();
            String registrationId = oauthToken.getAuthorizedClientRegistrationId();
            OAuth2AuthorizedClient client = clientService.loadAuthorizedClient(
                registrationId,
                name);

            if (null == client) {
SecurityContextHolder.getContext().setAuthentication(null);
                throw new OAuth2AuthorizationException(new OAuth2Error("access_denied", "The token is expired", null));
                //throw new CredentialsExpiredException("Credentials have expired");
            }
            OAuth2AccessToken accessToken = client.getAccessToken();

            if (accessToken != null) {
                String tokenType = accessToken.getTokenType().getValue();
                String accessTokenValue = accessToken.getTokenValue();
                if (isExpired(accessToken)) {
                    throw new OAuth2AuthorizationException(new OAuth2Error("access_denied", "The token is expired", null));
                    /* TODO best solution
                    log.info("AccessToken expired, refreshing automatically");
                    accessTokenValue = refreshToken(client, oauthToken);*/
                }
                String authorizationHeaderValue = String.format("%s %s", tokenType, accessTokenValue);
                return Optional.of(authorizationHeaderValue);
            }

        } else if (authentication instanceof JwtAuthenticationToken) {
            JwtAuthenticationToken accessToken = (JwtAuthenticationToken) authentication;
            String tokenType = (String) accessToken.getToken().getClaims().get("typ");
            String tokenValue = accessToken.getToken().getTokenValue();
            String authorizationHeaderValue = String.format("%s %s", tokenType, tokenValue);
            return Optional.of(authorizationHeaderValue);
        }
        return Optional.empty();
    }
```

- Throw a 401 in case of OAuth2AuthorizationException (which will trigger another login dance):
```

 @ExceptionHandler
    public ResponseEntity<Problem> handleConcurrencyFailure(OAuth2AuthorizationException ex, NativeWebRequest request) {
        Problem problem = Problem.builder()
            .withStatus(Status.UNAUTHORIZED)
            .with(MESSAGE_KEY, ErrorConstants.AUTH_EXPIRED)
            .build();
        return create(ex, problem, request);
    }
```

Side stuff:

Update the GrantedAuthorityMapper to handle Keycloak mappings:
```

/**
     * Map authorities from "groups" or "roles" claim in ID Token.
     *
     * @return a {@link GrantedAuthoritiesMapper} that maps groups from
     * the IdP to Spring Security Authorities.
     */
    @Bean
    @SuppressWarnings("unchecked")
    public GrantedAuthoritiesMapper userAuthoritiesMapper() {
        return (authorities) -> {
            Set<GrantedAuthority> mappedAuthorities = new HashSet<>();

            authorities.forEach(authority -> {
                OidcUserAuthority oidcUserAuthority = (OidcUserAuthority) authority;
                OidcUserInfo userInfo = oidcUserAuthority.getUserInfo();
                Collection<String> groups = (Collection<String>) userInfo.getClaims().get("roles");
                mappedAuthorities.addAll(groups.stream()
                    .filter(group -> group.startsWith("ROLE_"))
                    .map(SimpleGrantedAuthority::new).collect(Collectors.toList()));
            });

            return mappedAuthorities;
        };
    }
```

NOTA.

I found a refresh token implementation on the net (in kotlin), but it does not seem to work on our case (I've tried putting it in the AuthorizationHeaderUtil. If someone is motivated, here's the Java transpilled code:
```

private String refreshToken(OAuth2AuthorizedClient client, OAuth2AuthenticationToken oauthToken) {
        OAuth2AccessTokenResponse atr = refreshTokenClient(client);
        if (atr == null || atr.getAccessToken() == null) {
            log.info("Failed to refresh token for ${currentUser.name}");
            return null;
        }

        OAuth2RefreshToken refreshToken = atr.getRefreshToken() != null? atr.getRefreshToken(): client.getRefreshToken();
        OAuth2AuthorizedClient updatedClient = new OAuth2AuthorizedClient(
            client.getClientRegistration(),
            client.getPrincipalName(),
            atr.getAccessToken(),
            refreshToken
        );

        clientService.saveAuthorizedClient(updatedClient, oauthToken);
        return atr.getAccessToken().getTokenValue();
    }

    private OAuth2AccessTokenResponse refreshTokenClient(OAuth2AuthorizedClient currentClient ) {

        MultiValueMap<String, String> formParameters = new LinkedMultiValueMap<>();
        formParameters.add(OAuth2ParameterNames.GRANT_TYPE, AuthorizationGrantType.REFRESH_TOKEN.getValue());
        formParameters.add(OAuth2ParameterNames.REFRESH_TOKEN, currentClient.getRefreshToken().getTokenValue());
        formParameters.add(OAuth2ParameterNames.REDIRECT_URI, currentClient.getClientRegistration().getRedirectUriTemplate());


        RequestEntity requestEntity = RequestEntity
            .post(URI.create(currentClient.getClientRegistration().getProviderDetails().getTokenUri()))
            .contentType(MediaType.APPLICATION_FORM_URLENCODED)
            .body(formParameters);
        try {
            RestTemplate r = restTemplate(currentClient.getClientRegistration().getClientId(), currentClient.getClientRegistration().getClientSecret());
            ResponseEntity<OAuth2AccessTokenResponse> responseEntity = r.exchange(requestEntity, OAuth2AccessTokenResponse.class);
            return responseEntity.getBody();
        } catch (OAuth2AuthorizationException e) {
            log.error("Unable to refresh token ${e.error.errorCode}");
            throw new OAuth2AuthenticationException(e.getError(), e);
        }
    }

    private RestTemplate restTemplate(String clientId, String clientSecret)

    {
        return restTemplateBuilder
            .additionalMessageConverters(
                new FormHttpMessageConverter(),
                new OAuth2AccessTokenResponseHttpMessageConverter())
            .errorHandler(new OAuth2ErrorResponseErrorHandler())
            .basicAuthentication(clientId, clientSecret)
            .build();
    }

    private boolean isExpired(OAuth2AccessToken accessToken) {
        Instant now = Instant.now();
        Instant expiresAt = accessToken.getExpiresAt();
        return now.isAfter(expiresAt.minus(Duration.ofMinutes(1L)));
    }
```

**Comment by mraible** [comment]
Could be related to this issue: https://github.com/spring-projects/spring-security-oauth2-boot/issues/125

**Comment by eapriansyah** [comment]
The solution to overcome this problem, as follows.
1. Add spring-cloud-starter-oauth2 in pom.
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-oauth2</artifactId>
        </dependency>
2. Change SecurityConfiguration.java as follows:

@EnableWebSecurity
@EnableGlobalMethodSecurity(prePostEnabled = true, securedEnabled = true)
@EnableOAuth2Sso
@Import(SecurityProblemSupport.class)
public class SecurityConfiguration extends WebSecurityConfigurerAdapter {

    private final CorsFilter corsFilter;

    @Value("${spring.security.oauth2.client.provider.oidc.issuer-uri}")
    private String issuerUri;

    private final SecurityProblemSupport problemSupport;

    public SecurityConfiguration(CorsFilter corsFilter, SecurityProblemSupport problemSupport) {
        this.corsFilter = corsFilter;
        this.problemSupport = problemSupport;
    }

    @Override
    public void configure(WebSecurity web) throws Exception {
        web.ignoring()
            .antMatchers(HttpMethod.OPTIONS, "/**")
            .antMatchers("/app/**/*.{js,html}")
            .antMatchers("/i18n/**")
            .antMatchers("/content/**")
            .antMatchers("/swagger-ui/index.html")
            .antMatchers("/test/**");
    }

    @Override
    public void configure(HttpSecurity http) throws Exception {
        // @formatter:off
        http
            .csrf()
            .csrfTokenRepository(CookieCsrfTokenRepository.withHttpOnlyFalse())
        .and()
            .addFilterBefore(corsFilter, CsrfFilter.class)
            // .addFilterAfter(oAuth2AuthenticationProcessingFilter(), AbstractPreAuthenticatedProcessingFilter.class)
            .exceptionHandling()
            .accessDeniedHandler(problemSupport)
        .and()
            .headers()
            .frameOptions()
            .disable()
        .and()
            .authorizeRequests()
            .antMatchers("/api/**").authenticated()
            .antMatchers("/api/auth-info").permitAll()
            .antMatchers("/websocket/tracker").hasAuthority(AuthoritiesConstants.ADMIN)
            .antMatchers("/websocket/**").permitAll()
            .antMatchers("/management/health").permitAll()
            .antMatchers("/management/info").permitAll()
            .antMatchers("/management/prometheus").permitAll()
            .antMatchers("/management/**").hasAuthority(AuthoritiesConstants.ADMIN)
        .and()
            .oauth2Login()
        .and()
            .oauth2ResourceServer().jwt();
        // @formatter:on
    }

    /**
     * Map authorities from "groups" or "roles" claim in ID Token.
     *
     * @return a {@link GrantedAuthoritiesMapper} that maps groups from
     * the IdP to Spring Security Authorities.
     */
    @Bean
    @SuppressWarnings("unchecked")
    public GrantedAuthoritiesMapper userAuthoritiesMapper() {
        return (authorities) -> {
            Set<GrantedAuthority> mappedAuthorities = new HashSet<>();

            authorities.forEach(authority -> {
                OidcUserAuthority oidcUserAuthority = (OidcUserAuthority) authority;
                OidcUserInfo userInfo = oidcUserAuthority.getUserInfo();
                Collection<String> groups = (Collection<String>) userInfo.getClaims().get("groups");
                if (groups == null) {
                    groups = (Collection<String>) userInfo.getClaims().get("roles");
                }
                mappedAuthorities.addAll(groups.stream()
                    .filter(group -> group.startsWith("ROLE_"))
                    .map(SimpleGrantedAuthority::new).collect(Collectors.toList()));
            });

            return mappedAuthorities;
        };
    }

    @Bean
    JwtDecoder jwtDecoder() {
        NimbusJwtDecoderJwkSupport jwtDecoder = (NimbusJwtDecoderJwkSupport)
            JwtDecoders.fromOidcIssuerLocation(issuerUri);

        OAuth2TokenValidator<Jwt> audienceValidator = new AudienceValidator();
        OAuth2TokenValidator<Jwt> withIssuer = JwtValidators.createDefaultWithIssuer(issuerUri);
        OAuth2TokenValidator<Jwt> withAudience = new DelegatingOAuth2TokenValidator<>(withIssuer, audienceValidator);

        jwtDecoder.setJwtValidator(withAudience);

        return jwtDecoder;
    }

    @Bean
    public AuthorizationHeaderFilter authHeaderFilter(AuthorizationHeaderUtil headerUtil) {
        return new AuthorizationHeaderFilter(headerUtil);
    }

    @Bean
    @ConfigurationProperties("spring.security.oauth2.client")
    public ClientCredentialsResourceDetails oauth2RemoteResource() {
        return new ClientCredentialsResourceDetails();
    }

    @Bean
    @Primary
    public OAuth2RestTemplate restTemplate(OAuth2ClientContext clientContext) {
        return new OAuth2RestTemplate(oauth2RemoteResource(), clientContext);
    }
}

**Comment by mraible** [comment]
@EnableOAuth2Sso is deprecated in Spring Security 5.1 in favor of oauth2Login() as part of the configure() method. Does it work if you remove that annotation?

**Comment by eapriansyah** [comment]
Yes it works, with additional bean:

@Bean
    @ConfigurationProperties("spring.security.oauth2.client")
    public ClientCredentialsResourceDetails oauth2RemoteResource() {
        return new ClientCredentialsResourceDetails();
    }

    @Bean
    public OAuth2ClientContext oauth2ClientContext() {
       return new DefaultOAuth2ClientContext(new DefaultAccessTokenRequest());
    }

    @Bean
    public OAuth2RestTemplate restTemplate(OAuth2ClientContext clientContext) {
        return new OAuth2RestTemplate(oauth2RemoteResource(), clientContext);
    }

**Comment by eapriansyah** [comment]
Alternatively, act as client refer from this https://docs.spring.io/spring-security-oauth2-boot/docs/current-SNAPSHOT/reference/htmlsingle/

@EnableOAuth2Client
and add bean:
@Bean
    @ConfigurationProperties("spring.security.oauth2.client")
    public ClientCredentialsResourceDetails oauth2RemoteResource() {
        return new ClientCredentialsResourceDetails();
    }

@Bean
    public OAuth2RestTemplate oauth2RestTemplate(OAuth2ClientContext oauth2ClientContext,
        OAuth2ProtectedResourceDetails details) {
        return new OAuth2RestTemplate(details, oauth2ClientContext);
    }

**Comment by mraible** [comment]
If it’s not too much trouble, can you please create a pull request with this change? I’d be happy to review it.

https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-a-pull-request

I’ll also add $100 bounty to this issue.

**Comment by pascalgrimaud** [comment]
Just added the bounty @mraible

**Comment by mraible** [comment]
I've been able to reproduce this problem with Spring Boot and Spring Security. The fix suggested doesn't work. I'll consult with my colleagues and try to figure out a solution.

**Comment by eapriansyah** [comment]
Sorry, I made a mistake. My test folder is mixed with jhipster v5, in the microservice. So the problem is still there. Sorry for this misunderstanding.

**Comment by Stjerndal** [comment]
> I've been able to reproduce this problem with Spring Boot and Spring Security. The fix suggested doesn't work. I'll consult with my colleagues and try to figure out a solution.

So the bug is in Spring Security 5.1 rather than jhipster?

**Comment by mraible** [comment]
I think it's in JHipster. I believe this might be caused by a change I made in AuthorizationHeaderUtil:

https://github.com/jhipster/generator-jhipster/pull/9416/files#diff-0626afa9caefec7aca2255c6f6a50173L35

In the Spring Security 5.0 version, we used an `OAuth2RestTemplate` to get the access token, rather than from the `OAuth2AuthorizedClient`. We also had error handling when a `UserRedirectRequiredException` happened.

**Comment by Tcharl** [comment]
May be my implementation does fix the stuff.
At least it work for Gateways to services via backend (Feign), our production product hasn't had any noticed bug from now

**Comment by mraible** [comment]
From @jzheaux of the Spring Security team:

> You're absolutely right that the commit you linked to is making the difference. Spring Security 5.x doesn't yet automatically refresh the OAuth token. It does have an `ExchangeFilterFunction` that refreshes the token, which can be used with `WebClient`.
> 
> There's currently a 5.2 ticket open that Joe is working on that will lead to that logic being extracted into something more general purpose: https://github.com/spring-projects/spring-security/issues/6811.

**Comment by Tcharl** [comment]
the `getAuthorizationHeader()` implementation I posted in the ticket refreshes the token (so it's OK for Feign calls), however, I don't know the new equivalent of the `OAuth2RestTemplate` to hook that token refresh.
Does anyone know which bean it is?

**Comment by pascalgrimaud** [comment]
I'm closing this as https://github.com/jhipster/generator-jhipster/pull/9874 has been merged.
Then, maybe it can be improved but the solution proposed by @Tcharl works!
