### ISSUE TITLE
No client option

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#9708]
##### **Overview of the feature request**

Since we now have a question for the front-end framework we can also propose a `No client` choice that has the same effect as `--skipClient`

##### **Motivation for or Use Case**

I think JHipster can be used for every type of applications, even monolithic ones without front-end

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by murdos** [comment]
+1
I'm just wondering: since this could be already achieved by selecting the application type `microservice`, 
what would be the fundamental difference between a monolith with no client and a microservice with no registry?

**Comment by avdev4j** [comment]
I feel people used to generate server and client sides separately so this option could be more user friendly than the flag `--skip-server`. Same for a gateway

**Comment by murdos** [comment]
The question behind my previous question is: do we still need to keep and store the `applicationType` that the user has selected, or is this is just a way to filter further questions that the generator will prompt?

**Comment by cbornet** [comment]
The main remaining difference between a micro-service and a monolith is that you can authenticate on a monolith whereas on a micro-service authentication happens on the gateway.
