### ISSUE TITLE
vendor chunk voids angular's vendor lazy loading

### ISSUE THREAD

**Issue by arslan2012** [jhipster/generator-jhipster#9714]
##### **Overview of the issue**
I have used XLSX library in lazy loaded admin module.
XLSX is a big library so I would like it to be lazy loaded.
with the default webpack config the library will be bundled into vendor chunk.
<details>
<summary>disabling vendor chunk enables @angular/webpack 's built-in lazy loading.</summary>

```javascript
 optimization: {
        runtimeChunk: false,
-        splitChunks: {
-            cacheGroups: {
-                commons: {
-                    test: /[\\/]node_modules[\\/]/,
-                    name: 'vendors',
-                    chunks: 'all'
-                }
-            }
-        },
        minimizer: [
```
</details>
before disabling vendor chunk:

```
322K    4.46f85c2914a76bd36340.bundle.js
143K    5.46f85c2914a76bd36340.bundle.js
64K     6.46f85c2914a76bd36340.bundle.js
38K     7.46f85c2914a76bd36340.bundle.js
81K     8.46f85c2914a76bd36340.bundle.js
69K     9.46f85c2914a76bd36340.bundle.js
74K     10.46f85c2914a76bd36340.bundle.js
58K     11.46f85c2914a76bd36340.bundle.js
94K     12.46f85c2914a76bd36340.bundle.js
73K     13.46f85c2914a76bd36340.bundle.js
95K     14.46f85c2914a76bd36340.bundle.js
944     global.46f85c2914a76bd36340.bundle.js
489K    main.46f85c2914a76bd36340.bundle.js
1.6K    polyfills.46f85c2914a76bd36340.bundle.js
3.8M    vendors.46f85c2914a76bd36340.bundle.js
```
after disabling vendor chunk:

```
1014K   3.e1c8ba8edf4a0067d4ba.bundle.js
322K    4.e1c8ba8edf4a0067d4ba.bundle.js
30K     5.e1c8ba8edf4a0067d4ba.bundle.js
143K    6.e1c8ba8edf4a0067d4ba.bundle.js
64K     7.e1c8ba8edf4a0067d4ba.bundle.js
38K     8.e1c8ba8edf4a0067d4ba.bundle.js
81K     9.e1c8ba8edf4a0067d4ba.bundle.js
69K     10.e1c8ba8edf4a0067d4ba.bundle.js
74K     11.e1c8ba8edf4a0067d4ba.bundle.js
58K     12.e1c8ba8edf4a0067d4ba.bundle.js
94K     13.e1c8ba8edf4a0067d4ba.bundle.js
73K     14.e1c8ba8edf4a0067d4ba.bundle.js
95K     15.e1c8ba8edf4a0067d4ba.bundle.js
944     global.e1c8ba8edf4a0067d4ba.bundle.js
3.2M    main.e1c8ba8edf4a0067d4ba.bundle.js
63K     polyfills.e1c8ba8edf4a0067d4ba.bundle.js

```

##### **JHipster Version(s)**

```
canton@0.0.0 /home/arslan/Documents/bisaibang-canton
└── generator-jhipster@6.0.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": false,
    "jhiPrefix": "bsb",
    "languages": ["en", "fr"],
    "messageBroker": false,
    "nativeLanguage": "en",
    "packageName": "com.bisaibang.canton",
    "packageFolder": "com/bisaibang/canton",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "serviceDiscoveryType": false,
    "skipClient": false,
    "skipServer": false,
    "testFrameworks": [],
    "websocket": "spring-websocket",
    "applicationType": "monolith",
    "baseName": "canton",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "useSass": true,
    "serverPort": "8090",
    "jhipsterVersion": "6.0.0",
    "buildTool": "maven",
    "skipUserManagement": false,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "clientTheme": "none",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": []
  },
  "entities": ["Config", "Video", "Picture", "Tournament", "MatchGame", "Article", "Team"]
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
/**
 * @author Arslan Ablikim.
 */
entity Config {
  bannerUrlArray String,
  homePage String
}
/**
 * @author Arslan Ablikim.
 */
entity Video {
  url String required,
  type VideoType,
  name String,
  game Game,
  thumbnail String,
  createTime Instant required,
  description String
}
/**
 * @author Arslan Ablikim.
 */
entity Picture {
  url String required,
  type PictureType,
  name String,
  game Game,
  createTime Instant required,
  folder String
}
/**
 * @author Arslan Ablikim.
 */
entity Tournament {
  name String required,
  type TournamentType,
  matchgameType MatchGameType required,
  game Game,
  createTime Instant required,
  location String,
  city String,
  college String,
  bonus String,
  description String,
  rule String,
  result String,
  thumbnail String,
  state TournamentState
}
/**
 * @author Arslan Ablikim.
 */
entity MatchGame {
  playerType PlayerType required,
  sequence Long required,
  scoreA Integer,
  scoreB Integer,
  json TextBlob,
  nextSequence Long
}
/**
 * @author Arslan Ablikim.
 */
entity Article {
  name String required,
  content String,
  type ArticleType,
  thumbnail String,
  createDate Instant
}
/**
 * @author Arslan Ablikim.
 */
entity Team {
  name String required,
  logo String,
  game Game,
  score String
}
entity RecruitmentBoard {
  school String,
  location String,
  slogan String,
  qq String,
  game Game,
  state RecruitmentBoardState,
  modificationDate Instant,
  tournamentType TournamentType
}

enum VideoType {
  Advert,
  MatchRecord
}

enum Game {
  ValorOfKing,
  PUBG
}

enum PictureType {
  Tournament
}

enum TournamentType {
  CITY,
  COLLEGE
}

enum MatchGameType {
  SingleElimination,
  Scoreboard
}

enum TournamentState {
  ENROLLING,
  BALLOTING,
  MATCHING,
  ENDED
}

enum PlayerType {
  User,
  Team
}

enum ArticleType {
  TOURNAMENT,
  OFFICIAL,
  RESULT,
  USER
}

enum RecruitmentBoardState {
  RECRUITING,
  FULL
}

relationship OneToMany {
  Tournament{matchGames} to MatchGame{tournament}
}
relationship ManyToOne {
  Video{tournament} to Tournament,
  Picture{tournament} to Tournament,
  MatchGame{userA} to User,
  MatchGame{userB} to User,
  MatchGame{teamA} to Team,
  MatchGame{teamB} to Team,
  Article{tournament} to Tournament,
  Team{captain} to User,
  RecruitmentBoard{user(login)} to User
}
relationship ManyToMany {
  Tournament{teams} to Team,
  Tournament{participants} to User,
  Team{member} to User
}

service Config, Video, Picture, Tournament, MatchGame, Article, Team, RecruitmentBoard with serviceClass
paginate Video, Picture, Article, RecruitmentBoard with infinite-scroll
search Video, Picture, Tournament, Article, Team, RecruitmentBoard with elasticsearch

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-b01)
OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)

git version 2.21.0

node: v11.14.0

npm: 6.9.0

yeoman: 2.0.6

yarn: 1.15.2

Docker version 18.09.5-ce, build e8ff056dbc

docker-compose version 1.24.0, build unknown

**Comment by wmarques** [comment]
Good catch, I need to analyze where the other libs go if we remove the `vendors` chunk. I'll check this
