### ISSUE TITLE
Ability to define comfortable identifier field on CRUD UI instead of ID

### ISSUE THREAD

**Issue by ArthurFromDnipro** [jhipster/generator-jhipster#9738]
Ability to define comfortable identifier field on CRUD UI instead of ID.
##### **Overview of the feature request**
For example,
`entity Company {
    name String viewId
}`
Keyword 'viewId' or other will say: "This field will be shown on UI, instead of just ID,
when user selects one such entities on Create or Edit form of **other** _related_ entity."

##### **Motivation for or Use Case**

This will allow to use comfortable identifier for entity, when user selects it
on UI instead of just ID.

##### **Related issues or PR**

AS I know, no related issues.

-   [.] Checking this box is mandatory (this is just to show you read everything)

**Comment by ArthurFromDnipro** [comment]
remove, if duplicate, please

**Comment by pascalgrimaud** [comment]
Thanks for your proposal.

But I'm not sure it should be done, as it's against our Policy 2: only add options when there is sufficient added-value in the generated code

> It’s easier to code those lines manually than to learn a new JHipster option
> It will only make our generator more complex without adding any value

**Comment by ruddell** [comment]
This is already possible, see the `display-field` documented in the [JDL Relationship docs](https://www.jhipster.tech/jdl/#relationshipdeclaration)

For example, with the below JDL, the Author's `name` field is listed in the drop-down when creating/editing a Book entity:
```
entity Book
entity Author {
  name String required
}

relationship OneToMany {
  Author{book} to Book{writer(name) required}
}
```

**Comment by pascalgrimaud** [comment]
Thanks @ruddell
But I thought he's talking about the 'id', displayed in the title of update page. 
Anyway, it wasn't clear enough
