### ISSUE TITLE
[Atmosphere] Wrong dependency

### ISSUE THREAD

**Issue by jfarcand** [jhipster/generator-jhipster#974]
Users reported jhipster is using `atmosphere-runtime-native` as dependency. It should use `atmosphere-runtime` instead as native is for [Tomcat 6 and old JBoss version](https://github.com/Atmosphere/atmosphere/wiki/Installing-AtmosphereServlet-with-or-without-native-support)

**Comment by jdubois** [comment]
Thanks @jfarcand -> as we don't have Atmosphere at the moment I'm closing this, I'll add it again when we put Atmosphere back
