### ISSUE TITLE
H2 database does not work in project created with the --skip-client option

### ISSUE THREAD

**Issue by AndreKrebs** [jhipster/generator-jhipster#9746]
##### **Overview of the issue**

To create a monolithic project with only the backend, I used the command jhipster --skip-client and when I use this option the H2 database fails API initialization with the following error:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under '' to com.zaxxer.hikari.HikariDataSource:

    Property: driverclassname
    Value: org.h2.Driver
    Origin: "driverClassName" from property source "source"
    Reason: Failed to load driver class org.h2.Driver in either of HikariConfig class loader or Thread context classloader

Action:

Update your application's configuration
```

##### **Motivation for or Use Case**

With version 5.8.2, when creating a monolithic project with database H2 and parameter --skip-client the database does not fail and version 6.0.1 is failing.

##### **Reproduce the error**

On a Windows 10 system, by PowerShell:
- mkdir backTesteJhipster
- cd backTesteJhipster
- jhipster --skip-client

And select the following options:

- Which *type* of application would you like to create? Monolithic application (recommended for simple projects)
- What is the base name of your application? backTesteJhipster
- What is your default Java package name? com.testback
- Do you want to use the JHipster Registry to configure, monitor and scale your application? No
- Which *type* of authentication would you like to use? JWT authentication (stateless, with a token)
- Which *type* of database would you like to use? SQL (H2, MySQL, MariaDB, PostgreSQL, Oracle, MSSQL)
- Which *production* database would you like to use? MySQL
- Which *development* database would you like to use? H2 with disk-based persistence
- Do you want to use the Spring cache abstraction? Yes, with the Ehcache implementation (local cache, for a single node)
- Do you want to use Hibernate 2nd level cache? Yes
- Would you like to use Maven or Gradle for building the backend? Maven
- Which other technologies would you like to use? (Press <space> to select, <a> to toggle all, <i> to invert selection)
- Would you like to enable internationalization support? Yes
- Please choose the native language of the application Portuguese (Brazilian)
- Please choose additional languages to install (Press <space> to select, <a> to toggle all, <i> to invert selection)
- Besides JUnit and Jest, which testing frameworks would you like to use? (Press <space> to select, <a> to toggle all, <i> to invert selection)
- Would you like to install other generators from the JHipster Marketplace? No

Open STS-4, import the project as Maven project and wait for the IDE import process, into "Boot Dashboard", select the imported project and click "(Re)start" and wait for API initialization, error occurs during startup.

##### **JHipster Version(s)**

Version is 6.0.1 and it's not a regression.

##### **JHipster configuration**

JHipster info: 

```
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
back-teste-jhipster@0.0.0 C:\Users\andre.silva\Documents\workspace-sts\backTesteJhipster
`-- generator-jhipster@6.0.1

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.testback",
      "nativeLanguage": "pt-br"
    },
    "jhipsterVersion": "6.0.1",
    "applicationType": "monolith",
    "baseName": "backTesteJhipster",
    "packageName": "com.testback",
    "packageFolder": "com/testback",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "clientPackageManager": "npm",
    "nativeLanguage": "pt-br",
    "languages": [
      "pt-br"
    ],
    "skipClient": true
  }
}
</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>


##### **Environment and Tools**

java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

git version 2.21.0.windows.1

node: v10.15.3

npm: 6.4.1

yarn: 1.15.2

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

INFO! Congratulations, JHipster execution is complete!
```

The .yo-rc.json:

```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.testback",
      "nativeLanguage": "pt-br"
    },
    "jhipsterVersion": "6.0.1",
    "applicationType": "monolith",
    "baseName": "backTesteJhipster",
    "packageName": "com.testback",
    "packageFolder": "com/testback",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "ZTBjMzZlNmQ5YzVmZWY5N2UyNGVkNWQxYjFjYTI1NTE4NzVkYjdlZDcxYzU5Yjk3OThjOTkxYjk0NDVlOTY0ZDMzM2MzZDU1MTMxZDUwNWMyODI1YjhhN2FlNTY2MWEyOTIyNjAwNGQ4MWJkZmMwY2RhZGIwYWM3MjIwNTNjMTU=",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "clientPackageManager": "npm",
    "nativeLanguage": "pt-br",
    "languages": [
      "pt-br"
    ],
    "skipClient": true
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

No entities were generated in this project.

##### **Browsers and Operating System**

Problem occurs in Windows 10 Pro during startup in the STS-4 IDE.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by SoniaLahi** [comment]
Hi @AndreKrebs,

This error is related to STS.
Running the command `mvn springboot-run` starts the application. Hence, it is not a JHipster bug.

As a work-around you can create a custom maven build : 
Run > Run configurations ... > Maven Build > New configuration 
- base directory :  your project path
- goal :  `spring-boot:run`

For more info : https://stackoverflow.com/a/49556593/10018727

**Comment by pascalgrimaud** [comment]
Thanks @SoniaLahi 
As it's not a JHipster bug, I'm closing this

**Comment by HJK181** [comment]
The correct answer for STS users would be:
- Right click on the project > maven > select maven profiles ... > choose: dev as this pulls in h2 as compile dependency.

**Comment by mrsimple1982** [comment]
> The correct answer for STS users would be:
> 
> * Right click on the project > maven > select maven profiles ... > choose: dev as this pulls in h2 as compile dependency.

Thanks, this was helpful.

**Comment by seqqueman** [comment]
> 
> 
> The correct answer for STS users would be:
> 
>     * Right click on the project > maven > select maven profiles ... > choose: dev as this pulls in h2 as compile dependency.

Great solutions. Many thanks.
