### ISSUE TITLE
Add the H2DB console to the Administration menu

### ISSUE THREAD

**Issue by andidev** [jhipster/generator-jhipster#975]
It would be nice to have the possibility to go the the H2DB console through the administration menu. Also it would be nice that it then would be opened in a page with the navbar present. This is possible if the console is placed in an `<iframe>`-tag.

Is a this feature request accepted? If it is I can provide a PR.

**Comment by gmarziou** [comment]
The H2DB console is nto very well known so giving it more visibility by adding in menu could help but I don't understand how having it in an iframe would be more useful than having it in a separate tab or window.

**Comment by andidev** [comment]
New window works as well, did not think of that for some reason. Maybe better since it allows you to keep the current view while searching/editing the database.

**Comment by atomfrede** [comment]
I like it :+1:

**Comment by jdubois** [comment]
The problem is that the link should only work in the "dev" profile -> you could have a look at how I did this for the "dev" banner, but it's quite annoying (and you need to do it for Grunt and Gulp)

**Comment by andidev** [comment]
Agree with the dev profile restriction. I can take a look a look at it.

**Comment by jdubois** [comment]
@andidev please do, it looks like a nice improvement, as it's a cool feature most people don't know about (and be careful of the gulp version as well as the grunt version)

**Comment by andidev** [comment]
Okey I'll watch out for that. I havn't thought of it earles. Have to check my other PR cause I'm starting to think that I have missed the gulp version.

Using an environment variable for the current running environment seems to be a better aproach than the current one where a "search and replace" is done on the ribbon div. In this way it is possible to have as many environment specific functionality as wanted anywhere in the application.

Here is some info about how to do that 
http://mindthecode.com/how-to-use-environment-variables-in-your-angular-application

I'll start implementing it asap

**Comment by andidev** [comment]
Wikipedia says the french translation of the word "database" is "base de données". Is it correct to use "base de données" as the french translation or is it more commonly called "database" in  french? Anyone with some french skills?

**Comment by andidev** [comment]
Two appropriet icons found in glyphicon set, I'm not sure which one to use. Any suggestions by anyone?

![screen shot 2015-01-15 at 14 00 57](https://cloud.githubusercontent.com/assets/571389/5757810/272dd796-9cbf-11e4-9007-4f8adaf06e01.png)

VS

![screen shot 2015-01-15 at 14 01 42](https://cloud.githubusercontent.com/assets/571389/5757811/27318b98-9cbf-11e4-8dba-f41cd1724880.png)

**Comment by gmarziou** [comment]
"Base de données" is correct.

**Comment by jdubois** [comment]
Yes @gmarziou is right :-)
I'd rather have the "hdd" icon, the name looks better

**Comment by andidev** [comment]
Thanks, then it will be so.

**Comment by jdubois** [comment]
@andidev any progress on this? It looks close to be finished!

**Comment by andidev** [comment]
It is almost done. The gulp support is not in place since the gulp plugin I'm using does not support the same features as the grunt version of it. But I will release a forked version of this plugin today. So you can expect a PR today if nothing goes wrong.

**Comment by jdubois** [comment]
This doesn't work with "gulp serve" (and I expect with "grunt serve also), can you check this out?

**Comment by andidev** [comment]
I tested it and it works as intended to me. But maybe it is the indended part that is the bug here =)

The Database menu item in menu is only available when you log in as an Admin user. This is cause it is located in the Administration menu which is hidden for all users but Admin.

Maybe the Administration menu should always be visible with only the Datamase menu item no mather if you have logged in or not or what user you are? (In dev environment only of course)

Is this what you mean?

**Comment by jdubois** [comment]
No, there is an error with Gulp.js: when you click on the database link, from "gulp serve", you have an error page.

- It's working fine with Grunt
- I guess it's the Gulp.js proxy that is failing
