### ISSUE TITLE
Dockerfile missing in 6.0.1

### ISSUE THREAD

**Issue by kentkwan** [jhipster/generator-jhipster#9757]
##### **Overview of the issue**
Upgrade from 6.0.0 to 6.0.1, auto delete Dockerfile in path "src/main/docker".
Generate a new project in 6.0.1, Dockerfile is missing.
##### **JHipster Version(s)**
6.0.1

**Comment by pascalgrimaud** [comment]
Yes, it's normal.
It has been deleted in this PR: https://github.com/jhipster/generator-jhipster/pull/9688

This file is not needed any more as we use jib for building the Docker image.
