### ISSUE TITLE
Template content doesnt change

### ISSUE THREAD

**Issue by sableloki** [jhipster/generator-jhipster#976]
After generating the app i ran `mvn spring-boot:run` to see if it ran (it did) i then proceeded to open up emacs and give the homepage a nice little edit, how ever the content of the template remained the same, i then stopped and re started spring, nothing, i then ran `gulp serve` and nothing happened? is this an issue relating to the stack? or my configuration
- java 8
- gulp
- mongodb
- maven

**Comment by jdubois** [comment]
@amr is the "gulp serve" supposed to work?
Anyway, if you modified your template and stop/restart, it's supposed to work -> it's not even possible that if you change a file, you still see an older version

**Comment by sableloki** [comment]
@jdubois so you're saying when i edit `main.html` in the webapp dir, i should see the content that i put there not the original boilerplate?

**Comment by sableloki** [comment]
could it be related to maven or the build process itself?

**Comment by jdubois** [comment]
I don't understand when you say "original boilerplate". There is just one main.html file, if you edit it, then you'll see the results after a refresh (at least in "dev" profile)... If gulp doesn't work, doing a "refresh" manually should work.

**Comment by sableloki** [comment]
by "boilerplate" i refer to the content of `main.html` upon `yo jhipster` and i have gone as far as restarting both maven and gulp instances

**Comment by amr** [comment]
`gulp serve` should be working fine.

1. Which version if jhipster are you using, the `1.x` or the `master` branch?
2. Which address / port do you use for accessing the application in the browser?

**Comment by jdubois** [comment]
thanks @amr (as I didn't test the "gulp serve" task, shame on me)
@sableloki if you re-started maven, then this is just not possible. There is just one "main.html" file, so you either changed it, or not -> so you have something weird elsewhere
Did you save your file? Did you refresh your browser? Could you clean up your browser cache, or try with another browser, or use your browser's "private mode"?

**Comment by sableloki** [comment]
@amr im using version 2.0.0 as thats what npm installed and everything is default, also @jdubois yes i saved it, yes i tried browser in private mode, and 3 other browsers

**Comment by jdubois** [comment]
Can you explain step by step or do a screencast ?

**Comment by sableloki** [comment]
ok ill record the step by step to recreate

**Comment by sableloki** [comment]
http://youtu.be/C7NVTkboqiA

**Comment by jdubois** [comment]
@sableloki oh, that's easy, OK :-)
The text you change is internationalized (have a look at the "translate" attribute), so you see the translation, not the real text. Delete the attribute, or change something that is not a text (like the color), it will work!

**Comment by sableloki** [comment]
ok cheers
