### ISSUE TITLE
GitLab CI/CD release failure in 6.0.1

### ISSUE THREAD

**Issue by kentkwan** [jhipster/generator-jhipster#9761]
##### **Overview of the issue**
Step of release build failure with command "./mvnw jib:build -Djib.to.image=$IMAGE_TAG -Djib.to.auth.username=gitlab-ci-token  -Djib.to.auth.password=$CI_BUILD_TOKEN"

> [INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:56 min
[INFO] Finished at: 2019-05-18T06:16:44Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:0.9.11:build (default-cli) on project t: Obtaining project build output files failed; make sure you have compiled your project before trying to build the image. (Did you accidentally run "mvn clean jib:build" instead of "mvn clean compile jib:build"?): /builds/kent/test/target/classes -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
ERROR: Job failed: exit code 1

##### **Motivation for or Use Case**
Here is ".gitlab-ci.yml" release segment.
> docker-push:
  stage: release
  variables:
    REGISTRY_URL: <***>
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  dependencies:
    - maven-package
  script:
    - ./mvnw jib:build -Djib.to.image=$IMAGE_TAG -Djib.to.auth.username=gitlab-ci-token  -Djib.to.auth.password=$CI_BUILD_TOKEN

##### **JHipster Version(s)**
6.0.1

**Comment by pascalgrimaud** [comment]
Can you follow our guidelines and provide your `jhipster info` plz ?
Then, where did you try to push your Docker image ? Internal registry or Docker cloud ?

**Comment by kentkwan** [comment]
##### **JHipster Version(s)**

```
t@0.0.0 /Users/Kent/Desktop/t
└── generator-jhipster@6.0.1

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "zh-cn"
    },
    "jhipsterVersion": "6.0.1",
    "applicationType": "monolith",
    "baseName": "t",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "zh-cn",
    "languages": ["zh-cn"]
  }
}

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>


##### **Environment and Tools**

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.20.1 (Apple Git-117)

node: v10.15.3

npm: 6.9.0

yarn: 1.15.2

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

**Comment by kentkwan** [comment]
Push to gitlab internal registry

**Comment by pascalgrimaud** [comment]
Thanks for your information @kentkwan
I'll try to reproduce your issue later

**Comment by kentkwan** [comment]
Execute command "jhipster" to initialize a project.
Execute command "jhipster ci-cd" to add GitLab CI/CD config.
Push the project to internal gitlab host.

**Comment by pascalgrimaud** [comment]
@kentkwan : as the `docker-push` is done in another stage, there is a missing `- target/classes` in the previous stage. It is needed by jib. It should look like:

```yaml
maven-package:
  stage: package
  script:
    - ./mvnw verify -Pprod -DskipTests -Dmaven.repo.local=$MAVEN_USER_HOME
  artifacts:
    paths:
      - target/*.jar
      - target/classes
    expire_in: 1 day
```

You can have a look at my PR too: https://github.com/jhipster/generator-jhipster/pull/9762

**Comment by kentkwan** [comment]
Thanks a lot.
