### ISSUE TITLE
Implement the CII (Core Infrastructure Initiative) Badge

### ISSUE THREAD

**Issue by VinodAnandan** [jhipster/generator-jhipster#9764]
##### **Overview of the feature request**
Implement the CII (Core Infrastructure Initiative) Badge for Jhipster

**What is the CII Badging program?**
CII (Core Infrastructure Initiative) Badge may be achieved by the projects which follow the Best practices criteria for Free/Libre and Open Source Software (FLOSS).

CII has been created by the linux foundation in response to previous security issues in open-source projects (e.g. Heartbleed in openSSL).

The CII Badging is associated to the areas as follows:

       Basics, Change Control, Reporting, Quality, Security & Analysis

e.g: https://bestpractices.coreinfrastructure.org/en/projects/74

**Comment by pmverma** [comment]
In addition to that, LGTM - https://github.com/apps/lgtm-com/ also seems to be great to have. Many great java&JavaScript projects are using it. For eg, Hibernate, maven, activemq and angular.

**Comment by pascalgrimaud** [comment]
The difficulty here is `generator-jhipster` is not a real project but a generator.
But I'd like to have precision about what you have in mind:
- is it for generator-jhipster ?
- is it for generated project ?

Guys : could you give a try to a sample project and put here the link or screenshots of results plz ?
So we can discuss and decide if it deserves to add its to our projects.

**Comment by jdubois** [comment]
I think I did the process to get the badge a couple of years ago, but frankly I didn't use it as I didn't see the point of having yet another badge.

**Comment by pascalgrimaud** [comment]
Agree with you @jdubois 
Any way, we should only focus on SonarCloud, which is used, maybe, by all projects.

Our sample: https://sonarcloud.io/dashboard?id=io.github.jhipster.sample%3Ajhipster-sample-application
- coverage at 81% -> it could be improved
- 61 code smells -> it could be improved too

I'd prefer to focus on our current tools, improve our code with these metrics.
Once it's done, we can go further and add other tools as suggested.

Just my opinion.

**Comment by pmverma** [comment]
I am not sure for sonarcloud but one good point of LGTM is that it provide instant PR analysis.
For eg, you can see at https://github.com/hibernate/hibernate-orm/pull/2883/checks
Since we will not have PR to the sample apps, need to check if it analyze `ejs` or not for the main generator.

But as @pascalgrimaud said, it is better to focus to improve the current one.

**Comment by pascalgrimaud** [comment]
Thanks for your idea, but for now, let's focus on SonarCloud.

Anyway, don't hesitate to test with sample projects and post the result here.

For now, let's close this.
