### ISSUE TITLE
Oauth2, traefik and separate frontend/backend. 404 and documentation error

### ISSUE THREAD

**Issue by antarus** [jhipster/generator-jhipster#9770]
##### **Overview of the issue**
i notice some bug with traefik, oauth 2, and separate frontend/backend 

##### **Reproduce the error**

consider this jdl
<details><summary>jdl separate-frontend</summary>
application {
    config {
        baseName gateway
        applicationType gateway
        languages [fr,en]
        buildTool maven
        packageName dam.gateway
        serverPort 8080
        authenticationType oauth2 
        cacheProvider hazelcast
        devDatabaseType postgresql
        prodDatabaseType postgresql
        //searchEngine elasticsearch
        serviceDiscoveryType consul
        enableSwaggerCodegen false
        testFrameworks [gatling]
        clientPackageManager npm
        nativeLanguage fr
        useSass true
        skipServer true
        }

    entities *
}
application {
    config {
        baseName gatewayback
        applicationType gateway
        languages [fr,en]
        buildTool maven
        packageName dam.gateway
        serverPort 8080
        authenticationType oauth2 
        cacheProvider hazelcast
        devDatabaseType postgresql
        prodDatabaseType postgresql
        //searchEngine elasticsearch
        serviceDiscoveryType consul
        enableSwaggerCodegen true
        testFrameworks [gatling]
        clientPackageManager npm
        nativeLanguage fr
        useSass true
        skipClient true
        }

    entities *
}
application {
    config {
        baseName apis
        applicationType microservice
        skipClient true
        languages [fr,en]
        buildTool maven
        packageName dam.pelican
        serverPort 8081
        authenticationType oauth2 
        cacheProvider hazelcast
        devDatabaseType postgresql
        prodDatabaseType postgresql
        //searchEngine elasticsearch
        serviceDiscoveryType consul
        enableSwaggerCodegen true
        testFrameworks [gatling]
        clientPackageManager npm
        nativeLanguage fr
        }
   entities *
}

deployment {
    deploymentType docker-compose
    appsFolders [gatewayback, apis]
    gatewayType traefik
    monitoring elk 
    consoleOptions [zipkin]
    serviceDiscoveryType consul
    dockerRepositoryName "test"
}

// Domain Ressources
enum RessourceState {
	CREATING, NOT_TESTED, READY
}

entity Resources {
	// creator String required
    dateCreation Instant required
    dateModification Instant 
    dateExpiration LocalDate 
    dateAcquisiiton LocalDate 
    dateEndOfMaintenance LocalDate
    state RessourceState
}

dto * with mapstruct

paginate * with pagination
service all with serviceImpl

microservice * with apis

//filter *

//search * with elasticsearch

</details>

```
jhipster import-jdl project.jdl
```

next 
enabled cors in `application-prod` for `gatewayback` and `apis`
```
cd gatewayback
./mvnw -Pprod verify jib:dockerBuild
cd ../apis
./mvnw -Pprod verify jib:dockerBuild
cd ../docker-compose
# you can disable all service in docker-compose file under traefik except keycloak
docker-compose up -d
cd ../gateway
npm start
```
Connect to `localhost:9000`and connect via keycloak it's ok.

First issue :
 - navigate via the menu to `localhost:9001/admin/gateway`, the page is display correctly. Press `F5` an 404 not found page is display.

Then I want to create a docker image for my gateway. I was inspired by the page https://www.jhipster.tech/separating-front-end-and-api/#-separating-the-front-end-and-the-api-server
stop the command `npm start`
Follow documentation separating-frontend

Create a Dockerfile
```
FROM nginx:1.15-alpine
COPY build/resources/main/static/  /usr/share/nginx/html

```

```
npm run webpack:prod && docker build -t gateway:latest . 
```

add to `docker-compose.yml` file :
```
  gateway:
      image: gateway  
      ports:
          - 8000:80
      volumes:
          - ./gateway/gateway.conf:/etc/nginx/conf.d/default.conf
```

create a file `docker-compose/gateway/gateway.conf` with content :
don't use localhost as it's resolv in container, not your host
```
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    index index.html;

    error_log  /var/log/nginx/error.log;

    root /usr/share/nginx/html;
    location /api {
        proxy_pass $scheme://<Your ip local>/services/gatewayback/api;
    }
    location /management {
        proxy_pass $scheme://<Your ip local>/services/gatewayback/management;
    }
    location /v2 {
       proxy_pass $scheme://<Your ip local>/services/gatewayback/v2;
    }
    location /swagger-ui {
        proxy_pass $scheme://<Your ip local>/services/gatewayback/swagger-ui;
    }
    location /swagger-resources {
        proxy_pass $scheme://<Your ip local>/services/gatewayback/swagger-resources;
    }
    # add for jhipster 6.0.0
    location /oauth2 {
        proxy_pass $scheme://<Your ip local>/services/gatewayback/oauth2;
    }
    location /login {
        proxy_pass $scheme://<Your ip local>/services/gatewayback/login;
    }
    location / {
        try_files $uri $uri/ /index.html;
    }
}
```
access to `http:\\<your ip>:8000 `

in the browser log,  there is an error  on `http://<your ip>/oauth2/authorization/oidc`
```
http://<your ip>/oauth2/authorization/oidc
Request Method: GET
Status Code: 404 Not Found (from disk cache)
Referrer Policy: no-referrer-when-downgrade
```

click connect.
you have a 404 page not found gatewayback (redirect on http://< your ip >:8000/oauth2/authorization/oidc)

if i use this file instead 

```
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    index index.html;

    error_log  /var/log/nginx/error.log;

    root /usr/share/nginx/html;

    location /api {
        proxy_pass $scheme://< your ip >:8080/api;
    }
    location /management {
        proxy_pass $scheme://< your ip >:8080/management;
    }
    location /v2 {
       proxy_pass $scheme://< your ip >:8080/v2;
    }
    location /swagger-ui {
        proxy_pass $scheme://< your ip >:8080/swagger-ui;
    }
    location /swagger-resources {
        proxy_pass $scheme://< your ip >:8080/swagger-resources;
    }
    location /oauth2 {
        proxy_pass $scheme://< your ip >:8080/oauth2;
    }
    location /login {
        proxy_pass $scheme://< your ip >:8080/login;
    }
    location / {
        try_files $uri $uri/ /index.html;
    }
}
```
if got a 302 on oidc but error on `auth?response_type...`

http://keycloak/auth/realms/jhispter/protocol/openid-connect/auth?response_type=code&client_id=web_app&scope=openid%20address%20email%20offline_access%20phone%20profile%20roles%20web-origins&state=S56pcdDlNNyfizAIYkkteOKHtn8OAkVLbvKxabDqjT0%3D&redirect_uri=http://<your ip>:8080/login/oauth2/code/oidc

Ideally with an image docker nginx + consul, the gateway should register in consul, and traefik manage the load balancing between the different instances ...
On the 5.8 with some modification I managed to manage the load balancing between the different instances of the gateway on traefik but with the changes brought to 6.0, I can't find ..

Summary Issues :
 - [ ] navigate via the menu to `localhost:9001/admin/gateway`, the page is display correctly. Press `F5` an 404 not found page is display.
- [ ] The separation of frontend and backend via traefik and oauth doesn't work
##### **Related issues**

maybe https://github.com/jhipster/generator-jhipster/issues/9769

##### **JHipster Version(s)**

<details><summary>jhipster version</summary>

##### **JHipster Version(s)**

```
gatewayback@0.0.0 /home/cedric/dev/dam/test/gatewayback
└── generator-jhipster@6.0.1 

```

##### **Environment and Tools**

openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment (build 11.0.2+9-Ubuntu-3ubuntu118.04.3)
OpenJDK 64-Bit Server VM (build 11.0.2+9-Ubuntu-3ubuntu118.04.3, mixed mode, sharing)

git version 2.17.1

node: v10.13.0

npm: 6.4.1

Docker version 18.09.6, build 481bc77

docker-compose version 1.23.2, build 1110ad01

INFO! Congratulations, JHipster execution is complete!

</details>

##### **Browsers and Operating System**
linux ubuntu 18.04
chromium 73

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@antarus : maybe we can regroup with the other ticket #9769 ? Or, it's a different issue ?

**Comment by ruddell** [comment]
I think the first issue is solved by [configuring the base href](https://www.jhipster.tech/traefik/#configure-your-base-href), did you do that step?

**Comment by antarus** [comment]
In this configuration the gateway is not registered in consul and therefore not served via traefik...
In doubt, I tested to add the base href  `/services/gatewayback/` without success

**Comment by antarus** [comment]
I think, you can add tag oidc, the configuration of traefik seems work with jwt.

**Comment by Hawkurane** [comment]
Hello, I've tried reproducing your error and I can't seem to access to localhost:9001. None of my dockers are displaying to port 9001.

PS:

Glorious reformatted jdl for copy pasta for people trying to reproduce
```
application { 
    config { 
        baseName gateway 
        applicationType gateway 
        languages [fr,en] 
        buildTool maven 
        packageName dam.gateway 
        serverPort 8080 
        authenticationType oauth2 
        cacheProvider hazelcast 
        devDatabaseType postgresql 
        prodDatabaseType postgresql 
        //searchEngine elasticsearch 
        serviceDiscoveryType consul 
        enableSwaggerCodegen false 
        testFrameworks [gatling] 
        clientPackageManager npm 
        nativeLanguage fr 
        useSass true 
        skipServer true 
    }
    entities *
}
application {
    config {
        baseName gatewayback
        applicationType gateway
        languages [fr,en]
        buildTool maven
        packageName dam.gateway
        serverPort 8080
        authenticationType oauth2
        cacheProvider hazelcast
        devDatabaseType postgresql
        prodDatabaseType postgresql
        //searchEngine elasticsearch
        serviceDiscoveryType consul
        enableSwaggerCodegen true
        testFrameworks [gatling]
        clientPackageManager npm
        nativeLanguage fr
        useSass true
        skipClient true
    }

    entities *

}
application {
    config {
        baseName apis
        applicationType microservice
        skipClient true
        languages [fr,en]
        buildTool maven
        packageName dam.pelican
        serverPort 8081
        authenticationType oauth2
        cacheProvider hazelcast
        devDatabaseType postgresql
        prodDatabaseType postgresql
        //searchEngine elasticsearch
        serviceDiscoveryType consul
        enableSwaggerCodegen true
        testFrameworks [gatling]
        clientPackageManager npm
        nativeLanguage fr
    }
    entities *
}

deployment {
    deploymentType docker-compose
    appsFolders [gatewayback, apis]
    gatewayType traefik
    monitoring elk
    consoleOptions [zipkin]
    serviceDiscoveryType consul
    dockerRepositoryName "test"
}

// Domain Ressources
enum RessourceState {
    CREATING, NOT_TESTED, READY
}

entity Resources {
    // creator String required
    dateCreation Instant required
    dateModification Instant
    dateExpiration LocalDate
    dateAcquisiiton LocalDate
    dateEndOfMaintenance LocalDate
    state RessourceState
}

dto * with mapstruct

paginate * with pagination
service all with serviceImpl

microservice * with apis

//filter *

//search * with elasticsearch
```

**Comment by antarus** [comment]
access to localhost:9001 is done with `npm start`

**Comment by Hawkurane** [comment]
Ah for me the npm start port is to 9000 that explain things !
I am quite unfamilliar with OAUTH2.0 and Keycloak and I'm trying to reproduce your error, could you elaborate a bit more on how you manage to log in via keycloak ? (since the log in button for me leads to a 404)

**Comment by antarus** [comment]
i found a solution, base on https://github.com/jhipster/generator-jhipster/pull/9970. 
i need to simplify it. i work on it ;) 
you can assign to me @pascalgrimaud
