### ISSUE TITLE
VERSION 6.0.1: CreateProcess error=206, The filename or extension is too long

### ISSUE THREAD

**Issue by elpioramirez** [jhipster/generator-jhipster#9771]
##### **Overview of the issue**

When running mvnw to start my UAA Server an error for create process is generated. This error is related to JAVA_HOME path. I just updated to version 6.0.1, then I had to downgrade to version 5.8.2 and everything was working fine. 

##### **Motivation for or Use Case**

This is a bug since I'm not able to start the microservice for UAA Server 

##### **Reproduce the error**

Pre-requisites
Install version 6.0.1
JDK 8 u211
Steps:
1. jhipster
2. microservice uaa server
3. port 9191
4. package name: com.mycompany.app
5. Jhipster Registry
6. SQL
7. MariaDB
8. MariaDB
9. No Cache Abstraction
10. Maven
11. Elastic Search / Kafta
12. i18n: Y
13. English
14. Spanish
15. (Enter)
16. N

After everything is installed then run mvnw to test and this error appears.

##### **Related issues**

Yes, as closed. The funny thing is that this was not happening in version 5.8.2 (I had to downgrade and now everything is working fine)

##### **Suggest a Fix**

I couldn't find any, I tried moving my JDK installation to C:\jdk and changed environmental variable since it was suggesting filename of JAVA_HOME was to long but error persisted.

##### **JHipster Version(s)**

6.0.1

##### **JHipster configuration**

Not applicable since I had to downgrade to test if it was working on previous versions

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Not applicable since I had to downgrade to test if it was working on previous versions

##### **Browsers and Operating System**

Windows 10, not opening any browser just console

-   [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by BhawaniSingh** [comment]
This is basically a windows issues, not anything specific to jhipster.
It occurs because windows command line is restricted to 32768 chars.
You can bypass this issue by moving the project to root of the drive some thing like d:\awesome-project
Here is the Microsoft docs explaining
https://docs.microsoft.com/en-us/windows/desktop/api/processthreadsapi/nf-processthreadsapi-createprocessa

**Comment by pascalgrimaud** [comment]
Could you try to have a look to the previous link ?
As said, it's related to Windows, not to JHipster. You could try our [DevBox](https://github.com/jhipster/jhipster-devbox) too, I'm pretty sure, you won't have the issue.

Feel free to bring precisions or additional information to this ticket.

**Comment by elpioramirez** [comment]
Actually I always create my projects under c:/my-app to avoid long names, the only way I was able to run the app was downgrading Jhipster to version 5.

**Comment by gmarziou** [comment]
Could it be due to location of your maven local repository?
