### ISSUE TITLE
Consider replacing Glyphicons with Font Awesome

### ISSUE THREAD

**Issue by andidev** [jhipster/generator-jhipster#978]
Font Awesome may be a better alternative than Glyphicons since it contains more icons (479 vs 200). It is also a more open project.

If not replacing maybe include them both? They are very simiiar. Not sure if two libraries are apprecieted by the users though.

Reference
http://fortawesome.github.io/Font-Awesome/

**Comment by atomfrede** [comment]
:+1: for Font Awesome! In particular coloring icons is much easier with Font Awesome.

**Comment by gmarziou** [comment]
I like both but I'm concerned by download size.
Is there a way with grunt to optimize fonts to only the icons used?

**Comment by gzsombor** [comment]
You dont need to download anything, you can rely on cdns, just add this to your header:
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

**Comment by gmarziou** [comment]
I am concerned by download size from browser standpoint, CDN would not help.
Why download full icon set, if you use only 1O of them?
This is a concern for mobile browsers mainly with lower network bandwidth.

**Comment by andidev** [comment]
Here are the differences in size:

Glyphicons
![screen shot 2015-01-13 at 16 02 30](https://cloud.githubusercontent.com/assets/571389/5727781/e026f36e-9b65-11e4-8906-deacd2bb8865.png)

Font Awesome
![screen shot 2015-01-13 at 16 02 50](https://cloud.githubusercontent.com/assets/571389/5727782/e027a156-9b65-11e4-836c-c4ed72d2c2e0.png)

Agree, quite a differense

**Comment by andidev** [comment]
IOS 5 and Android 4.4 supports .woff. Otherwise svg seems to be used
[source](http://stackoverflow.com/questions/11002820/why-should-we-include-ttf-eot-woff-svg-in-a-font-face?answertab=active#tab-top)

The svg files are quite big unluckily. But it looks like the fontawesome-webfint.svg can be reduced by compression to 74kB while the glyphicons-halflings-regular.svg can be redusced to 17kB. 

I just checked and it seems that jhipster apps does not compress the fonts. Maybe something to look into?

**Comment by gmarziou** [comment]
Interesting, I think the font compression should have its own issue.

I found [fontello](https://github.com/fontello/fontello) which lets you select only some icons and generate a font file. This could be automated (maybe in Grunt) by searching icon CSS class names and calling fontello, maybe this already exists.

**Comment by andidev** [comment]
I thought about that too actually. Though I see one problem with that, what if the user is creating the css class dynamically in javascript? Then the search won't find the font class used. This scenario maybe could be solved by allowing to add fonts by configuration as well. Not sure if this is a bit overkill though.

There is as it looks already a grunt task for downloading icons from fontelli. The way it works is that you have to provide it a config.json file containing referenses to the fonts to use.

Here is an example containing three Font Awesome fonts
```json
{
  "name": "",
  "css_prefix_text": "icon-",
  "css_use_suffix": false,
  "hinting": true,
  "units_per_em": 1000,
  "ascent": 850,
  "glyphs": [
    {
      "uid": "cfaa8fbbdcc7bb8d636cb974aad1f9b9",
      "css": "glass",
      "code": 59392,
      "src": "fontawesome"
    },
    {
      "uid": "9ea0a737ccc45d6c510dcbae56058849",
      "css": "music",
      "code": 59393,
      "src": "fontawesome"
    },
    {
      "uid": "9dd9e835aebe1060ba7190ad2b2ed951",
      "css": "search",
      "code": 59394,
      "src": "fontawesome"
    }
  ]
}
```

**Comment by jdubois** [comment]
We use glyphicon as it's the default icon set coming with AngularJS : as always, we stick with the default, standard stuff, unless we have a very good reason to change.
I know Font Awesome is great (that's what we use for the JHipster website), but I don't think there is a need to provide it by default -> of course, if you want to use it, it's quite easy to install, so there isn't much added value in providing it by default.
We should rather focus on stuff like #969 , to make it easy to add new JS/CSS/images if needed
