### ISSUE TITLE
Gateway fails to start using 6.0.1 or master - hibernatePropertiesCustomizer/jCacheCacheManager

### ISSUE THREAD

**Issue by jsm174** [jhipster/generator-jhipster#9787]
##### **Overview of the issue**

When creating a new gateway and microservice from JDL using 6.0.1 or master, the gateway fails to start with the following:

```
10:25:33.962 [DEBUG] [TestEventLogger]     2019-05-23 10:25:33.961 ERROR 77121 --- [    Test worker] o.s.b.d.LoggingFailureAnalysisReporter   :
10:25:33.962 [DEBUG] [TestEventLogger]
10:25:33.962 [DEBUG] [TestEventLogger]     ***************************
10:25:33.963 [DEBUG] [TestEventLogger]     APPLICATION FAILED TO START
10:25:33.963 [DEBUG] [TestEventLogger]     ***************************
10:25:33.963 [DEBUG] [TestEventLogger]
10:25:33.963 [DEBUG] [TestEventLogger]     Description:
10:25:33.963 [DEBUG] [TestEventLogger]
10:25:33.963 [DEBUG] [TestEventLogger]     Parameter 0 of method hibernatePropertiesCustomizer in com.example.gateway.config.CacheConfiguration required a bean of type 'javax.cache.CacheManager' that could not be found.
10:25:33.963 [DEBUG] [TestEventLogger]
10:25:33.963 [DEBUG] [TestEventLogger]     The following candidates were found but could not be injected:
10:25:33.964 [DEBUG] [TestEventLogger]          - Bean method 'jCacheCacheManager' in 'JCacheCacheConfiguration' not loaded because AnyNestedCondition 0 matched 2 did not; NestedCondition on JCacheCacheConfiguration.JCacheAvailableCondition.CustomJCacheCacheManager @ConditionalOnSingleCandidate (types: javax.cache.CacheManager; SearchStrategy: all) did not find any beans; NestedCondition on JCacheCacheConfiguration.JCacheAvailableCondition.JCacheProvider JCache found multiple JSR-107 providers
10:25:33.964 [DEBUG] [TestEventLogger]
10:25:33.964 [DEBUG] [TestEventLogger]
10:25:33.964 [DEBUG] [TestEventLogger]     Action:
10:25:33.964 [DEBUG] [TestEventLogger]
10:25:33.964 [DEBUG] [TestEventLogger]     Consider revisiting the entries above or defining a bean of type 'javax.cache.CacheManager' in your configuration.
```

##### **Reproduce the error**

This is the  JDL I used (apps.jh):

```
application {
   config {
      baseName gateway,
      applicationType gateway,
      authenticationType oauth2,
      packageName com.example.gateway,
      prodDatabaseType mariadb,
      languages [en],
      buildTool gradle
   }
   entities *
}

application {
   config {
      baseName sampleservice,
      applicationType microservice,
      packageName com.example.sampleservice,
      authenticationType oauth2,
      prodDatabaseType mariadb,
      buildTool gradle
      skipClient true
   }
   entities Book
}

entity Book {
   title String
}

paginate * with pagination

microservice Book with sampleservice
```

Execute the following:

```
jhipster import-jdl apps.jh
cd gateway
./gradlew build
```

##### **JHipster Version(s)**

```
gateway@0.0.0 /Users/jmillard/jason/gateway
└── generator-jhipster@6.0.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["en"],
    "messageBroker": false,
    "nativeLanguage": "en",
    "packageName": "com.example.gateway",
    "packageFolder": "com/example/gateway",
    "prodDatabaseType": "mariadb",
    "searchEngine": false,
    "serviceDiscoveryType": "eureka",
    "skipClient": false,
    "skipServer": false,
    "testFrameworks": [],
    "websocket": false,
    "baseName": "gateway",
    "applicationType": "gateway",
    "authenticationType": "oauth2",
    "buildTool": "gradle",
    "jhipsterVersion": "6.0.1",
    "skipUserManagement": true,
    "clientPackageManager": "npm",
    "cacheProvider": "ehcache",
    "serverPort": "8080",
    "clientFramework": "angularX",
    "useSass": true,
    "clientTheme": "none",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": []
  },
  "entities": ["Book"]
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Book {
  title String
}
paginate Book with pagination
microservice Book with sampleservice

</pre>
</details>

##### **Environment and Tools**

openjdk version "12" 2019-03-19
OpenJDK Runtime Environment (build 12+33)
OpenJDK 64-Bit Server VM (build 12+33, mixed mode, sharing)

git version 2.20.1 (Apple Git-117)

node: v10.15.3

npm: 6.4.1

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by devWhyqueue** [comment]
Just had the same issue. You most likely chose different cache providers for your microservice and your gateway.
In your .yo-rc.json for the gateway you defined:
`"cacheProvider": "ehcache"`
Please make sure you did the same in all microservices.

**Comment by pascalgrimaud** [comment]
I gave a fast try, and indeed, it failed only with Gradle. If I try with Maven, there is no problem.
So it comes probably from a difference between dependencies.

**Comment by jsm174** [comment]
Thanks @devWhyqueue. From the JDL I posted I never set any cache providers. I will look to see what the microservice was defaulted too.

**Comment by devWhyqueue** [comment]
Just looked it up in the docs.
As stated in the available application options table [(JDL/Application Options)](https://www.jhipster.tech/jdl/#application_options) the default cache provider property sets its default like this:
**Option Name:** _`cacheProvider`_
**Default Value:** `ehcache or hazelcast`
**Possible Values:** `ehcache, hazelcast, infinispan, no`
**Comment:** `ehcache for monoliths and gateways, hazelcast otherwise`

**Comment by jsm174** [comment]
@pascalgrimaud  So I tried with maven, and it did work. 

In the most unscientific comparison ever :) 

Maven:

```
./mvnw spring-boot:run -Dspring-boot.run.jvmArguments="-Xlog:class+load=info:classloaded.txt"
grep \.jar classloaded.txt | grep -o '[^\/]*$' | sort -u > maven_jars.txt
```

Gradle:

```
Update build.gradle with:

bootRun {
   jvmArgs = ["-Xlog:class+load=info:classloaded.txt"]
}

./gradlew bootRun
grep \.jar classloaded.txt | grep -o '[^\/]*$' | sort -u > gradle_jars.txt
```

TBH, not much is jumping out. It seems like there are different versions of jaxb, jackson-annotations.

[maven_jars.txt](https://github.com/jhipster/generator-jhipster/files/3228971/maven_jars.txt)
[gradle_jars.txt](https://github.com/jhipster/generator-jhipster/files/3228968/gradle_jars.txt)
 
<img width="903" alt="gradle-vs-maven-1" src="https://user-images.githubusercontent.com/1197137/58499897-09e65400-814f-11e9-945a-06e9d304b5e1.png">

<img width="982" alt="gradle-vs-maven-2" src="https://user-images.githubusercontent.com/1197137/58499905-0e127180-814f-11e9-9b62-f4ff0a3c5f9f.png">

**Comment by pascalgrimaud** [comment]
@jsm174 : thanks for investigating. I don't know Gradle enough to try to find a fix, so if you find one, go ahead !

**Comment by jsm174** [comment]
So I decided to comment out hazelcast entries from `build.gradle` since, its not listed in the maven version. The gateway did start successfully.

`build.gradle.ejs` specifically adds hazelcast when it's a gateway:

https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/build.gradle.ejs#L296

As @devWhyqueue said above, the JDL document says "ehcache for monoliths and gateways, hazelcast otherwise"

Looking at`pom.xml.ejs`:

https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/pom.xml.ejs#L222

It looks like the logic to add these jars between gradle and maven is different:

<img width="712" alt="gradle-maven" src="https://user-images.githubusercontent.com/1197137/58505585-46b84800-815b-11e9-9a82-77e94a9a3f93.png">

**Comment by pascalgrimaud** [comment]
closed by https://github.com/jhipster/generator-jhipster/pull/9811
