### ISSUE TITLE
Question : is GZipServletOutputStream usefull ?

### ISSUE THREAD

**Issue by mpages** [jhipster/generator-jhipster#979]
is GZipServletOutputStream usefull ?
will i was doing a light optim on GZipServletFilter by removing a stream to array and i come to the conclusion that GZipServletOutputStream can be replace by java.util.zip.GZIPOutputStream.

**Comment by jmirc** [comment]
It could be tested only with prod profile. If it works, can you do a PR? Thanks

**Comment by jdubois** [comment]
It's useful because you need to have a ServletOutputStream in the GZipServletResponseWrapper, it's forced by the servlet API

**Comment by mpages** [comment]
you can do without it using java.util.zip.GZIPOutputStream
since it doesn't provide huge diff in perf... i don't think it's usefull to change it
