### ISSUE TITLE
Support UUID field type in entity for SQL databases

### ISSUE THREAD

**Issue by murdos** [jhipster/generator-jhipster#9793]
##### **Overview of the feature request**

Add support for the java.util.UUID type as a field of an entity for SQL Databases.

##### **Motivation for or Use Case**

This feature is already available for Cassandra.
Also it's far more accurate to declare your field as UUID in java that as String.

##### **Related issues or PR**

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by murdos** [comment]
- [ ] jhipster-core : https://github.com/jhipster/jhipster-core/pull/331
- [ ] generator-jhipster : https://github.com/jhipster/generator-jhipster/pull/9794
- [ ] documentation

**Comment by MathieuAA** [comment]
Regarding JCore and the doc, this feature request is good to go.

**Comment by jdubois** [comment]
This has already been widely discussed and there are many (only?) downsides of using UUIDs for PK. I'm fine with it, but we need to document this thoroughly.

**Comment by pascalgrimaud** [comment]
@jdubois : if I understand well, it is as a new type, not as PK

**Comment by mraible** [comment]
As you might know, I’m very interested in this feature since I need it in my 21-Points Health app that’s using PostreSQL on Heroku. I’ve migrated to UUID to solve duplicate key issues in the following PR:

https://github.com/mraible/21-points/pull/58

I’m not sure if we need it, but based on my experience, it’d be pretty solid if we offered an upgrade to UUID. For example:

jhipster upgrade —uuid

**Comment by jdubois** [comment]
Oh sorry!

- if it's not a PK -> no problem at all
- for PKs, that could be an option 

And @mraible isn't your issue linked to audit logs? Maybe we should remove them, I'm not sure we should have those by default.

We could also have a pattern where we use Longs as PKs, but UUIDs as "exposed keys", for example for REST endpoints.

**Comment by mraible** [comment]
@jdubois Yes, it started with audit logs. However, I've noticed it happens for primary key generation of all my entities. The app started with JHipster 2.x and I've migrated it to new versions over the years. I'm not sure it's a JHipster issue, but it definitely has been a JHipster + Heroku issue for me.

**Comment by murdos** [comment]
To make things clear: this feature request is just for field type, not for PK.

**Comment by pascalgrimaud** [comment]
Closed by https://github.com/jhipster/generator-jhipster/pull/9794
