### ISSUE TITLE
Prometheus configuration for K8S needs a fix

### ISSUE THREAD

**Issue by vinicius91carvalho** [jhipster/generator-jhipster#9795]
##### **Overview of the issue**

Prometheus is causing errors when I try to apply your configuration in the EKS cluster on AWS.

##### **Motivation for or Use Case**

When I apply the monitoring directory generated by the `jhipster kubernetes` sub generator, I can not to running up Prometheus, because I receive the below message:

Unhandled error received. Exiting..." err="creating CRDs failed: waiting for PrometheusRule crd failed: timed out waiting for Custom Resource: failed to list CRD: unknown (get prometheusrules.monitoring.coreos.com)"

##### **Reproduce the error**

1) kubectl -f apply registry
2) kubectl -f apply gateway
3) kubectl -f apply monitoring
4) The pod of the prometheus CR not stay in running state

##### **Suggest a Fix**

I found the solution here: [Prometheus operator ERROR status](https://github.com/coreos/prometheus-operator/issues/1658)

The solution is added the line `- prometheusrules` on this section below:

```
- apiGroups:
  - monitoring.coreos.com
  resources:
  - alertmanagers
  - prometheuses
  - servicemonitors
  - prometheusrules
```

##### **JHipster Version(s)**

6.0.1

##### **JHipster Version(s)**

```
/Users/viniciuscarvalho/Projects/sbt-platform/devops/kubernetes
└── (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "appsFolders": [
      "gateway"
    ],
    "directoryPath": "../../",
    "serviceDiscoveryType": "eureka",
    "jwtSecretKey": "***",
    "dockerRepositoryName": "***",
    "dockerPushCommand": "docker push",
    "kubernetesNamespace": "default",
    "kubernetesServiceType": "LoadBalancer",
    "ingressDomain": "",
    "monitoring": "prometheus",
    "istio": true
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

git version 2.21.0

node: v10.15.3

npm: 6.9.0

yeoman: 2.0.0

yarn: 1.15.2

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

##### **Browsers and Operating System**

MacOS Mojave 10.14.5
Chrome Versão 74.0.3729.169 (Version official) 64 bits

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@vinicius91carvalho : thanks for reporting this. Indeed, this part is not tested in our CI so you're probably right.
Would you like to contribute and PR the fix plz ?

**Comment by vinicius91carvalho** [comment]
@pascalgrimaud OK! I will open it later. Thanks :)
