### ISSUE TITLE
Missed configuration in the Prometheus K8S recipe

### ISSUE THREAD

**Issue by vinicius91carvalho** [jhipster/generator-jhipster#9796]
##### **Overview of the issue**

I am receiving the messages below when I up the Prometheus with K8S in the EKS on AWS.

```
E0504 06:11:53.688249       1 reflector.go:322] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:300: Failed to watch *v1.Namespace: unknown (get namespaces)
E0504 06:11:54.691215       1 reflector.go:322] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:300: Failed to watch *v1.Namespace: unknown (get namespaces)
E0504 06:11:55.695893       1 reflector.go:322] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:300: Failed to watch *v1.Namespace: unknown (get namespaces)
E0504 06:11:56.698611       1 reflector.go:322] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:300: Failed to watch *v1.Namespace: unknown (get namespaces)
```

##### **Motivation for or Use Case**

It needs a simple fix. A config was missing.

##### **Reproduce the error**

In a new cluster generated on EKS, run the monitoring directory generated by the jhipster kubernetes sub generator:

1) kubectl apply -f monitoring 

##### **Suggest a Fix**

I found a solution here: [Failed to watch *v1.Namespace: unknown (get namespaces)](https://github.com/coreos/prometheus-operator/issues/1324)

It needs a 'watch' operator on the config below:

```
- apiGroups: [""]
  resources:
  - namespaces
  verbs: ["list","watch"]
```
##### **JHipster Version(s)**

6.0.1

##### **JHipster Version(s)**

```
/Users/viniciuscarvalho/Projects/sbt-platform/devops/kubernetes
└── (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "appsFolders": [
      "gateway"
    ],
    "directoryPath": "../../",
    "serviceDiscoveryType": "eureka",
    "jwtSecretKey": "***",
    "dockerRepositoryName": "***",
    "dockerPushCommand": "docker push",
    "kubernetesNamespace": "default",
    "kubernetesServiceType": "LoadBalancer",
    "ingressDomain": "",
    "monitoring": "prometheus",
    "istio": true
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

git version 2.21.0

node: v10.15.3

npm: 6.9.0

yeoman: 2.0.0

yarn: 1.15.2

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

##### **Browsers and Operating System**

MacOS Mojave 10.14.5
Chrome Version 74.0.3729.169 (Version official) 64 bits

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@vinicius91carvalho : same here, don't hesitate to PR the fix

**Comment by vinicius91carvalho** [comment]
@pascalgrimaud Ok! I will open it later. Thanks :)
