### ISSUE TITLE
Separate loading of fake data from definition of data structure

### ISSUE THREAD

**Issue by ChouSsu** [jhipster/generator-jhipster#9804]
##### **Overview of the feature request**

Separate loading of fake/test data from definition of data structure in liquibase changesets.

##### **Motivation for or Use Case**

Currently loading of generated fake/test data is placed within corresponding entity files - even before jhipster needle ```jhipster-needle-liquibase-add-changeset``` which prevents other/external modules (e.g. generator-jhipster-entity-audit) to introduce additional fields.

##### **Suggest a Fix**
**Approach 1**: introduction of additional needles e.g. ```jhipster-needle-liquibase-add-changeset-dmo``` for data manipulation operations (DMO) and ```jhipster-needle-liquibase-add-changeset-ddo``` for data definition operations (DDO). DMO needle is required to be placed at the end of the entity changeset file.

**Approach 2**: full separation of DMO and DDO, e.g. have a separate ```import_data.xml``` residing within ```data``` sub-folder which lists the loadData elements for the various entities and reference that file in the master.xml.

2nd approach preferred for cleaner separation.

##### **Related issues or PR**
Could not find a directly related PR or issue. Closest ones I could find:
* jhipster/generator-jhipster#9103
* jhipster/generator-jhipster#9579
* jhipster/generator-jhipster#9661

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Yes I agree with you that approach 2 seems better, anyway the less needles the better as they clutter the end user's code.

I'm adding a bug bounty here.
