### ISSUE TITLE
Use compatible liquibase-hibernate5 and liquibase versions

### ISSUE THREAD

**Issue by clakech** [jhipster/generator-jhipster#9807]
##### **Overview of the issue**

liquibase-hibernate5 version 3.6 (used by jhipster 6.0.1) does not support liquibase 3.6 (used by jhipster 6.0.1)

See the release note: https://github.com/liquibase/liquibase-hibernate/releases/tag/liquibase-hibernate5-3.7 
```
Support for Liquibase 3.6.x
Support for Bean validation annotation
Better handling of indexes and constraints
Better handling of physicalNamingStrategy
Support for using sequence start values
```

This leads to an error using liquibase:diff

```
[ERROR] Failed to execute goal org.liquibase:liquibase-maven-plugin:3.6.3:diff (default-cli) on project api: Error setting up or running Liquibase: org.hibernate.boot.MappingException: Unable to perform unmarshalling at line number 3 and column 40. Message: élément inattendu (URI : "http://www.hibernate.org/xsd/orm/hbm", local : "hibernate-mapping"). Les éléments attendus sont <{}hibernate-mapping> : origin(envers): UnmarshalException -> [Help 1]
```

##### **Motivation for or Use Case**

We should use compatible versions between dependencies

##### **Suggest a Fix**

Update to liquibase-hibernate5 version 3.7

##### **JHipster Version(s)**

6.0.1

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

Sorry for the quick dirty issue, I may be able to provide more context later

**Comment by pmverma** [comment]
Last time we had this same problem and was fixed in https://github.com/jhipster/generator-jhipster/pull/9695

Please provide details steps to reproduce.

Updating to liquibase-hibernate5 version 3.7 didn't help, see in the https://github.com/jhipster/generator-jhipster/pull/9740#issuecomment-492768001

Did your code successfully run with your suggested fix?

**Comment by clakech** [comment]
W00t trying to reproduce this in a brand new project from scratch and bOOm, found an issue in my project : bad merge on last jhi update and my pom.xml was not following jhi ! 

A quick patch solve this issue (add this dependency into liquibase-maven-plugin <artifactId>hibernate-core</artifactId><version>${hibernate-core.version}</version>)
