### ISSUE TITLE
Pagination problem when filtering

### ISSUE THREAD

**Issue by JaviManteiga** [jhipster/generator-jhipster#9808]
##### **Overview of the issue**

Using JHipster with Angular and pagination, if you access a entity list with more than one page, go to page 2 and use a filter with few results that only need one page to show,, a page change to page one is not performed.

##### **Motivation for or Use Case**

This behaviour is not present in the audit list (which is also a paginated list) so the other tables should be consistent with it.

##### **Reproduce the error**

- Access a list with more than one page
- Go to page 2
- Filter results leaving few results (<pageSize)
- In the audit list a page change to page 1 is done
- In any other paginated entity list stays in page 2

##### **Suggest a Fix**

I don't know exactly the reason but is related with the ngif of the ouside div (entity-management.component.html.ejs):

`    <div *ngIf="<%=entityInstancePlural %> && <%=entityInstancePlural %>.length">
        <div class="row justify-content-center">
            <jhi-item-count [page]="page" [total]="totalItems" [maxSize]="5" [itemsPerPage]="itemsPerPage"></jhi-item-count>
        </div>
        <div class="row justify-content-center">
            <ngb-pagination [collectionSize]="totalItems" [(page)]="page" [pageSize]="itemsPerPage" [maxSize]="5" [rotate]="true" [boundaryLinks]="true" (pageChange)="loadPage(page)"></ngb-pagination>
        </div>
    </div>
    <%_ } _%>`

My guess is that the ngIf prevents the inner tags to be in the DOM when the event should be raised and because of that, when it evaluates to true is too late and the event is never thrown. In fact, if I change the ngIf with a hidden, everything works.

##### **JHipster Version(s)**

I'm using JHipster 5.8.2 but the code affected hasn't changed in JHipster 6

##### **JHipster Version(s)**

```
managementApp@0.0.0 T:\workspace\app
`-- generator-jhipster@5.8.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.app.management",
      "nativeLanguage": "es"
    },
    "jhipsterVersion": "5.8.2",
    "applicationType": "monolith",
    "baseName": "management",
    "packageName": "com.app.management",
    "packageFolder": "com/app/management",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "es",
    "languages": [
      "es",
      "en"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Idioma {
  codigo String required maxlength(8),
  codigoISO String required maxlength(2)
}
dto Idioma with mapstruct
paginate Idioma with pagination
service Idioma with serviceClass

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) Client VM (build 25.201-b09, mixed mode, sharing)

node: v8.12.0

npm: 6.4.1

yeoman: 2.0.5

**Comment by ruddell** [comment]
Can you please supply your `jhipster info` output so we can easily reproduce?

**Comment by JaviManteiga** [comment]
> Can you please supply your `jhipster info` output so we can easily reproduce?

I've updated my question with the information. Thanks in advance

**Comment by clement26695** [comment]
I can confirm the issue. Replacing the ngIf condition with a hidden looks good to me. Do you want to do a PR @JaviManteiga ?

For the others, if you want to reproduce, you can check https://github.com/clement26695/9808-ng.

https://github.com/clement26695/9808-ng/commit/1ec032bdbb0e40387a88611368aecdddcffc4cd3 works, when https://github.com/clement26695/9808-ng/commit/78efe31067a81af7792b14d12ede046f61ce92f9 does not.

**Comment by clement26695** [comment]
Note that the issue is present in the vue-js bluebrint.

It is also present in react, as we built our own component, and didn't took care of this issue.

**Comment by JaviManteiga** [comment]
@clement26695 I made the Angular client changes in https://github.com/JaviManteiga/generator-jhipster/commit/bc3fbfcec2f3e82e81a0612be51000aaf952ac52 but since React and VueJS are also affected I didn't create the PR (feel free to use my commit).

Testing your example, I think in the hidden input the array check is still needed:

`<div [hidden]="!idiomas || idiomas.length === 0">`

Otherwise, while the data is retrieved from the backend the pagination component is visible.
