### ISSUE TITLE
Adding two relationship to the same entity is forbidden by the generator

### ISSUE THREAD

**Issue by maxleiko** [jhipster/generator-jhipster#981]
When you want to generate a new entity that will have a relationship with another one, you can use the generator for the first relation, but if you want to add another field to your entity that includes a relationship with the same entity as the previous one, the generator will tell you that:

```
>> Your relationship name cannot contain special characters or use an already existing field name
```

Even though you do not plan to allow multiple relations with the same entity from a generator POV, we should be able to say after that error message that we are done with this entity. Because, for now, if you see this error message you cannot do anything else but add another relation to your entity or restart the whole generation process again.

Maybe you should ask for the relation name.  

If you have the tables **User** and **OtherTable**, and you want to add the relations `owner` (ManyToOne) and `users` (ManyToMany) to **OtherTable** you can't.  
Plus, when you first try to generate the `owner` relation, `jhipster` will generate a relation using the name of the related entity, which means `user`, and that is not what you always want.

**Comment by jdubois** [comment]
Yes, that's a limitation.
At the moment the only thing you can do is to start up again, which forces you to think ahead and prepare your relationships/field names before firing up the generator. The other option would be to fill up random stuff in this question, edit the resulting .jhipster filter, and then run the generator again.
I don't think we could do much more at the moment.
