### ISSUE TITLE
Users are removed even if they have already been activated

### ISSUE THREAD

**Issue by avdev4j** [jhipster/generator-jhipster#9812]
##### **Overview of the issue**
Every day we check for not activated users and delete them. we should only do this for user that have never been activated.

##### **Motivation for or Use Case**
If we have an activated user and we deactivate him, the user will be deleted from the application if he stay inactivated for 3 days.
For me we should not remove users that have already been activated. For some reasons we could want to deactivate a user for more than 3 days and don't want him to be definitively deleted.

Of course for never activated users we should keep the same behaviour than before.

##### **Reproduce the error**
Create a user, activate him, deactivate him and wait for 3 days to see them disappeared from the database.

Tips:
If you don't have 3 days to loose change the scheduler for the `removeNotActivatedUsers()` method and the "before" date.

For example:
```
    @Scheduled(cron = "* * * * * ?")
    public void removeNotActivatedUsers() {
        userRepository
            .findAllByActivatedIsFalseAndActivationKeyIsNotNullAndCreatedDateBefore(Instant.now().minus(10, ChronoUnit.SECONDS))
            .forEach(user -> {
                log.debug("Deleting not activated user {}", user.getLogin());
                userRepository.delete(user);
                this.clearUserCaches(user);
            });
    }
```

##### **Suggest a Fix**
I think we can use the "activationKey" to know if the user have already been activate or not. The activitonKey is used to activate users by mail and it's set to null when the user is effectively activated.

##### **JHipster Version(s)**
6.0.1

##### **JHipster configuration**

```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.0.1",
    "applicationType": "monolith",
    "baseName": "fixUsersDeleted",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "ZDYwZmNkOGQwZDQ1MzdjMGRiYTk4MGJmNjIyZDFjNzc0YTkyNDlmMzc1ZTY1YTc3NTQzMGM4NmM1NDc5NjdlNWMxY2M0YWE0YWUwNTQ2NjcyNjFhMWY4MDYyY2M3MTI4NGY4NjFmNjQ3YTM3MjBjYWM2ZmMzMWI0ZDk5MDZmZjg=",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
N/A

##### **Browsers and Operating System**
MacOS

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
It's not the first time I see issues about this: deleting users can always be a cause of problem, even for non-activated ones. Maybe we should in fact totally remove that part.
Initially, I coded this as an example on how to use @Scheduled with JHipster, this wasn't really for solving a business case.
But yes, +1 for your issue and solution

**Comment by avdev4j** [comment]
IMO it's good to keep the `@scheduled` part, it's a great example of how scheduling tasks can be and it keep the DB clean.

**Comment by gzsombor** [comment]
The other, more general solution is to implement 'logical' deletion, instead of 'physical' - (like adding a 'deletionTime' column, and adding 'deletionTime is null' filters everywhere). This would make the DB happy, as no FK violation would occur during 'logical deletion'.
