### ISSUE TITLE
swagger-ui access_token error

### ISSUE THREAD

**Issue by maxleiko** [jhipster/generator-jhipster#982]
I suspect that you renamed the token name in the LocalStorage from `token` to `ls.token` resulting in an error when you try to access the API view as an admin.

```txt
Uncaught TypeError: Cannot read property 'access_token' of null 
```

You should rename `token` to `ls.token` in [swagger-ui/index.html](https://github.com/jhipster/generator-jhipster/blob/master/app/templates/src/main/webapp/swagger-ui/_index.html#61) line 61

**Comment by jdubois** [comment]
Thanks!

**Comment by anshumanpurohit** [comment]
After I made the change swagger-ui/index.html, things worked fine for my local. But when I deploy the generated war to AWS Beanstalk + RDS, it shows an empty page for swagger-ui.
