### ISSUE TITLE
JHipster on Jonas 5.2.3  no Spring context loading

### ISSUE THREAD

**Issue by sguiheux** [jhipster/generator-jhipster#983]
Hi,

I try to deploy Jhisper on a Jonas application server  5.2.3. The Spring context is not initialize. So I just have client side working.
The war file works great on tomcat 7

jonas.properties:   #jonas.service.web.class    org.ow2.jonas.web.tomcat6.Tomcat6Service
jonas.service.web.class    org.ow2.jonas.web.tomcat7.Tomcat7Service
My web.xml is empty.
My ApplicationWebXml.java: 
![image](https://cloud.githubusercontent.com/assets/1478025/5737511/fadcd59e-9be1-11e4-9a4c-77ec3dc74ee0.png)

Jonas console:
![image](https://cloud.githubusercontent.com/assets/1478025/5737546/501b891a-9be2-11e4-857d-7dad0bb7c9a8.png)

Do I miss something?

Regards,

**Comment by sguiheux** [comment]
it's Jonas 9.2.4 not 9.2.3

**Comment by gmarziou** [comment]
This is not a jhipster issue.
If you read [spring-boot doc](http://docs.spring.io/spring-boot/docs/current/reference/html/howto-traditional-deployment.html), you'll see that to deploy without a web.xml it'll require servlet 3.0 and to deploy on older servers like Jonas you must provide a web.xml and it must not be empty, you'll find [an example for servlet 2.5](http://docs.spring.io/spring-boot/docs/current/reference/html/howto-traditional-deployment.html#howto-servlet-2-5) but it seems to me that Jonas5.2.4  maybe even older (servlet 2.4?).

**Comment by jdubois** [comment]
I have reports from people at Orange who have successfully deployed JHipster on Jonas -> as it's the only company left using this app server, I suppose you must work there, you should reach them out.

Otherwise, indeed, this is not a JHipster issue, as no hipster would ever use Jonas :-)
