### ISSUE TITLE
Feature Contribution: Mobx store

### ISSUE THREAD

**Issue by erkieh** [jhipster/generator-jhipster#9838]
Would you guys be interested in a generator option for a React store implementation based on Mobx as an alternative to Redux? Since I prefer Mobx for React I have already done some work in my fork https://github.com/erkieh/generator-jhipster

**Comment by pascalgrimaud** [comment]
Can you argue why we should have Mobx as an alternative to Redux ?

I'm against to maintain 2 options without real additional value, so for me, I'd prefer to stick to Redux for React as it works well and we don't have any issue with this lib.

Then, you can develop a module or blueprint, to replace Redux by Mobx. Then, we can see if it's really popular.

**Comment by erkieh** [comment]
Not saying Redux is bad. Just I prefer the less verbose Mobx style and find it simpler to read and write. Your stance is agreeable and of course I am fine with going the blueprint route.

**Comment by pascalgrimaud** [comment]
ok so let's stick with Redux.
Don't hesitate to tweet and mention `@java_hipster` when you decide to start a module or blueprint
