### ISSUE TITLE
Generated App 404s on Browser Refresh

### ISSUE THREAD

**Issue by AlexanderNZ** [jhipster/generator-jhipster#9839]
##### **Overview of the issue**

There is appears to be inconsistent behaviour in navigating by links (in the nav bar for example) vs navigating by entering URLs directly in to the URL bar. This has impacts on things like page refresh.

##### **Motivation for or Use Case**

This is a bug because of user expectations around consistency.

Routing in the app should behave consistently, regardless of how a route is being triggered.

If I click a link and the app loads a page at http://localhost:9000/entity, refreshing the page or navigating directly to http://localhost:9000/entity should also load the page. Current behaviour is that the app produces a 404.

This is inconsistent again with using the old hashbang routing - If I create an app and attempt to navigate to an entity that doesn't exist (e.g. an app with a book entity and an author entity) and navigate to http://localhost:9000/fakeJhipsterEntity, the web app produces a 404, where navigating to http://localhost:9000/#/fakeJhipsterEntity redirects the browser to the home page.

##### **Reproduce the error**

Generate a new Jhipster 6 application with AngularX front end (I haven't tested on react)

##### **Related issues**

I could not find any

##### **Suggest a Fix**

I don't know the angular router well enough to suggest a fix (or I would just make a PR).
It seems to me to be an issue with the change from hashbang modeto HTML5 mode. More then that I'm not sure

##### **JHipster Version(s)**

6.0.1

##### **JHipster configuration**

INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
```
valuable-admin-client@0.0.0 C:\Users\user\Documents\jhipster
`-- generator-jhipster@6.0.1

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": false,
    "jhiPrefix": "valuable",
    "languages": ["en"],
    "messageBroker": false,
    "nativeLanguage": "en",
    "packageName": "com.myapp.jhipster",
    "packageFolder": "com/myapp/jhipster",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "serviceDiscoveryType": false,
    "skipClient": false,
    "skipServer": true,
    "testFrameworks": ["protractor", "cucumber", "gatling"],
    "websocket": false,
    "baseName": "jhipster",
    "applicationType": "monolith",
    "buildTool": "gradle",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "dtoSuffix": "DTO",
    "serverPort": "8080",
    "jhipsterVersion": "6.0.1",
    "skipUserManagement": false,
    "clientTheme": "none",
    "entitySuffix": "",
    "otherModules": []
  },
  "entities": [
    "Book",
    "Author",
  ]
}

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Book{
  name String required,
}
entity Author{
  name String required,
}

paginate Book, Author with infinite-scroll
service Book, Author with serviceClass

</pre>
</details>


##### **Environment and Tools**

java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

git version 2.17.1.windows.2

node: v8.11.3

npm: 5.6.0

yarn: 1.15.2

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

INFO! Congratulations, JHipster execution is complete!
```

##### **Browsers and Operating System**

Windows 10, Latest Firefox

-   [CHECK ] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
I tried to reproduce this with the default options but was not able to.  I'm guessing it's related to the separated client/server.

One solution is to restore the config like

**Comment by jdubois** [comment]
Yes be careful with the "skipServer" here, as this can only work thanks to a specific server code. What do you have on the server side, a JHipster 6 app?

**Comment by AlexanderNZ** [comment]
Thanks for the insight @ruddell, I'll keep an eye out for that PR and hopefully learn from it for the future!
Yes that's right @jdubois, Jhipster 6.0.1 on both ends.

If it's helpful, the complete JDL is that reproduces this is:

```
application {
  config {
    baseName bookshopApi
    packageName com.shop.book
    applicationType monolith
    databaseType sql
    devDatabaseType h2Memory
    prodDatabaseType postgresql
    buildTool gradle
    authenticationType jwt
    cacheProvider ehcache
    enableHibernateCache true
    clientFramework angularX
    useSass true
    clientPackageManager npm
    dtoSuffix DTO
    jhiPrefix valuable
    enableTranslation false
    nativeLanguage en
    languages [en]
    enableSwaggerCodegen false 		
	serviceDiscoveryType false
    messageBroker false
    serverPort 8080
    websocket false
    testFrameworks [protractor, cucumber, gatling]
    skipClient true
    skipServer false
  }
  entities *
}

application {
  config {
    baseName bookshopAdminClient
    packageName com.shop.book
    applicationType monolith
    databaseType sql
    devDatabaseType h2Memory
    prodDatabaseType postgresql
    buildTool gradle
    authenticationType jwt
    cacheProvider ehcache
    enableHibernateCache true
    clientFramework angularX
    useSass true
    clientPackageManager npm
    dtoSuffix DTO
    jhiPrefix valuable
    enableTranslation false
    nativeLanguage en
    languages [en]
    enableSwaggerCodegen false 		
	serviceDiscoveryType false
    messageBroker false
    serverPort 8080
    websocket false
    testFrameworks [protractor, cucumber, gatling]
    skipClient false
    skipServer true
  }
  entities *
}

entity Book {
	name String required
    webPageAddress String required
    billingContactEmailAddress String required
    primaryContactEmailAddress String required
}

entity Author {
	name String required
    primaryContactEmailAddress String required
}

entity Shop {
	name String required
    primaryContactEmailAddress String required
}

relationship OneToOne {
    Author to Shop
}

relationship OneToMany {
    Shop to Book
}

relationship ManyToMany {
    Author to Book
}

service * with serviceClass
paginate * with infinite-scroll
```

**Comment by wmarques** [comment]
I can confirm that you need to handle this part on your server configuration (apache, nginx, or in the webpack config when you develop) to always redirect into the `index.html` file.

**Comment by ruddell** [comment]
I'll open a PR tomorrow of the commit linked above after testing again.  

When using separate client/server, index.html does not exist on the backend, so refreshing gives a server-side 404 error.  The webpack proxy needs a slight tweak to handle this.

**Comment by Celebes** [comment]
@ruddell Problem still exists on JHipster v6.8.0 and separate server/client (both generated with JHipster). Navigating by <a> with routerLink works, refreshing gives 404 error. Adding historyApiFallback: {index: 'index.html'} in webpack.dev.js didn't help.

**Comment by ruddell** [comment]
@Celebes It looks like it's due to the `/auth` proxy.  You can change it to `/auth/` so it does not proxy `/authors`. PRs to fix this are welcome.
