### ISSUE TITLE
Enhancing release section of repo

### ISSUE THREAD

**Issue by raiyanalam** [jhipster/generator-jhipster#9853]
Hi,
   I was going through the repo, i found that it does not display much information in the release section of the repository. Currently it has only a long list of release tags. 
![image](https://user-images.githubusercontent.com/7879476/58855982-03ac2680-86bf-11e9-8a23-61faee264a25.png)
This section is really important for users who would want to know the latest changes that is incorporated in a release. Also GitHub notifies watchers that a new release is available whenever the repo publishes one. Solution wise, it might not be too tough to enhance this. Since the repo already uses azure pipelines, the built-in [github release task](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/GitHubReleaseV0) can be used to publish releases. The task can be configured to create a release only when the pipeline is triggered for a matching tag(Eg. 'v6.*'). It will compute the changes made in a release, cross reference it with corresponding issues and display a list. Optionally, we can also display a link to changelog file as well in the release notes.
Here is a [sample repo](https://github.com/Microsoft/vscode-react-native/releases) that leverages this capability.

![image](https://user-images.githubusercontent.com/7879476/58856456-5e924d80-86c0-11e9-846e-cb1ed7549823.png)

PS: I am a PM for azure pipelines. I would be happy to help with the changes :)

**Comment by pascalgrimaud** [comment]
Big +1 from me, as currently, our release notes are done manually: https://www.jhipster.tech/releases/
cc @jdubois

**Comment by jdubois** [comment]
@pascalgrimaud you mean moving from our website to the GitHub release page? I'd rather stay on our website, as I can tag everything at one (usually doing a release also mean updating portions of the website), and also that's better for our sponsors (lots of trafic on those pages, and Okta deserves to have its logo shown). At some point I'd also like to deliver a PDF doc of our website with each release, and for this we need everything there, including the release notes.
We could do a link on the GitHub release page, to our release page on the website, instead.

**Comment by atomfrede** [comment]
I like what Testcontainers is doing too. The use release drafter to create draft releases in GitHub automatically using issue tags. https://github.com/testcontainers/testcontainers-java/releases I would at least like to have a link to our official release notes in GitHub

**Comment by pascalgrimaud** [comment]
IMO, what could be done:
- automate the release notes at jhipster.tech
- add the link to the release note, in the tags sections

**Comment by raiyanalam** [comment]
@jdubois : we should definitely keep the website as it has its own advantages. However, simultaneously we should also leverage the in built capability provided by github for releases even if it is just posting a link to the relevant documentation. Several users scan this section to see how active the repo is and the changes that were incorporated in a release. Optionally, the task can also display an exhaustive list of changes and links to issues/commits that were included in the release. 

If it seems worthy, i would be happy work on a simple PR for this.

**Comment by pascalgrimaud** [comment]
@raiyanalam : I'd like to have this :) I'll discuss with Julien about it today

**Comment by raiyanalam** [comment]
@pascalgrimaud : Did you get an opportunity to discuss this with Julien?

**Comment by PierreBesson** [comment]
The initial idea from Julien is to have the information in only one place the jhipster.tech website and I tend to agree with it. 
Currently our issues and PR descriptions are not cleaned and uncurated which means that you cannot automatically extract good release notes from them. Very often we have users submitting PRs with unclear titles or content that is irrelevant to the release notes (eg. "fix CI builds"). But if someone can suggest a simple and easy to implement process to help with creating release notes, let's try it.

**Comment by pascalgrimaud** [comment]
@raiyanalam : sorry, I was quite busy these last weeks. I agree with Pierre. If there is something to do, it should go to https://github.com/jhipster/jhipster.github.io as the release note is there

**Comment by SudharakaP** [comment]
@PierreBesson @pascalgrimaud : One thing we could do without much effort and to give out some information about releases in the release notes page on Github is to use the https://github.com/marketplace/harvest-for-github plugin. With this plugin when you are making a release on Github you get and additional drop-down to specify the tag to compare. And then you can specify for example to list down all merged pull requests in-between. This might be a useful supplementary for developers and people who visit the Github pages so that they can see which pull requests are included in the release directly from the release page itself. 

I don't think this in any way replace the release notes, but I am just suggesting that this might be better than having nothing on the releases page and we can try it out since its very little effort.

**Comment by PierreBesson** [comment]
I guess it can't hurt. We can alzo

**Comment by SudharakaP** [comment]
@PierreBesson @pascalgrimaud : Yes, I can look into displaying the pull request list on the website if you guys like; but first maybe give the plugin a try and see if it works to the expectations.

**Comment by pascalgrimaud** [comment]
Currently, I'm fine with using milestones. 
The release note has a link to the milestone with all issues / PRs.

I think we can stay like this. 
Maybe try this once all the release workflow is automated.

That's why I'm closing this.
