### ISSUE TITLE
Translation (en.json) loading problem

### ISSUE THREAD

**Issue by zooldk** [jhipster/generator-jhipster#9857]
Hi,

I initially scafolded my angular project with jhipster in 2017. I then ported the projects so the client and server were split apart. In that process something happend with my translation files and how they are loaded. 

I can see that it loads the en.json file - but my problem is that it keeps loading (200 OK reply) it in the browser (almost 180 times) and its probably due to the buildTimestamp=undefined. I have tried to set it as an evnronment variable - but can't make it work. The en.json file exists and i can see it on the server and get 200 OK replies back. But it just keeps loading it multiple times. Does not work locally (with a proxy) or on a server.

Does  anybody have any ideas? Is it due to the timestamp missing or??? its hard to debug - because i cant really change the nature of ng-translate since jhipster is wrapping it.
 
##### **Jhipster Version**

"ng-jhipster": "^0.4.0"

this is loaded inside our @NgModule:

NgJhipsterModule.forRoot({
      // set below to true to make alerts look like toast
      alertAsToast: false,
      i18nEnabled: true,
      defaultI18nLang: 'en'
    }),

##### **Browsers and Operating System**

Tested with Chrome, IE etc.

**Comment by zooldk** [comment]
![Screenshot 2019-06-04 at 13 51 13](https://user-images.githubusercontent.com/1841838/58878171-eb460700-86d2-11e9-95b9-01c4486c4519.png)

**Comment by pascalgrimaud** [comment]
@zooldk : you need to follow our guidelines. Without that, how can we know your config, your tools, etc ?

**Comment by zooldk** [comment]
Sure i will provide as much as possible. But i have migrated my project so no more .yo config.  I have of course a .angular-cli.json file:

```
"apps": [{
        "root": "src",
        "outDir": "../pere/target/www/",
        "assets": [
            "content",
            "i18n",
            "swagger-ui",
            "favicon.ico"
        ],
        "index": "index.html",
        "main": "main.ts",
        "polyfills": "polyfills.ts",
        "test": "test.ts",
        "tsconfig": "tsconfig.app.json",
        "testTsconfig": "tsconfig.spec.json",
        "prefix": "jhi",
        "styles": [
            "content/scss/global.scss"
        ],
        "scripts": [
          "../node_modules/jquery/dist/jquery.min.js",
          "../node_modules/popper.js/dist/umd/popper.min.js",
          "../node_modules/bootstrap/dist/js/bootstrap.min.js"
        ],
        "environmentSource": "environments/environment.ts",
        "environments": {
            "dev": "environments/environment.ts",
            "prod": "environments/environment.prod.ts"
        }
```

snip of package.json file:

```
  "scripts": {
    "ng": "ng",
    "_start": "ng serve",
    "start": "ng serve --proxy-config proxy.conf.json",
    "build": "ng build --prod",
    "build-test": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "postinstall": "sync-pom-version ../xxx/pom.xml"
  },
```

Proxy.conf:

{
    "/api": {
        "target": "http://localhost:8080",
        "secure": false,
        "loglevel": "debug"
    },
    "/i18": {
        "target": "http://localhost:8080"
    }
}

environment file:
```
export const environment = {
 VERSION: (<any>appPackage).version + '-DEV',
  production: false,
  logger: {
    level: Level.LOG
  },
  mixpanel: 'xxx',
  stripeKey : 'xxx',
};
```

What more is needed?

**Comment by vishal423** [comment]
Do you use JHipster webpack build process? If yes, then, following code in the webpack.common.js file define and substitute this value during the build process:

<pre>
plugins: [
        new webpack.DefinePlugin({
            'process.env': {
                NODE_ENV: `'${options.env}'`,
                <b>BUILD_TIMESTAMP: `'${new Date().getTime()}'`,</b>
                VERSION: `'${utils.parseVersion()}'`,
                DEBUG_INFO_ENABLED: options.env === 'development',
                // The root URL for API calls, ending with a '/' - for example: `"https://www.jhipster.tech:8081/myservice/"`.
                // If this URL is left empty (""), then it will be relative to the current context.
                // If you use an API server, in `prod` mode, you will need to enable CORS
                // (see the `jhipster.cors` common JHipster property in the `application-*.yml` configurations)
                SERVER_API_URL: `''`
            }
        }),
</pre>

**Comment by zooldk** [comment]
Hi @vishal423 . Thanks for the answer. No we have not kept the webpack build process - but moved into all normal ng-cli - and thats why i was asking how do i update the undefined BUILD_TIMESTAMP i general. As you can see we are using the package.json file along with ng-cli.

I have also tried to enforce the environement variable in the build, when calling yarn start:

```
  "scripts": {
    "ng": "ng",
    "_start": "ng serve",
    "start": "BUILD_TIMESTAMP=1234; ng serve --proxy-config proxy.conf.json",
    "build": "ng build --prod",
    "build-test": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
  },
```
But that did not help either.

**Comment by zooldk** [comment]
So how can i otherwise override this undefined variable that is implicitly called. Is the code somewhere i can override - using normal ngx-translate or?

**Comment by zooldk** [comment]
Ok thats fair enough. But since i am using jhipster for doing the translations I just hoped to find out where to override this undefined date. Otherwise how do I disable the translations? because setting the i18nEnabled in false in the NgJhipsterModule.forRoot does not work - it still calls almost 200 http calls.

**Comment by vishal423** [comment]
An alternative ugly way could be to create a fork of ng-jhipster and override with whatever you want and use that in your project

Relevant code can be located under `ng-jhipster.module.ts` in `ng-jhipster` 

```
export function translatePartialLoader(http: HttpClient) {
    return new TranslateHttpLoader(http, 'i18n/', `.json?buildTimestamp=${process.env.BUILD_TIMESTAMP}`);
}
```
