### ISSUE TITLE
JavaScript canot use large number from Java type Long

### ISSUE THREAD

**Issue by jankod** [jhipster/generator-jhipster#9861]
Jhipster generates a rest controller that retrieves the ID entity which is type Long.
The problem is that the large number of type Long can not be displayed in javascript.

Problem is described also here [https://stackoverflow.com/questions/17320706/javascript-long-integer](https://stackoverflow.com/questions/17320706/javascript-long-integer)

It is not problem of jhipster, but JavaScript. 

Java Spring:
```
@GetMapping("/long")
public Long getLong() {
   Long number = Long.MAX_VALUE ;
   log.debug("number {}", number);
   return number;
}
```

Angular 
```
  getLong() {
     this.http.get('http://localhost:4111/long').subscribe(data => {
      console.log("long ", data);
    });
  }
```

Java console show: 9223372036854775807
Javascript console show: 9223372036854776000

**Comment by ruddell** [comment]
Is there something actionable that we can do?  I don't think most apps will ever get to 999,999,999,999,999 entities.  

Also a simpler way to reproduce without having to modify a generated app is to simply paste `9223372036854775807` in the browser console.

**Comment by jankod** [comment]
Maybe solution is:
On Java Entity:  
```
@JsonSerialize(using=ToStringSerializer.class)
Long id; 
```

On Angular model:
```
id?: string;
```

**Comment by ruddell** [comment]
To me, this is a rare edge-case so we shouldn't force everyone to send the ID as a string field when most people will never hit that number.

**Comment by jankod** [comment]
Also work if on java Long type add:
```
@JsonSerialize(using=ToStringSerializer.class)
Long id;
```

and on angular:
`id?: bigint;`

**Comment by PierreBesson** [comment]
This is a really interesting bug but a very rare use case IMO. Still I'm glad that I learned something with this issue.
@jankod I'm curious did you really encounter this bug in your app ?

**Comment by jankod** [comment]
> @jankod I'm curious did you really encounter this bug in your app ?
Yes, 
I have methods that generate generate unique Long IDs in my app and this Long are usually very large number that I can not see in my angular app if expected TypeScript number type from JSON response.

```java
Long createUniqueID() {
    return UUID.randomUUID().getMostSignificantBits() & Long.MAX_VALUE;
}
```
