### ISSUE TITLE
generate middleware (spring crud) repositories from an existing database

### ISSUE THREAD

**Issue by jhulick** [jhipster/generator-jhipster#987]
There is a code generator here at [spring-data-rest-templates-TT210](https://github.com/bewilcox/spring-data-rest-templates-TT210) that will scan an existing database schema and generate the middleware JPA Spring data repositories for you. I haven't tested this project, or used the dependent Telosys utility before, but I think this kind of feature would add a lot of value to this already excellent project.

**Comment by jdubois** [comment]
Yes, there is already #925 on this subject
I don't know if we will be able to have some kind of GUI on top of JHipster:
- It could be cool, but I don't know if there's a lot of added value (the questions also add validation, etc, which you can't do graphically)
- I have no idea if we should use something that generates from an existing database, or uses UML... Both approaches have pros and cons

**Comment by jhulick** [comment]
In my line of work we develop/maintain a lot of line-of-business applications. They are long lived and many have well established domain models that may last 10+ years. In this sector rewrites or new apps are often created over existing database models, and so a feature such as this would add a lot of value. We've looked at the excellent [PostgREST](https://github.com/begriffs/postgrest) utility as a means to generate the REST API but need to stick with JVM platform. The spring-data-rest-templates utility generates a REST API (HATEOAS/HAL) via Spring repositories for an existing RDBMS (along with validation stubs) and so offers something similar. Anyway, thanks for your time and input. Looking forward to see more progress on your excellent project.
