### ISSUE TITLE
Allow extending JDL application options from a blueprint

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/generator-jhipster#9870]
See https://github.com/jhipster/jhipster-core/pull/344

##### **Overview of the feature request**

Currently when using JHipster with a blueprint that extend the available application options, it is not possible to select those options when generating an app using the JDL.

JHipster should expose an API that let blueprint developers edit the available application_options, potentially extending or restricting them. Currently they are declared in jhipster-core (see [jhipster-core/lib/core/jhipster/application_options.js](https://github.com/jhipster/jhipster-core/blob/master/lib/core/jhipster/application_options.js)) with no way to extend them from a blueprint.

##### **Motivation for or Use Case**

An currently failing scenario:
**app.jdl**
```
application {
  config {
    baseName vuejsApp,
    clientFramework vuejs
  }
}
```
When running:

    jhipster -b vuejs import-jdl app.jdl

It fails with:

    Error: Unknown value 'vuejs' for option 'clientFramework'.
    Error while parsing applications and entities from the JDL Error: Unknown value 'vuejs' for 
    option 'clientFramework'.

# Related issues

#8915 JDL centric configurations

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
Since the JHipster-UML is deprecated I think this will be much easier if we
merge JHipster-core into generator as Mathieu suggested earlier, we can
still expose the public API from core so that people can use it directly

Thanks & Regards,
Deepu

**Comment by ksilz** [comment]
@PierreBesson Would this request also help in the following scenario:

I want to customize the generated Angular front end through a configurable blueprint. So instead of putting a config file into my jHipster project which the blueprint then reads (can it actually?), I define configuration options (such as "hideDeletion" or "detailLinkColumn") in the JDL instead.

**Comment by PierreBesson** [comment]
@deepu105 Yes I was also considering that the merging of jhipster-core should go first. Maybe we could create a separate issue for it.

**Comment by deepu105** [comment]
Yes, let's do it. Ping @MathieuAA

**Comment by MathieuAA** [comment]
I like this GH issue. I'm gonna create an issue for this.

**Comment by MathieuAA** [comment]
Oh and if you guys agree, I'll create a new project to better keep track of the related tasks

**Comment by danielpetisme** [comment]
For the dotnetcore blueprint I need to ignore some Java oriented options
and in the future I would like to add new keywords.

So, you have a big +1 from my part.

Let me know if I can help somehow.

**Comment by MathieuAA** [comment]
@danielpetisme thanks :) I'll definitely ping you

**Comment by PierreBesson** [comment]
As a workaround to let users generate vuejs apps with the JDL, I opened a PR to jhipster-core with a workaround: https://github.com/jhipster/jhipster-core/pull/338 (adding vuejs to the list of client-frameworks).

**Comment by pascalgrimaud** [comment]
@MathieuAA @mshima @PierreBesson : as it's opened for a while, does one of you start to work on this ? Should we let this ticket opened ?

**Comment by MathieuAA** [comment]
It's something that needs doing, but right now, I'm busy with another task.

**Comment by mshima** [comment]
I think we should use something like:
clientFramework vuejs:vuejs
vuejs:clientTheme foo

Every key and value with : should be ignored for now.
I am busy removing yo dependency (improving environment lookup to be selective)

**Comment by MathieuAA** [comment]
SImpler: we could _not_ validate what the user writes in the JDL file(s) and perform a validation just before the application-generation phase in the generator.

**Comment by PierreBesson** [comment]
@MathieuAA maybe add a --skip-jdl-validation flag as a workaround which would implement solution 1, then proceed with solution 2.

**Comment by mshima** [comment]
I have a blueprint that implements a custom config. So it would be nice to support it.
I like the idea of namespacing the config to be easy to differentiate from oficial configurations.

**Comment by MathieuAA** [comment]
@PierreBesson I like your idea. As soon as I wrap what I'm on, I can start implementing this. Unless there's someone willing to start it now of course

**Comment by mraible** [comment]
@MathieuAA You were interested in implementing this in January? Are you still interested? If not, I suggest we close this issue.

**Comment by mshima** [comment]
At least we should implement annotations at application.
This issue have taken too long already, there is no way to add a custom config for blueprints.

**Comment by MathieuAA** [comment]
Commenting. @nicolas63's PR should fix it after some changes are done, #12975.

**Comment by MathieuAA** [comment]
And BTW, thanks @nicolas63 to have proposed a PR for your issue (which involves this one too).

**Comment by mshima** [comment]
This is important to have.

**Comment by DanielFran** [comment]
@mshima Can you confirm this can be closed?

**Comment by mshima** [comment]
@DanielFran no, I've added support to defining jdl options outside jdl implementation, but loading logic it is still hardcoded.
There is not way to inject the options, and there is no lookup of jdl options.

Lookup should be implemented for options, config and jdl definition related to not finished https://github.com/jhipster/generator-jhipster/pull/21192

**Comment by mshima** [comment]
Implemented in https://github.com/jhipster/generator-jhipster/pull/23961

**Comment by deepu105** [comment]
Is this documented somewhere if not can we please add it to docs. We are having a lot of undocumented changes
