### ISSUE TITLE
Add cache entry listener logger for ehcache

### ISSUE THREAD

**Issue by DanielFran** [jhipster/generator-jhipster#9871]
##### **Overview of the feature request**

Implements a cache entry listener to allow to log what is happenning with cache.

##### **Motivation for or Use Case**

This might be usefull to log for investigation perpose.

##### **Possible implementation**

```java
import javax.cache.event.CacheEntryCreatedListener;
import javax.cache.event.CacheEntryEvent;
import javax.cache.event.CacheEntryExpiredListener;
import javax.cache.event.CacheEntryListenerException;
import javax.cache.event.CacheEntryRemovedListener;
import javax.cache.event.CacheEntryUpdatedListener;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * A custom cache entry listener.
 */
public class CacheEntryListenerLogger implements CacheEntryCreatedListener<Object, Object>, CacheEntryUpdatedListener<Object, Object>, CacheEntryExpiredListener<Object, Object>, CacheEntryRemovedListener<Object, Object> {

    private static final Logger log = LoggerFactory.getLogger(CacheEntryListenerLogger.class);
    
    @Override
    public void onCreated(Iterable<CacheEntryEvent<? extends Object, ? extends Object>> events) throws CacheEntryListenerException {
        for (CacheEntryEvent<? extends Object, ? extends Object> entryEvent : events) {
            log.info("Cache event {} for key {} with value {}", entryEvent.getEventType(), entryEvent.getKey(), entryEvent.getValue());
        }
    }

    @Override
    public void onUpdated(Iterable<CacheEntryEvent<? extends Object, ? extends Object>> events) throws CacheEntryListenerException {
        for (CacheEntryEvent<? extends Object, ? extends Object> entryEvent : events) {
            log.info("Cache event {} for key {}, with old value {} and new value {}", entryEvent.getEventType(), entryEvent.getKey(), entryEvent.getOldValue(), entryEvent.getValue());
        }
    }

    @Override
    public void onExpired(Iterable<CacheEntryEvent<? extends Object, ? extends Object>> events) throws CacheEntryListenerException {
        for (CacheEntryEvent<? extends Object, ? extends Object> entryEvent : events) {
            log.info("Cache event {} for key {} with value {}", entryEvent.getEventType(), entryEvent.getKey(), entryEvent.getValue());
        }
    }

    @Override
    public void onRemoved(Iterable<CacheEntryEvent<? extends Object, ? extends Object>> events) throws CacheEntryListenerException {
        for (CacheEntryEvent<? extends Object, ? extends Object> entryEvent : events) {
            log.info("Cache event {} for key {} with value {}", entryEvent.getEventType(), entryEvent.getKey(), entryEvent.getValue());
        }
    }
    
}
```

```java
import java.time.Duration;

import org.ehcache.config.builders.*;
import org.ehcache.jsr107.Eh107Configuration;

import io.github.jhipster.config.jcache.BeanClassLoaderAwareJCacheRegionFactory;
import io.github.jhipster.config.JHipsterProperties;
import io.github.jhipster.config.jcache.CacheEntryListenerLogger;
import javax.cache.configuration.FactoryBuilder;
import javax.cache.configuration.MutableCacheEntryListenerConfiguration;

import org.springframework.boot.autoconfigure.cache.JCacheManagerCustomizer;
import org.springframework.cache.annotation.EnableCaching;
import org.springframework.context.annotation.*;

@Configuration
@EnableCaching
public class CacheConfiguration {

    private final javax.cache.configuration.Configuration<Object, Object> jcacheConfiguration;

    private final javax.cache.configuration.CacheEntryListenerConfiguration<Object, Object> jcacheEntryListenerConfiguration;
    
    public CacheConfiguration(JHipsterProperties jHipsterProperties) {
        BeanClassLoaderAwareJCacheRegionFactory.setBeanClassLoader(this.getClass().getClassLoader());
        JHipsterProperties.Cache.Ehcache ehcache =
            jHipsterProperties.getCache().getEhcache();

        jcacheEntryListenerConfiguration = new MutableCacheEntryListenerConfiguration<>(
                FactoryBuilder.factoryOf(CacheEntryListenerLogger.class),
                null,
                false,
                false);
        
        jcacheConfiguration = Eh107Configuration.fromEhcacheCacheConfiguration(
            CacheConfigurationBuilder.newCacheConfigurationBuilder(Object.class, Object.class,
                ResourcePoolsBuilder.heap(ehcache.getMaxEntries()))
                .withExpiry(ExpiryPolicyBuilder.timeToLiveExpiration(Duration.ofSeconds(ehcache.getTimeToLiveSeconds())))
                .build());
    }

    @Bean
    public JCacheManagerCustomizer cacheManagerCustomizer() {
        return cm -> {
            cm.createCache(io.myproject.entity.Category.class.getName(), jcacheConfiguration).registerCacheEntryListener(jcacheEntryListenerConfiguration);
        };
    }
}
```

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by DanielFran** [comment]
@jhipster/developers Do you consider this functionality interesting?

**Comment by PierreBesson** [comment]
I'm wondering if you could set the log level to DEBUG or TRACE for Ehcache to achieve the same result.

**Comment by PierreBesson** [comment]
@danielfran Does setting org.springframework.cache to TRACE level is not enough for you ?

**Comment by DanielFran** [comment]
Thinking this could be usefull, will test your approach...

**Comment by pascalgrimaud** [comment]
for me, +1
unless setting `org.springframework.cache` to TRACE level is enough

**Comment by DanielFran** [comment]
I did some tests and here is the result setting _org.springframework.cache_ to _TRACE_:
- 1st attempt (no cache available):
{"level":"TRACE","logger_name":"o.s.c.i.CacheInterceptor","message":"**Computed cache key 'SimpleKey [banana,1,2]' for operation Builder[public abstract java.util.List io.mytest.domain.repository.ProductRepository.findMyCachedProduct(java.lang.String,java.lang.Short,java.lang.Short)] caches=[myCachedProduct] | key='' | keyGenerator='' | cacheManager='' | cacheResolver='' | condition='' | unless='' | sync='false'**"}
{"level":"TRACE","logger_name":"o.s.c.i.CacheInterceptor","message":"**No cache entry for key 'SimpleKey [banana,1,2]' in cache(s) [myCachedProduct]**"}
{"level":"TRACE","logger_name":"o.s.c.i.CacheInterceptor","message":"**Computed cache key 'SimpleKey [banana,1,2]' for operation Builder[public abstract java.util.List io.mytest.domain.repository.ProductRepository.findMyCachedProduct(java.lang.String,java.lang.Short,java.lang.Short)] caches=[myCachedProduct] | key='' | keyGenerator='' | cacheManager='' | cacheResolver='' | condition='' | unless='' | sync='false'**"}

- 2nd attempt (with existing cache):
{"level":"TRACE","logger_name":"o.s.c.i.CacheInterceptor","message":"**Computed cache key 'SimpleKey [banana,1,2]' for operation Builder[public abstract java.util.List io.mytest.domain.repository.ProductRepository.findMyCachedProduct(java.lang.String,java.lang.Short,java.lang.Short)] caches=[myCachedProduct] | key='' | keyGenerator='' | cacheManager='' | cacheResolver='' | condition='' | unless='' | sync='false'**"}
{"level":"TRACE","logger_name":"o.s.c.i.CacheInterceptor","message":"**Cache entry for key 'SimpleKey [banana,1,2]' found in cache 'myCachedProduct'**"}


Now with the helper:
- 1st attempt (no cache available):
{"level":"INFO","logger_name":"i.m.c.c.CacheEntryListenerLogger","message":"**Cache event CREATED for key io.mytest.domain.repository.ProductRepository.findMyCachedProduct#myCachedProduct{product=banana, box=1, category=2} with value CacheEntry(io.mytest.domain.repository.ProductRepository.myCachedProduct)**"}
- 2nd attempt (with existing cache): **Nothing to show since it uses the cache entry.**

**Comment by DanielFran** [comment]
@PierreBesson as you can see the information we get is totally different, the purpose of the helper is just to log when the data as created / removed / updated / expired in the cache.

Is it OK for you to proceed?

**Comment by DanielFran** [comment]
Closing: see https://github.com/jhipster/generator-jhipster/pull/9951
