### ISSUE TITLE
OAuth2 without service discovery: gateway compilation errors

### ISSUE THREAD

**Issue by dgeorgiev06** [jhipster/generator-jhipster#9877]
##### **JHipster Version(s)**

```
gateway@0.0.0 /Users/alexandrastefanova/developer/projects/urban/gateway
└── generator-jhipster@6.0.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.urban.gateway"
    },
    "jhipsterVersion": "6.0.0",
    "applicationType": "gateway",
    "baseName": "gateway",
    "packageName": "com.urban.gateway",
    "packageFolder": "com/urban/gateway",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "clientFramework": "react",
    "clientTheme": "journal",
    "clientThemeVariant": "primary",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Profile
relationship OneToOne {
  Profile{user(login)} to User
}

dto Profile with mapstruct
paginate Profile with infinite-scroll
service Profile with serviceClass
filter Profile

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

git version 2.13.1

node: v10.15.1

npm: 6.9.0

yeoman: 2.0.5

yarn: 1.13.0

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

##### **Overview of the issue**

gateway process fails to compile class AuthorizationHeaderFilter with com.netflix.zuul not found error

##### **Motivation for or Use Case**

I want to deploy to a GCP kubernetes cluster with ingress/istio for load balancing.  So i choose to generate a jhipster gateway  without a jhipster registry 

##### **Reproduce the error**

generate a microservices gateway without a registry and with oauth2 authentication and compile it

##### **JHipster Version(s)**

6

##### **JHipster configuration**

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.urban.gateway"
    },
    "jhipsterVersion": "6.0.0",
    "applicationType": "gateway",
    "baseName": "gateway",
    "packageName": "com.urban.gateway",
    "packageFolder": "com/urban/gateway",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "clientFramework": "react",
    "clientTheme": "journal",
    "clientThemeVariant": "primary",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

profile.json

{
    "fluentMethods": true,
    "clientRootFolder": "",
    "relationships": [
        {
            "relationshipName": "user",
            "otherEntityName": "user",
            "relationshipType": "one-to-one",
            "otherEntityField": "login",
            "ownerSide": true,
            "useJPADerivedIdentifier": true,
            "otherEntityRelationshipName": "profile"
        }
    ],
    "fields": [],
    "changelogDate": "20190609151112",
    "dto": "mapstruct",
    "searchEngine": false,
    "service": "serviceClass",
    "entityTableName": "profile",
    "databaseType": "sql",
    "jpaMetamodelFiltering": true,
    "pagination": "infinite-scroll"
}

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
As you choose "no service discovery", it's an option we didn't test in our CI.
If you find the fix, feel free to PR.

Here the full stacktrace for people who want to work on this:

```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/pgrimaud/tmp/13-issue-9877/src/main/java/com/urban/gateway/security/oauth2/AuthorizationHeaderFilter.java:[3,24] package com.netflix.zuul does not exist
[ERROR] /home/pgrimaud/tmp/13-issue-9877/src/main/java/com/urban/gateway/security/oauth2/AuthorizationHeaderFilter.java:[4,32] package com.netflix.zuul.context does not exist
[ERROR] /home/pgrimaud/tmp/13-issue-9877/src/main/java/com/urban/gateway/security/oauth2/AuthorizationHeaderFilter.java:[10,69] package org.springframework.cloud.netflix.zuul.filters.support does not exist
[ERROR] /home/pgrimaud/tmp/13-issue-9877/src/main/java/com/urban/gateway/security/oauth2/AuthorizationHeaderFilter.java:[10,1] static import only from classes and interfaces
[ERROR] /home/pgrimaud/tmp/13-issue-9877/src/main/java/com/urban/gateway/security/oauth2/AuthorizationHeaderFilter.java:[12,48] cannot find symbol
  symbol: class ZuulFilter
[INFO] 5 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  48.048 s
[INFO] Finished at: 2019-06-10T20:03:53+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project gateway: Compilation failure: Compilation failure: 
[ERROR] /home/pgrimaud/tmp/13-issue-9877/src/main/java/com/urban/gateway/security/oauth2/AuthorizationHeaderFilter.java:[3,24] package com.netflix.zuul does not exist
[ERROR] /home/pgrimaud/tmp/13-issue-9877/src/main/java/com/urban/gateway/security/oauth2/AuthorizationHeaderFilter.java:[4,32] package com.netflix.zuul.context does not exist
[ERROR] /home/pgrimaud/tmp/13-issue-9877/src/main/java/com/urban/gateway/security/oauth2/AuthorizationHeaderFilter.java:[10,69] package org.springframework.cloud.netflix.zuul.filters.support does not exist
[ERROR] /home/pgrimaud/tmp/13-issue-9877/src/main/java/com/urban/gateway/security/oauth2/AuthorizationHeaderFilter.java:[10,1] static import only from classes and interfaces
[ERROR] /home/pgrimaud/tmp/13-issue-9877/src/main/java/com/urban/gateway/security/oauth2/AuthorizationHeaderFilter.java:[12,48] cannot find symbol
[ERROR]   symbol: class ZuulFilter
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by Hawkurane** [comment]
To fix this, we can either just remove all compilation problems by commenting the code or add the required dependency to the pom.xml

I don't see any reasons not to include dependency to the pom.xml even if the zuul filter is not used explicitly as the feature can be either readded or removed afterwards depending on the use case.

**Comment by Hawkurane** [comment]
@PierreBesson I don't know which is best practice, to enable Zuul either way even without service discovery or remove it completely and let the user use the context path

**Comment by PierreBesson** [comment]
If you have a gateway without Zuul arguably it's can not really serve as a gateway anymore. Moreover if you remove service discovery it will not be able to find microservices instances. So this case is only theoretical for now. IMO it should be forbidden to generate a configuration like that (gateway + no discovery) as it doesn't make any sense.

**Comment by Hawkurane** [comment]
Supposedly if the service discovery is added later, is it better to let zuul being generated or let the user add it later as well? Either way, I can make a PR for both cases but removing zuul might crash other builds as some files are used elsewhere (OIDC for example)

**Comment by dgeorgiev06** [comment]
I am playing with ingress/istio on gcp so i expect the setup to provide load balancing and discovery instead of zuul and ribbon
