### ISSUE TITLE
Unable to start embedded container and unable to start Tomcat Server error

### ISSUE THREAD

**Issue by ConfusedIntern** [jhipster/generator-jhipster#988]
So I am new to this whole world, but I am not quite sure what went wrong. I set up my project to use H2 cache memory, and I created an entity. This worked correctly after I ran the project, but cause problems when I tried to create more. I control-c the project and ended the batch job, and then I created a new entity with a relationship to the previous entity. It created fine but this error occurred when I tried to run it:

``` Exception in thread "main" org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat```

The top warning was as follows:

```org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt```

```Caused by: org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat```

**Comment by jdubois** [comment]
I can't reproduce your error.
Please read https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submit and give us more information about your setup.

**Comment by Rmabini** [comment]
Hi Hello I am getting an error starting the project, It has something to do with oracle not being started, I have already define a the credential in the yml. 
datasource:
        driverClassName: oracle.jdbc.OracleDriver
        dataSourceClassName: oracle.jdbc.pool.OracleDataSource
        url: jdbc:oracle:thin:@localhost:1521:orcl
        databaseName: employerApp
        serverName: employerApp
        username: employerApp  
        password: employerApp  

Don't know what seem's to be the problem

**Comment by jomach** [comment]
Hi, I'm getting the same error using the https://github.com/mstahv/spring-data-vaadin-crud and hooking up a custom Spring Scheduler...

**Comment by gmarziou** [comment]
@jomach Please don't post on a closed issue, open a new one if you think you encountered a jhipster bug which dos not seem obvious as you're using vaadin.
