### ISSUE TITLE
Static vs content folders on client-side

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#9880]
Seems like we are using a mix of `static` and `content` as folder names for static content between the client frameworks.
- Angular is using `content`
- React is using `static` which get copied into `content` when building
- for microservices there is an index.html in `static` folder

This is confusing for users hence we should streamline this and use same folder names in all client-side

Related to https://github.com/jhipster/generator-jhipster/pull/9879

**Comment by avdev4j** [comment]
I'm taking this one. As `static` folder `content` is currently copied to the `content` one I'll take `content` as both folder name for Angular and React.

**Comment by deepu105** [comment]
I think there was some issue with folder names for JAR packaging. I don't recall the details(@jhipster/developers anyone remember what the issue was). Also for microservices, the index is being copied to static

**Comment by avdev4j** [comment]
you're right @deepu105 
https://github.com/jhipster/generator-jhipster/blob/master/generators/server/files.js#L739

But it's the spring boot static folder not the React one. So for me it's not a problem, we always have a static folder (from spring boot) which contain our React or Angular App and his content folder (the old static one for React).

 Next time I will check the JAR packaging

**Comment by PierreBesson** [comment]
I confirm this "static" comes from spring boot https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-developing-web-applications.html#boot-features-spring-mvc-static-content

**Comment by avdev4j** [comment]
I've just made some tests with a jar file (build with prod profil) launch on my laptop. Everything work as expected. 

I remove the draft status on the PR, if we have known issues with JAR file let me know.

**Comment by deepu105** [comment]
Did you test runnng app in dev mode via maven/gradle and via IDE and from
the main class?

Thanks & Regards,
Deepu

**Comment by avdev4j** [comment]
I've test dev profile with both gradle and maven and both via launching the main class and the wrappers `./mvnw` `./gradlew`

**Comment by avdev4j** [comment]
close by https://github.com/jhipster/generator-jhipster/pull/9893
