### ISSUE TITLE
main.css not present in directory

### ISSUE THREAD

**Issue by davykiala** [jhipster/generator-jhipster#989]
I've just download the last version of jhipster. I create a project. When i run the project i have some 404 error on main.css. Why this ? is it normal ?
![main css](https://cloud.githubusercontent.com/assets/4395342/5767965/bfe636e8-9d0c-11e4-8384-93ca8bed9753.PNG)
![main css1](https://cloud.githubusercontent.com/assets/4395342/5767973/d21d17a0-9d0c-11e4-84b2-2901fde146c2.PNG)

**Comment by jdubois** [comment]
I can't reproduce your error.
I guess you are using Compass -> in that case you need to run "grunt serve", if you use Grunt... That all depends on your JHipster options and versions, so please read https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submit and give us more information.

**Comment by davykiala** [comment]
Thank you for your answer. I've change my configuration now. I no longer choose Compass and it's work like a charm.
