### ISSUE TITLE
[React] Use hooks for components

### ISSUE THREAD

**Issue by qmonmert** [jhipster/generator-jhipster#9891]
##### Use hooks in all React components

Hooks are available since the version 16.8 of React. The goal will be to integrate hooks in JHipster.

##### Todo

Here are all the components that seem be impacted :

-   [x] Header #9883 **MERGED**
-   [x] Password #9899 **MERGED**
-   [x] Register #9899 **MERGED**
-   [x] Configuration #9919 **MERGED**
-   [x] Health #9921 **MERGED**
-   [x] Logs #9921 **MERGED**
-   [x] Activate #9964 **MERGED**
-   [x] Logout #9968 **MERGED**
-   [x] Settings #9965 **MERGED**
-   [x] Metrics #9966 **MERGED**
-   [x] PasswordResetFinish #9924 **MERGED**
-   [x] UserManagementDetail #9929 **MERGED**
-   [x] UserManagementDeleteDialog #9938 **MERGED**
-   [x] UserManagementUpdate #9938 **MERGED**
-   [x] Home #9969 **MERGED**
-   [x] Login #9971 **MERGED**
-   [x] App #9972 **MERGED**
-   [x] Audits #9975 **MERGED**
-   [x] UserManagement #9981 **MERGED**

And the entities :

-   [ ] Entity #9983 ❌

**Comment by deepu105** [comment]
@qmonmert I suggest doing small PRs so that its easy to review and test, may a PR per module(admin, layout, account, entity)

**Comment by qmonmert** [comment]
@deepu105 yes I'm doing some small PRs

**Comment by deepu105** [comment]
Once we implement the new bounty system, this issue should get 300$ bounty atleast

**Comment by deepu105** [comment]
@jdubois I have changed the bounty amount as this is a lot of work and deserves more. Hope you are fine with it

**Comment by jdubois** [comment]
Of course I am!!

**Comment by pascalgrimaud** [comment]
Crazy work here @qmonmert !
Hope someone with more experience with React can review all your PRs

**Comment by qmonmert** [comment]
thanks @pascalgrimaud :) I hope cc @deepu105 & @chrisdns ;)

**Comment by qmonmert** [comment]
@deepu105 & @pascalgrimaud I am not able to make azure e2e tests pass for PRs #9968 & #9981 even after multiple attempts (it works locally). Are these PR still mergeable are should we wait for success ?

**Comment by deepu105** [comment]
excellent work @qmonmert :clap:

**Comment by pascalgrimaud** [comment]
Yes nice work @qmonmert !
About the 2 others PRs, sorry I was busy the last weeks... I'll have a look when possible

**Comment by pascalgrimaud** [comment]
@qmonmert : I'm increasing the bounty, as it was really too much work, and you're still working on it to achieve this enhancement. So it will be well deserved

**Comment by qmonmert** [comment]
I claim my money :) https://opencollective.com/generator-jhipster/expenses/11978

**Comment by jdubois** [comment]
Already paid, I trust you :-P

**Comment by qmonmert** [comment]
thanks @jdubois :)

**Comment by pascalgrimaud** [comment]
you're too fast @jdubois !
thanks for the hard work @qmonmert !!

**Comment by qmonmert** [comment]
thanks @pascalgrimaud ;)
