### ISSUE TITLE
Wired behavior when clicking register then login link from register. 

### ISSUE THREAD

**Issue by svennela** [jhipster/generator-jhipster#990]
Hi ,

I am seeing wired behavior when clicking register then login link from register. authentication fails.
steps to reproduce.
1) click register
2) login
3) try to login with admin/admin

Thank you,
Sridhar

**Comment by jdubois** [comment]
I need to have more information on your version, options, etc.
Please read Please read https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submit and give us more information.
