### ISSUE TITLE
Test missgenerated on certain relationships

### ISSUE THREAD

**Issue by amatosg** [jhipster/generator-jhipster#9904]
##### **Overview of the issue**

When generating entities with certain relationship, the test is wrongly generated.

##### **Motivation for or Use Case**
Test should be generated properly

##### **Reproduce the error**

The only case I have is this 2 entities 
```
entity Partner {
    name String required
    title PartnerTitle,
    phone String,
    mobile String,
    email String,
    avatar ImageBlob,
    birthday LocalDate,
    active Boolean required,
    comment TextBlob,
    contactName String,
    organizationName String,
    individual Boolean,
    supplier Boolean,
    customer Boolean,
    documentType DocumentType,
    documentNumber String,
    employee Boolean
}
```
and
```
entity Address {
    name String required
    contact String
    mobile String
    address String
    note TextBlob
    delivery Boolean
    invoicing Boolean
    active Boolean
}
```
With relationship
```
relationship OneToMany {
    Partner{address(name) required} to Address{partner(name)}
}
```

The resulting test is like this:
```java
@Test
@Transactional
public void getAllPartnersByAddressIsEqualToSomething() throws Exception {
    // Get already existing entity
    Address address = partner.getAddress();
    partnerRepository.saveAndFlush(partner);
    Long addressId = address.getId();

    // Get all the partnerList where address equals to addressId
    defaultPartnerShouldBeFound("addressId.equals=" + addressId);

    // Get all the partnerList where address equals to addressId + 1
    defaultPartnerShouldNotBeFound("addressId.equals=" + (addressId + 1));
}
``` 
The error is that it's generating `Address address = partner.getAddress();` and there is no such property, instead there is a list of `Addresses` in the `Partner` entity

##### **Related issues**

I searched and found none.

##### **Suggest a Fix**
This was working previous to 6.x

##### **JHipster Version(s)**
I was failing in 6.0.1 and it's failing also in 6.1.0

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.almasoft.facturapp",
      "nativeLanguage": "es"
    },
    "jhipsterVersion": "6.1.0",
    "applicationType": "monolith",
    "baseName": "FacturApp",
    "packageName": "com.almasoft.facturapp",
    "packageFolder": "com/almasoft/facturapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "mariadb",
    "prodDatabaseType": "mariadb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "rememberMeKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "clientFramework": "angularX",
    "clientTheme": "spacelab",
    "clientThemeVariant": "light",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "es",
    "languages": ["es"]
  }
}

</pre>
</details>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>Address.json</summary>
<pre>
{
    "name": "Address",
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "contact",
            "fieldType": "String"
        },
        {
            "fieldName": "mobile",
            "fieldType": "String"
        },
        {
            "fieldName": "address",
            "fieldType": "String"
        },
        {
            "fieldName": "note",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "text"
        },
        {
            "fieldName": "delivery",
            "fieldType": "Boolean"
        },
        {
            "fieldName": "invoicing",
            "fieldType": "Boolean"
        },
        {
            "fieldName": "active",
            "fieldType": "Boolean"
        }
    ],
    "relationships": [
        {
            "relationshipType": "one-to-many",
            "otherEntityName": "invoice",
            "otherEntityRelationshipName": "address",
            "relationshipName": "invoice"
        },
        {
            "relationshipType": "one-to-many",
            "otherEntityName": "quote",
            "otherEntityRelationshipName": "address",
            "relationshipName": "quote"
        },
        {
            "relationshipType": "one-to-many",
            "otherEntityName": "saleOrder",
            "otherEntityRelationshipName": "address",
            "relationshipName": "saleOrder"
        },
        {
            "relationshipType": "one-to-many",
            "otherEntityName": "creditNote",
            "otherEntityRelationshipName": "address",
            "relationshipName": "creditNote"
        },
        {
            "relationshipType": "many-to-one",
            "otherEntityName": "district",
            "otherEntityRelationshipName": "address",
            "relationshipName": "district",
            "otherEntityField": "name"
        },
        {
            "relationshipType": "many-to-one",
            "otherEntityName": "partner",
            "otherEntityRelationshipName": "address",
            "relationshipName": "partner",
            "otherEntityField": "name"
        }
    ],
    "changelogDate": "20190612160623",
    "entityTableName": "address",
    "dto": "mapstruct",
    "pagination": "pagination",
    "service": "serviceImpl",
    "jpaMetamodelFiltering": true,
    "fluentMethods": true,
    "clientRootFolder": "",
    "applications": "*"
}
</pre>
</details>

<details>
<summary>Address.json</summary>
<pre>
{
    "name": "Partner",
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "title",
            "fieldType": "PartnerTitle",
            "fieldValues": "MISS,MRS,MISTER,DOCTOR,MAGISTER,LICENCIADO,PROFESSOR"
        },
        {
            "fieldName": "phone",
            "fieldType": "String"
        },
        {
            "fieldName": "mobile",
            "fieldType": "String"
        },
        {
            "fieldName": "email",
            "fieldType": "String"
        },
        {
            "fieldName": "avatar",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image"
        },
        {
            "fieldName": "birthday",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "active",
            "fieldType": "Boolean",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "comment",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "text"
        },
        {
            "fieldName": "contactName",
            "fieldType": "String"
        },
        {
            "fieldName": "organizationName",
            "fieldType": "String"
        },
        {
            "fieldName": "individual",
            "fieldType": "Boolean"
        },
        {
            "fieldName": "supplier",
            "fieldType": "Boolean"
        },
        {
            "fieldName": "customer",
            "fieldType": "Boolean"
        },
        {
            "fieldName": "documentType",
            "fieldType": "DocumentType",
            "fieldValues": "RUC,DNI,CE,PASSPORT"
        },
        {
            "fieldName": "documentNumber",
            "fieldType": "String"
        },
        {
            "fieldName": "employee",
            "fieldType": "Boolean"
        }
    ],
    "relationships": [
        {
            "relationshipType": "one-to-many",
            "otherEntityName": "product",
            "otherEntityRelationshipName": "supplier",
            "relationshipName": "product"
        },
        {
            "relationshipType": "one-to-many",
            "otherEntityName": "address",
            "otherEntityRelationshipName": "partner",
            "relationshipValidateRules": "required",
            "relationshipName": "address"
        },
        {
            "relationshipType": "one-to-many",
            "otherEntityName": "partner",
            "otherEntityRelationshipName": "parent",
            "relationshipName": "child"
        },
        {
            "relationshipType": "one-to-many",
            "otherEntityName": "invoice",
            "otherEntityRelationshipName": "customer",
            "relationshipName": "invoice"
        },
        {
            "relationshipType": "one-to-many",
            "otherEntityName": "quote",
            "otherEntityRelationshipName": "customer",
            "relationshipName": "quote"
        },
        {
            "relationshipType": "one-to-many",
            "otherEntityName": "saleOrder",
            "otherEntityRelationshipName": "customer",
            "relationshipName": "saleOrder"
        },
        {
            "relationshipType": "one-to-many",
            "otherEntityName": "creditNote",
            "otherEntityRelationshipName": "customer",
            "relationshipName": "creditNote"
        },
        {
            "relationshipType": "one-to-many",
            "otherEntityName": "purchaseOrder",
            "otherEntityRelationshipName": "customer",
            "relationshipName": "purchaseOrder"
        },
        {
            "relationshipType": "one-to-many",
            "otherEntityName": "purchaseInvoice",
            "otherEntityRelationshipName": "customer",
            "relationshipName": "purchaseInvoice"
        },
        {
            "relationshipType": "one-to-many",
            "otherEntityName": "itemComment",
            "otherEntityRelationshipName": "partner",
            "relationshipName": "comments"
        },
        {
            "relationshipType": "one-to-many",
            "otherEntityName": "bankAccount",
            "otherEntityRelationshipName": "customer",
            "relationshipName": "bankAccount"
        },
        {
            "relationshipType": "one-to-many",
            "otherEntityName": "manufacturingOrder",
            "otherEntityRelationshipName": "partner",
            "relationshipName": "manufacturingOrder"
        },
        {
            "relationshipType": "many-to-one",
            "otherEntityName": "partner",
            "otherEntityRelationshipName": "child",
            "relationshipName": "parent",
            "otherEntityField": "name"
        },
        {
            "relationshipType": "many-to-one",
            "otherEntityName": "company",
            "otherEntityRelationshipName": "partners",
            "relationshipName": "company",
            "otherEntityField": "name"
        },
        {
            "relationshipType": "many-to-one",
            "otherEntityName": "district",
            "otherEntityRelationshipName": "partner",
            "relationshipName": "district",
            "otherEntityField": "name"
        },
        {
            "relationshipType": "many-to-one",
            "otherEntityName": "paymentTerm",
            "otherEntityRelationshipName": "paymentPartners",
            "relationshipName": "preferredPaymentTerm",
            "otherEntityField": "name"
        },
        {
            "relationshipType": "many-to-one",
            "otherEntityName": "paymentTerm",
            "otherEntityRelationshipName": "collectorPartners",
            "relationshipName": "preferredCollectionTerm",
            "otherEntityField": "name"
        }
    ],
    "changelogDate": "20190612160621",
    "entityTableName": "partner",
    "dto": "mapstruct",
    "pagination": "pagination",
    "service": "serviceImpl",
    "jpaMetamodelFiltering": true,
    "fluentMethods": true,
    "clientRootFolder": "",
    "applications": "*"
}
</pre>
</details>
##### **Browsers and Operating System**
Not relevant

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
The provided JDL wasn't working, I corrected it:
```
entity Partner {
    name String required,
    phone String,
    mobile String,
    email String,
    avatar ImageBlob,
    birthday LocalDate,
    active Boolean required,
    comment TextBlob,
    contactName String,
    organizationName String,
    individual Boolean,
    supplier Boolean,
    customer Boolean,
    documentNumber String,
    employee Boolean
}
entity Address {
    name String required
    contact String
    mobile String
    address String
    note TextBlob
    delivery Boolean
    invoicing Boolean
    active Boolean
}
relationship OneToMany {
    Partner{address(name) required} to Address{partner(name)}
}

**Comment by jdubois** [comment]
Sorry, with this JDL, on the latest version, it works without any issue, so I'm closing.

**Comment by amatosg** [comment]
@jdubois question, what was the correction you made? I can't find the difference. Thank you!

**Comment by jdubois** [comment]
@amatosg you had stuff like `title PartnerTitle` which couldn't work, as you only gave a part of your JDL

**Comment by amatosg** [comment]
@jdubois Oh, I see, there are 2 enum class. Every time I regenerate I get an error on the test for that particular class and the class `Address` only has relationship with `Partner`.
```
enum PartnerTitle{
    MISS,
    MRS,
    MISTER,
    DOCTOR,
    MAGISTER,
    LICENCIADO,
    PROFESSOR
}

enum DocumentType{
    RUC,
    DNI,
    CE,
    PASSPORT,
    DIPLOMATIC,
    EXPORT,
    OTHER
}
```
