### ISSUE TITLE
configure GZipServletFilter to compress files of type *.svg and *.ttf files

### ISSUE THREAD

**Issue by andidev** [jhipster/generator-jhipster#991]
As brought up in #978, it seems that some font file types could gain from being compressed by the GZipServletFilter.

Therefore the *.svg and *.ttf url patterns should be added to the GZipServletFilter.

referense
http://zoompf.com/blog/2014/08/bootstrap-fonts

**Comment by andidev** [comment]
Also not a big thing but the docs says that the GZipServletFilter only compresses resources if running the application in production mode. This is not true. It does it in development mode as well.

**Comment by jdubois** [comment]
@andidev thanks that's an issue for me -> I will check the dev mode
