### ISSUE TITLE
Generate importMappings with zalando problem class when using API first development

### ISSUE THREAD

**Issue by mikhail-putilov** [jhipster/generator-jhipster#9911]
##### **Overview of the feature request**

When users try to use Zalando Problem library in theirs `api.yml`:
```
responses:
  default:
    description: error occurred - see status code and problem object for more information.
    content:
      "application/problem+json":
        schema:
          $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
```
And run `mvn generate-sources`, maven plugin `openapi-generator-maven-plugin` generates unneseccary java class `Problem` eventhough `org.zalando.Problem` is already presented in classpath in `org.zalando.problem:problem` jar.

##### **Motivation for or Use Case**

Normally, it is expected from a user perspective to reuse existing classes in classpath. 
Consider adding `<importMappings>Problem=org.zalando.problem.Problem</importMappings>` inside `<configuration>` tag in `pom.xml`, please. It would fix the thing.

Thank you in advance!

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
Good point, having open api generate zalando problem class is really annoying.

**Comment by atomfrede** [comment]
Going to work on that and on updating open api plugins to the latest version.
