### ISSUE TITLE
Cannot generate entities with jhipster import-jdl command

### ISSUE THREAD

**Issue by gyunus** [jhipster/generator-jhipster#9912]
##### **Overview of the issue**

Using JHipster 6.0.1 generator, i cannot generate entities with my JDL file.

##### **Motivation for or Use Case**

I am working on a new project based on the microservices architecture in my company and we have chosen jhipster as project generator. We could have generated the project successfully but we are facing a big problem while generating entities related to the project. 
We used jhipster tutorials on the jhipster official webpage but generating entities with a JDL file can not generate entities. 

##### **Reproduce the error**

We are using the following command and JDL file to generate entities. 

`jhipster import-jdl app.jdl.jh`

app.jdl.jh

> /* Entities for Annexe microservice */
entity Annexe {
	lignefacturation String
	datedebut Instant
	datefin Instant
	prixunitaire Double 
	quantite Integer
	montantht Double 
	nombrecoinvestisseurs Integer
	typecommandeacces String 
	codeinsee String 
	typedezone String 
	referencepm String 
	datecrmadpm Instant
	logementscouverts Integer
	logementsraccordables Integer
	refcofinancement String 
	coefexpost Double 
	referencecommande String 
	typefacturation String 
	typeingenierie Ingenierie
	emplacementpm String 
	pmcategory String 
	typeacces String 
	nombreoperateursdedie Integer
	nombreoperateurspartage Integer
	motifcontestation String
}
enum Ingenierie {
 QUADRI,BI
}
service Annexe with serviceClass
paginate Annexe with pagination
microservice Annexe with backend

`jhipster entity Annexe` works fine

Results - FAIL: 

> PS C:\Certif_OWF\certif_backend> jhipster import-jdl app.jdl.jh --debug
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Debug logging is on
DEBUG!  Executing CLI only script
DEBUG!  cmd: import-jdl from ./import-jdl
DEBUG!  args: app.jdl.jh, commands: Object, options: Object, _execs: Object, _allowUnknownOption: true, _args: Object, _
name: import-jdl, _noHelp: false, parent: Object, _description: Create entities from the JDL file passed in argument.
  By default everything is run in parallel. If you like to interact with the console use '--interactive' flag., _argsDes
cription: undefined, _events: Object, _eventsCount: 1
INFO! Executing import-jdl app.jdl.jh
INFO! Options: debug: true, from-cli: true
DEBUG!  JDLProcessor started with jdlFiles: app.jdl.jh and options: debug: true, from-cli: true
INFO! Found .yo-rc.json on path. This is an existing app
INFO! The JDL is being parsed.
DEBUG!  importState exportedEntities: 0
DEBUG!  importState exportedApplications: 0
DEBUG!  importState exportedDeployments: 0
INFO! No change in entity configurations, no entities were updated.
INFO! The JDL has been successfully parsed
DEBUG!  Applications not generated
DEBUG!  Entities not generated
DEBUG!  Deployments not generated

##### **JHipster Version(s)**

```
certifbackend@0.0.0 C:\Certif_OWF\certif_backend
`-- generator-jhipster@6.0.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.owf.certification"
    },
    "jhipsterVersion": "6.0.1",
    "applicationType": "microservice",
    "baseName": "certifbackend",
    "packageName": "com.owf.certification",
    "packageFolder": "com/owf/certification",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "clientPackageManager": "npm",
    "skipClient": true,
    "skipUserManagement": true,
    "languages": [
      "en",
      "fr"
    ],
    "nativeLanguage": "en"
  },
  "entities": []
}
</pre>
</details>
##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json
<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)

git version 2.21.0.windows.1

node: v10.15.3

npm: 6.4.1

Docker version 18.03.0-ce, build 0520e24302

docker-compose version 1.20.1, build 5d8c71b2

INFO! Congratulations, JHipster execution is complete!

**Comment by kaidohallik** [comment]
In `.yo-rc.json` microservice name is `certifbackend` but in `app.jdl.jh` it is `backend`.  
Use
```
microservice Annexe with certifbackend
```
in JDL file.
