### ISSUE TITLE
Frontend Enums should be global

### ISSUE THREAD

**Issue by amatosg** [jhipster/generator-jhipster#9920]
##### **Overview of the feature request**
If I have this:
```
enum CommonFieldValues{
    A, B, C, D
}

entity Something {
    commonFieldValue CommonFieldValues
}

entity OtherEntity {
    commonFieldValue CommonFieldValues
}
```

Then the enum `CommonFieldValues` will be created twice, once in the class in their respective model.

As it is an enum used in different classes with the exact same values, this should be handled the same way is being done in the backend.

##### **Motivation for or Use Case**
There are times when I need to compare the same enum from 2 classes and it doesn't work as they are treated as different enums.

Plus, this will reduce the amount of code :)
##### **Related issues or PR**

None

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
Agree we should reduce duplicate code here

**Comment by clement26695** [comment]
Bounty claimed at https://opencollective.com/generator-jhipster/expenses/9436

**Comment by amatosg** [comment]
thank you @clement26695!
