### ISSUE TITLE
Enhanced CRUD

### ISSUE THREAD

**Issue by 0loky0** [jhipster/generator-jhipster#993]
Bonjour, 

Super boulot :)

Après quelques tests et plusieurs visionnage de diverses tutos/présentations. 
Il me semblerait intéressant de disposer (peut-être en option) dans le CRUD de : 
- la pagination 
- critères de recherche dans le tableau

Je sais que l'absence de ng-table est voulu mais ce qui est produit me semble un peu just ... 
Et cela donnerait un bonne exemple du best practice en la matière :)

**Comment by jdubois** [comment]
Please write your questions in English
Of course I can read French, but this is for everybody to understand!
And yes you are correct, those are 2 things we should do, but they are out of scope now, for lack of time
This might be our v3 version
