### ISSUE TITLE
Using the JDL, "cacheProvider no" doesn't work with the default Hibernate configuration

### ISSUE THREAD

**Issue by anthony-o** [jhipster/generator-jhipster#9933]
##### **Overview of the issue**

We are currently unable to use the option `cacheProvider` with value `no`.

When using such an option, here is the result in the console when launching `./mvnw`:

    ***************************
    APPLICATION FAILED TO START
    ***************************

    Description:

    Parameter 1 of constructor in com.mycompany.myproject.config.LiquibaseConfiguration required a bean of type 'org.springframework.cache.CacheManager' that could not be found.

    The following candidates were found but could not be injected:
	    - Bean method 'cacheManager' in 'CaffeineCacheConfiguration' not loaded because @ConditionalOnClass did not find required class 'com.github.benmanes.caffeine.cache.Caffeine'
	    - Bean method 'cacheManager' in 'EhCacheCacheConfiguration' not loaded because @ConditionalOnClass did not find required class 'net.sf.ehcache.Cache'
	    - Bean method 'cacheManager' in 'JCacheCacheConfiguration' not loaded because @ConditionalOnClass did not find required class 'javax.cache.Caching'

    Action:

    Consider revisiting the entries above or defining a bean of type 'org.springframework.cache.CacheManager' in your configuration.

##### **Motivation for or Use Case**

I think one could be able to don't use Hibernate second level cache for an application generated with JHipster.

##### **Reproduce the error**

```bash
cd /dev/shm/
mkdir myproject
cd myproject
mkdir /dev/shm/m2cache /dev/shm/yarncache
sudo tee myproject.jdl <<EOF
application {
    config {
        baseName MyProject
        cacheProvider no
        clientPackageManager yarn
        jhiPrefix mp
        enableTranslation false
        languages [fr]
        nativeLanguage fr
        packageName com.mycompany.myproject
        prodDatabaseType postgresql
        skipUserManagement false
        testFrameworks [cucumber]
    }
    entities *
}

entity MyEntity {
    myField String
}
EOF
sudo chown -R 1000:1000 . /dev/shm/m2cache /dev/shm/yarncache
docker run -it --rm --name jhipster -v "$(pwd):/home/jhipster/app" -v /dev/shm/m2cache:/home/jhipster/.m2 -v /dev/shm/yarncache:/home/jhipster/.cache/yarn -v "$HOME/.gitconfig:/home/jhipster/.gitconfig:ro" jhipster/jhipster:v6.1.0 jhipster import-jdl ./myproject.jdl --force

docker run -it --rm --name jhipster -v "$(pwd):/home/jhipster/app" -v /dev/shm/m2cache:/home/jhipster/.m2 -v /dev/shm/yarncache:/home/jhipster/.cache/yarn jhipster/jhipster:v6.1.0 ./mvnw
```

##### **JHipster Version(s)**

```
my-project@0.0.0 /home/jhipster/app
`-- generator-jhipster@6.1.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": false,
    "jhiPrefix": "mp",
    "languages": ["fr"],
    "messageBroker": false,
    "nativeLanguage": "fr",
    "packageName": "com.mycompany.myproject",
    "packageFolder": "com/mycompany/myproject",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "serviceDiscoveryType": false,
    "skipClient": false,
    "skipServer": false,
    "testFrameworks": ["cucumber"],
    "websocket": false,
    "baseName": "MyProject",
    "cacheProvider": "no",
    "clientPackageManager": "yarn",
    "skipUserManagement": false,
    "jhipsterVersion": "6.1.0",
    "buildTool": "maven",
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "clientFramework": "angularX",
    "serverPort": "8080",
    "useSass": true,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "clientTheme": "none",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": []
  },
  "entities": ["MyEntity"]
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity MyEntity {
  myField String
}

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu218.04.1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu218.04.1, mixed mode, sharing)

git version 2.17.1

node: v10.16.0

npm: 6.9.0

yeoman: 2.0.6

yarn: 1.16.0

##### **Browsers and Operating System**

Using Ubuntu 18.04 LTS with Firefox

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
This is very important so I'm adding a bug bounty, but I think it might be more complicated as I'm doing this all the time and never had such an issue.

**Comment by jdubois** [comment]
@anthony-o this is because you have `enableHibernateCache false` missing in your JDL.
I'm not sure this can/should be done in the JDL... The reason is that this is "true" by default, but if you have an Hibernate cache and then no cache configured, this isn't going to work. On the command line we can help people, so they don't provide non-consistent options, it's more difficult with the JDL.

I'm not sure what we can do here... @deepu105 I think you're the boss of this part?

I'm removing the bug bounty as it's not really worth it.

**Comment by jdubois** [comment]
I updated the title so it's less stressful :-)

**Comment by deepu105** [comment]
Yes, enableHibernateCache needs to be set in JDL. There is already support
for this. Let me see if we can set it to false automatically when cache is
not selected

**Comment by anthony-o** [comment]
@jdubois thank you for the analyze, I didn't see the `enableHibernateCache` option.
Anyway, do we agree that even with `enableHibernateCache` set to `false` and `cacheProvider`, classical Hibernate L1 cache will continue to work?
From what I can read [here](https://howtodoinjava.com/hibernate/understanding-hibernate-first-level-cache-with-example/), [here](https://discourse.hibernate.org/t/how-to-disable-the-first-level-cache-with-jpa-and-hibernate/1926/2) or [here](https://stackoverflow.com/a/3829097/535203), this L1 cache cannot be disabled...

**Comment by jdubois** [comment]
@anthony-o L1 cache will always work, that's the way Hibernate work, no problem at all!
