### ISSUE TITLE
Gulp + Production mode does not work

### ISSUE THREAD

**Issue by ctranxuan** [jhipster/generator-jhipster#994]
Hello,
A project generated with JHipster 2.0.0 with Gulp as js build manager and maven as java build manager does not work with the production mode.

Here are the steps to reproduce:
* create a project with jhipster-generator 2.0.0 (choose the default options except for the js build manager: choose Gulp): yo jhipster
* run: mvn -Pprod  package
* run: java -jar target/jhipster-0.0.1-SNAPSHOT.war --spring.profiles.active=prod
* open a browser, you get a almost blank page (only the footer is displayed): see screenshot in attachment

When opening the js console, we get some js errors:
```javascript
 GET http://localhost:8080/scripts/components/navbar/navbar.html 404 (Not Found)
vendor-188cadec.js:6 
GET http://localhost:8080/scripts/app/main/main.html 404 (Not Found)
```
![screenshot from 2015-01-16 16 40 34](https://cloud.githubusercontent.com/assets/816144/5778927/0d9335fc-9d9f-11e4-815a-29fc4f74912c.png)

Tested on Chrome Version 39.0.2171.99 (64-bit) and Firefox 35.0 Mozilla Firefox for Ubuntu canonical - 1.0

There is no issue when choosing Grunt instead of Gulp.
If ever you need more details, feel free to contact me.

Cheers,

Cédric.

**Comment by amr** [comment]
Confirmed, thanks for reporting it. I submitted a PR with a fix.
