### ISSUE TITLE
Jhipster prod Error pl.project13.maven

### ISSUE THREAD

**Issue by mabliedana** [jhipster/generator-jhipster#9944]
##### **Overview of the issue**
In prod packaging, compilation failed due to this issue:
[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.2.6:revision (default) on project test: Could not complete Mojo execution...: Error: Could not get HEAD Ref, are you sure you have some commits in the dotGitDirectory? -> [Help 1]

##### **Motivation for or Use Case**
Generation of production war 

##### **Reproduce the error**

jhipster
./mvnw clean package -Pprod -DskipTests 
Then it does not finish the compilation and .war generation

##### **Related issues**

#8705 was closed due to lack of informacion

##### **Suggest a Fix**

It seems to be solved by adding in the pom.xml the properties `<failOnUnableToExtractRepoInfo>false</failOnUnableToExtractRepoInfo>` under pl.project13.maven plugin 

##### **JHipster Version(s)**

6.1.0

##### **JHipster configuration**

JHipster configuration, a .yo-rc.json file generated in the root folder
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.1.0",
    "applicationType": "monolith",
    "baseName": "test",
```
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "YjA0YjFjMzc0NjU3MDcwZTllMWMxMjRiMzAzZGY3ODYyYTNhYWFiZmRhNGQ1MjkwY2NlODM3NDg0MjZjN2JlNGU3NDM1ZjdiNThlM2JhYjc0YjhkN2M0M2RmYTZjOGU5YWU2NGY5MGI4ZTY5MjYxZmU2NDZjNGE4ZTY2MjgyMjc=",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

No entities have been added

##### **Browsers and Operating System**

Environment and Tools

Machine
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial

Java
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.16.04.1-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)

git version 2.7.4

node: v10.16.0

npm: 6.9.0

yeoman: 2.0.6

yarn: 1.16.0

-   [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by DanielFran** [comment]
@mabliedana Do you wan't to contribute and make a PR?

**Comment by PierreBesson** [comment]
Yes, it is known that the build will fail if the git repository is initialized but no commit has been done. As this state is invalid and should not happen in the normal case. This error is normal and it seems a bit strange to work around it but anyway I guess we can add the line if it helps some users:`<failOnUnableToExtractRepoInfo>false</failOnUnableToExtractRepoInfo>`.
