### ISSUE TITLE
Resource server JWT => User mapping doesn't work with Okta

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#9946]
##### **Overview of the issue**

When using JHipster as a resource server (with OIDC authentication), the access token looks a lot different when coming from Okta than it does from Keycloak. 

**From Keycloak**

Access token:

```json
{
 "jti": "4753c06a-6fb9-4fcd-818e-710c4cf77533",
 "exp": 1560990185,
 "nbf": 0,
 "iat": 1560989885,
 "iss": "http://localhost:9080/auth/realms/jhipster",
 "aud": "account",
 "sub": "4c973896-5761-41fc-8217-07c5d13a004b",
 "typ": "Bearer",
 "azp": "web_app",
 "auth_time": 1560989884,
 "session_state": "ff746a9f-ac55-4ec6-bc75-e9b76cd7c9e6",
 "acr": "1",
 "allowed-origins": [
  "*"
 ],
 "realm_access": {
  "roles": [
   "ROLE_USER",
   "offline_access",
   "ROLE_ADMIN",
   "uma_authorization"
  ]
 },
 "resource_access": {
  "account": {
   "roles": [
    "manage-account",
    "manage-account-links",
    "view-profile"
   ]
  }
 },
 "scope": "openid jhipster email offline_access profile",
 "email_verified": true,
 "roles": [
  "ROLE_USER",
  "offline_access",
  "ROLE_ADMIN",
  "uma_authorization"
 ],
 "name": "Admin Administrator",
 "preferred_username": "admin",
 "given_name": "Admin",
 "family_name": "Administrator",
 "email": "admin@localhost"
}
```

**From Okta**

Access token:

```json
{
 "ver": 1,
 "jti": "AT.IaCEQIsduqRLJFCdVt8ud0tQmV2O7FO-4dxGMKmLPvI",
 "iss": "https://dev-133320.okta.com/oauth2/default",
 "aud": "api://default",
 "iat": 1560993383,
 "exp": 1560996983,
 "cid": "0oaqw04pluEd7HkWI356",
 "uid": "00ueblyxoowgcboNP356",
 "scp": [
  "openid",
  "profile"
 ],
 "sub": "demo@okta.com",
 "groups": [
  "Everyone",
  "ROLE_USER"
 ]
}
```

##### **Motivation for or Use Case**

When using Ionic + OIDC and JHipster, there's a 500 error when you log in with Okta. I believe it's because the user's email is null.

```
2019-06-19 19:09:01.500 ERROR 53117 --- [  XNIO-1 task-9] c.m.myapp.aop.logging.LoggingAspect      : Exception in com.mycompany.myapp.service.UserService.getUserFromAuthentication() with cause = 'NULL' and exception = 'null'

java.lang.NullPointerException: null
	at org.ehcache.jsr107.Eh107Cache.remove(Eh107Cache.java:224)
	at org.springframework.cache.jcache.JCacheCache.evict(JCacheCache.java:105)
	at com.mycompany.myapp.service.UserService.clearUserCaches(UserService.java:257)
	at com.mycompany.myapp.service.UserService.syncUserWithIdP(UserService.java:176)
	at com.mycompany.myapp.service.UserService.getUserFromAuthentication(UserService.java:207)
```

##### **Reproduce the error**

Create a JHipster app with OIDC, configure it for Okta. Create an Ionic 4 app and configure it for Okta. It's a long story, but I do have an upcoming blog post that shows how to do it!

##### **Related issues**

https://github.com/jhipster/generator-jhipster/pull/9905

##### **Suggest a Fix**

The easiest fix is likely to adjust the logic in UserService#getUser() to make sure there's an email address. In other words, use `uid` for the id and `sub` for the email when it's a `JwtAuthenticationToken`. 

<img width="1926" alt="Screen Shot 2019-06-19 at 7 13 01 PM" src="https://user-images.githubusercontent.com/17892/59811545-a1ab0e00-92c7-11e9-9494-af88a69fea17.png">

A better long-term fix would likely be to call the /userinfo endpoint to get all the user's information.

##### **JHipster Version(s)**

Current `master` branch as of a couple of hours ago.

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["en", "fr"],
    "messageBroker": false,
    "nativeLanguage": "en",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "serviceDiscoveryType": false,
    "skipClient": false,
    "skipServer": false,
    "testFrameworks": ["protractor"],
    "websocket": false,
    "baseName": "oauth2",
    "authenticationType": "oauth2",
    "buildTool": "gradle",
    "jhipsterVersion": "6.1.0",
    "skipUserManagement": true,
    "clientPackageManager": "npm",
    "applicationType": "monolith",
    "cacheProvider": "ehcache",
    "clientFramework": "angularX",
    "serverPort": "8080",
    "useSass": true,
    "clientTheme": "none",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": []
  },
  "entities": []
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Album {
  title String required,
  description TextBlob,
  created Instant
}
entity Photo {
  title String required,
  description TextBlob,
  image ImageBlob required,
  height Integer,
  width Integer,
  taken Instant,
  uploaded Instant
}
entity Tag {
  name String required minlength(2)
}
relationship ManyToOne {
  Album{user(login)} to User,
  Photo{album(title)} to Album
}
relationship ManyToMany {
  Photo{tag(name)} to Tag{photo}
}

paginate Album with pagination
paginate Photo, Tag with infinite-scroll

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

git version 2.20.1 (Apple Git-117)

node: v10.15.3

npm: 6.9.0

yeoman: 2.0.6

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

**Comment by mraible** [comment]
@ruddell Have you tested Ignite JHipster with JHipster 6.1.0 and Okta to see if you have similar issues? This happens because I call `/api/account` to see if the user is authenticated. Previously, I fetched the user's info from the `/userinfo` endpoint on the client. I could switch back to that, but it's probably better to solve on the server-side.

**Comment by vishal423** [comment]
@mraible, If this issue is due to email claims not being populated, then, can we ask for `email` scope? I don't see that scope in the okta's JWT token response.

**Comment by mraible** [comment]
@vishal423 I tried changing my Ionic app to send `openid email profile` for scopes (instead of `openid profile offline_access`). It doesn't result in an email being in the access token.

```json
{
 "ver": 1,
 "jti": "AT.B48F2yg_fDaxbqU6nwoJousRp19iQ012qxJ_S7OZs9s",
 "iss": "https://dev-133320.okta.com/oauth2/default",
 "aud": "api://default",
 "iat": 1561022356,
 "exp": 1561025956,
 "cid": "0oaqw04pluEd7HkWI356",
 "uid": "00ueblyxoowgcboNP356",
 "scp": [
  "profile",
  "openid",
  "email"
 ],
 "sub": "demo@okta.com",
 "groups": [
  "Everyone",
  "ROLE_USER"
 ],
 "given_name": "Okta",
 "family_name": "Demo"
}
```
