### ISSUE TITLE
Refresh problem on a jhipster project

### ISSUE THREAD

**Issue by cmennevret** [jhipster/generator-jhipster#9948]
hello I have a problem with a project generated under Jhipster
I can not refresh the project when saving code or f5 if my page is "localHost:9000/example" the page breaks.
 I am forced to relaunch the "localhost: 9000".

And I do not know where the problem comes from or how to solve it (it's very difficult for coding because I have to restart each time)

Thank you for your answers

**Comment by jdubois** [comment]
Thanks, but you really provide no information at all: your OS, your browser, how you start JHipster, etc... I'm sorry but we can't help you like that, could you please follow our contribution guidelines?

**Comment by cmennevret** [comment]
I am on windows 10, I use chrome google and I start jhipster with the command "npm run start"
it starts well on "localhost: 9000" the problem is that when I make a change in the code if the site and "localhost: 9000/example" the page breaks and puts:
" Your request can not be processed 
Sorry, an error has occurred.

Status: Not Found (Not Found)
Message: Not Found
Other things to try:
Search localhost: 9000:"

and I have to restart the "localhost: 9000"

I do not know where the problem comes from or how to fix it

**Comment by ruddell** [comment]
Without the information from the template and instructions to reproduce, we can't really help.

Sounds like it is related to https://github.com/jhipster/generator-jhipster/issues/9839 (PR fixing that is https://github.com/jhipster/generator-jhipster/pull/9860)

**Comment by pascalgrimaud** [comment]
I think @ruddell is right. So let's close this.
