### ISSUE TITLE
Unable to login after token expires in v1.10.2, "prod" only.

### ISSUE THREAD

**Issue by flythebluesky** [jhipster/generator-jhipster#995]
Recreate: Create new jhipster app as per .yo-rc.json below. Log in and let the token expire. After token expiry, the expired token is still present in local browser storage, and attempts to open up the login view fails with 401 unauthorized error. The main view is also not displayed. 

For the recreation, I installed H2 in the "prod" profile, and upgraded Liquibase to 3.2.3. to sidestep a Liquibase exception. 

Recreation code: https://github.com/flythebluesky/jhipster-token-bug-recreate/commit/52c6b74ea92c2e7c91d3397b0baa634792bf9469

```
java -jar build/libs/hipstertoken-0.1-SNAPSHOT.war --spring.profiles.active=prod 
```
(prod uses port 9090 localhost:9090)

It does not fail with spring.profiles.active=dev

Subsequent attempts to access resources result in http 401 response {"error":"invalid_token","error_description":"Invalid access token: 9e4f183d-3a2e-4aea-a011-04c0d4101dc8"}, even if that resource is unprotected (e.g. /#/login). 

To clear the problem, the token must be deleted manually from the browser storage.
If this is a new issue, I would appreciate any pointers to try and debug this.

```
{
  "generator-jhipster": {
    "baseName": "hipstertoken",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "authenticationType": "token",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "hazelcast",
    "websocket": "atmosphere",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "useCompass": true,
    "buildTool": "gradle",
    "frontendBuilder": "gulp",
    "javaVersion": "8"
  }
}
```

```
Remote Address:127.0.0.1:9090
Request URL:http://localhost:9090/views/main.html
Request Method:GET
Status Code:401 Unauthorized
Request Headersview source
Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Authorization:Bearer 31f23b62-765c-4b71-bb66-ef26dec41498
Cache-Control:max-age=0
Connection:keep-alive
Cookie:vocotrax=rgo; _ga=GA1.1.1952220718.1420663843; NG_TRANSLATE_LANG_KEY=%22en%22; tmhDynamicLocale.locale=%22en%22; hazelcast.sessionId=HZ7E7D619346E848EA9B563D0E29577CD0; JSESSIONID=p31vzbzi4zsmwyedrrfrj6vd
Host:localhost:9090
If-Modified-Since:Thu, 15 Jan 2015 15:04:52 GMT
Referer:http://localhost:9090/
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36
Response Headersview source
Cache-Control:no-store
Content-Type:application/json;charset=UTF-8
Date:Thu, 15 Jan 2015 22:03:48 GMT
Pragma:no-cache
Server:Apache-Coyote/1.1
Transfer-Encoding:chunked
WWW-Authenticate:Bearer realm="oauth", error="invalid_token", error_description="Invalid access token: 31f23b62-765c-4b71-bb66-ef26dec41498"
X-Application-Context:application:prod:9090
```

**Comment by flythebluesky** [comment]
This problem only occurs when the static resources filter is enabled for the /view/*.html files in production (this is not enabled in the dev env). 

Comment out the line as shown below to avoid the problem. With that line commented out, the server does not return a 401 unauthorized for the view. It's unclear to me why a 401 would occur because the view directory is excluded from Spring security (see SecurityConfiguration.java).

WebConfigurer.java: 

```java
    private void initStaticResourcesProductionFilter(ServletContext servletContext,
                                                     EnumSet<DispatcherType> disps) {

        log.debug("Registering static resources production Filter");
        FilterRegistration.Dynamic staticResourcesProductionFilter =
                servletContext.addFilter("staticResourcesProductionFilter",
                        new StaticResourcesProductionFilter());

        staticResourcesProductionFilter.addMappingForUrlPatterns(disps, true, "/");
        staticResourcesProductionFilter.addMappingForUrlPatterns(disps, true, "/index.html");
        staticResourcesProductionFilter.addMappingForUrlPatterns(disps, true, "/images/*");
        staticResourcesProductionFilter.addMappingForUrlPatterns(disps, true, "/fonts/*");
        staticResourcesProductionFilter.addMappingForUrlPatterns(disps, true, "/scripts/*");
        staticResourcesProductionFilter.addMappingForUrlPatterns(disps, true, "/styles/*");
        // staticResourcesProductionFilter.addMappingForUrlPatterns(disps, true, "/views/*");
        staticResourcesProductionFilter.setAsyncSupported(true);
    }
```

**Comment by flythebluesky** [comment]
Who is running JHipster in production mode? If so, have you seen this bug?

**Comment by Avricot** [comment]
We are running in prod (www.lapetitetranche.fr) and had some -strange- issue with token expiration on server restart. see https://github.com/jhipster/generator-jhipster/issues/906
I don't know if it's the same issue, do you have something on your server logs ?

**Comment by flythebluesky** [comment]
No server logs.
If the problem is resolved by deleting "token" in browser storage, then
it's probably the same issue.

**Comment by jdubois** [comment]
As this was with v1, did you try with v2 ?
Do you still have the issue?

**Comment by jdubois** [comment]
Should be corrected by https://github.com/jhipster/generator-jhipster/commit/1ed6ca3dee889729b132cc0656d25e64f852fa17

**Comment by hooligan495** [comment]
hey.  I'm using an older version of Jhipster and seeing this issue (1.x timeframe) it still has the http-auth-interceptor.  Is there a way to simply apply this patch to that?  (I need it for a demo then I need to start the upgrade path :) )

**Comment by deepu105** [comment]
Dude thats too old a version. @jdubois any idea about this?

**Comment by hooligan495** [comment]
I know... I need to fix it for a demo... then we are upgrading.  :P

**Comment by hooligan495** [comment]
Is there at least a set of commits I could follow to upgrade parts of my app to the oauth scheme of today without upgrading everything?

**Comment by deepu105** [comment]
Dude its a really old version and no one would remember that far, you can
always go and check a files git history and track yourself

**Comment by hooligan495** [comment]
I'll see what I can do.



On Tue, Sep 1, 2015 at 9:46 PM, Deepu k Sasidharan <notifications@github.com
> wrote:

> Dude its a really old version and no one would remember that far, you can
> always go and check a files git history and track yourself

**Comment by khouloudkhadija** [comment]
Hi  guys , I generate an application with jhipster generator and when I tried to run this application the execution was successful and without error but the display of the application was strange and when I inspect the home page of the application I got this error : "the server responded with a status of 401 (Unauthorized)"

**Comment by deepu105** [comment]
Plz dont post on old closed issues, open a new ticket following our issue template if you have any issue

**Comment by khouloudkhadija** [comment]
ok i'm sorry
