### ISSUE TITLE
user by email inconsistent ignore case

### ISSUE THREAD

**Issue by kaidohallik** [jhipster/generator-jhipster#9950]
##### **Overview of the issue**

In UserRepository.java:
* finding user by email without authorities is case insensitive: 
    * https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/repository/UserRepository.java.ejs#L143
    * https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/repository/UserRepository.java.ejs#L350
* finding user by email with authorities is case sensitive: https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/repository/UserRepository.java.ejs#L175

I think correct approach is to use case insensitive in both cases.

##### **Motivation for or Use Case**

Finding user with or without authorities should behave similarly.

##### **Suggest a Fix**

In files
* https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/repository/UserRepository.java.ejs
* https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/security/DomainUserDetailsService.java.ejs

change
```
findOneWithAuthoritiesByEmail
```
to
```
findOneWithAuthoritiesByEmailIgnoreCase
```

Change test in https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/test/java/package/security/DomainUserDetailsServiceIT.java.ejs from
```
    public void assertThatUserCanNotBeFoundByEmailIgnoreCase() {
        assertThatExceptionOfType(UsernameNotFoundException.class).isThrownBy(
            () -> domainUserDetailsService.loadUserByUsername(USER_TWO_EMAIL.toUpperCase(Locale.ENGLISH)));
    }
```
to
```
    public void assertThatUserCanBeFoundByEmailIgnoreCase() {
        UserDetails userDetails = domainUserDetailsService.<% if (reactive) { %>find<% } else { %>loadUser<% } %>ByUsername(USER_TWO_EMAIL.toUpperCase(Locale.ENGLISH))<% if (reactive) { %>.block()<% } %>;
        assertThat(userDetails).isNotNull();
        assertThat(userDetails.getUsername()).isEqualTo(USER_TWO_LOGIN);
    }
```

##### **JHipster Version(s)**

```
jhipster@0.0.0 C:\projects\teest\jhipster
`-- generator-jhipster@6.1.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "et"
    },
    "jhipsterVersion": "6.1.0",
    "applicationType": "monolith",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "et",
    "languages": ["et"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)

git version 2.21.0.windows.1

node: v10.15.3

npm: 6.9.0

yeoman: 2.0.6

yarn: 1.15.2

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
Looks good to me, would you like to submit a pull request?

**Comment by kaidohallik** [comment]
I made PR #9962
