### ISSUE TITLE
jhipster command blocks on application/project name prompt

### ISSUE THREAD

**Issue by pvliss** [jhipster/generator-jhipster#9952]
##### **Overview of the issue**
Not able to create a new JHipster application using just the prompts

##### **Motivation for or Use Case**
Should be able to create JHipster application using just the prompts

##### **Reproduce the error**
1. `npm install -g generator-jhipster`
2. `mkdir temp && cd temp`
3. `jhipster`
4. Select an app type. For me it does not matter
5. App is now blocked at the app name question.

##### **Related issues**
https://github.com/jhipster/jhipster-kotlin/issues/149

##### **JHipster Version(s)**
6.0.1
6.1.0

##### **JHipster configuration**
INFO! Using JHipster version installed globally
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
/home/pav/Development/temp/jhipster-java/temp
└── (empty)

```

cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

git version 2.17.1

node: v10.15.2

npm: 6.9.0

yeoman: 2.0.5

yarn: 1.16.0

Docker version 18.09.6, build 481bc77

docker-compose version 1.23.2, build 1110ad01

##### **Operating System**
Ubuntu 18.04.2 LTS

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
With @PierreBesson, we confirm the issue.

I managed to reproduce the issue, using https://github.com/jhipster/jhipster-guides
I'm putting a bounty on this, as it is an important bug !

We need to do a release after finding the fix. It probably comes from a transitive dependencies, as usual

**Comment by pascalgrimaud** [comment]
cc @jdubois @deepu105 @jhipster/developers  -> I'm afraid without a fix, we won't be able to do demo
We really need to find a fix and release

**Comment by jdubois** [comment]
What a mess NPM is!
Yes let's do a release after that

**Comment by PierreBesson** [comment]
I think the solution might involve publishing a new version with a [shrinkwrap.json file] (https://docs.npmjs.com/files/shrinkwrap.json) to fix the correct version of the transitive dependency. But first we need to find the dependency that is causing the app to hang.

**Comment by vishal423** [comment]
I use `yarn` and don't see this issue. Is this specific to `npm` ?

**Comment by pascalgrimaud** [comment]
I'm pretty sure it comes from a transitive dependencies.
I switched to v6.1.0 tag
- `npm ci` : no problem, it works fine
- I deleted `package-lock.json` and  `node_modules`, then `npm install` -> the `package-lock.json` has changed and it's broken

**Comment by PierreBesson** [comment]
I have found the bad dependency: https://github.com/SBoudrias/Inquirer.js/issues/811

**Comment by jdubois** [comment]
Awesome work @PierreBesson ! The good news is that @SBoudrias is a friend and an excellent coder, so this time to bug should be solved easily!!

**Comment by pvliss** [comment]
Congrats @PierreBesson!!! Would really be interested to know what's your process for finding node/npm these issues

**Comment by amatosg** [comment]
it looks like this should solve the issue https://github.com/slhck/vue-cli/commit/fdf602827e6aa57367f6bdea37b517755bc7ba5c

**Comment by jdubois** [comment]
@amatosg no unfortunately it's a transitive dependency

**Comment by PierreBesson** [comment]
My process was to look at the diff between a newly generated package lock and the one from the 6.1.0 release. Then I searched among the transitively updated packages which one had a recent npm release (manually). Then I expected that people must have already opened an issue on the GitHub project.

**Comment by pvliss** [comment]
@PierreBesson That makes sense. Thanks a lot!!!

**Comment by PierreBesson** [comment]
@jdubois I think that we should give the bounty money to the Yeoman open collective: https://opencollective.com/yeoman
But there doesn't seem to be a way to transfer fund between different collectives. This would be cool to sponsor upstream dependencies.

**Comment by jdubois** [comment]
c'mon @PierreBesson you found the culprit! If @SBoudrias is interested (and fixes the issue!!) we could do it a $200 bounty and you share it. WDYT @SBoudrias ?

**Comment by jdubois** [comment]
So we'll have a temporary fix from @PierreBesson with the above PR, and that's awesome.
