### ISSUE TITLE
Enhance documentation on how to create systems with multiple gateways

### ISSUE THREAD

**Issue by woelfle** [jhipster/generator-jhipster#9953]
##### **Overview of the feature request**

The JHipster documentation on microservices states that:

"There can be several different gateways, if you want to follow the Backends for Frontends pattern, but that’s not mandatory." (https://www.jhipster.tech/microservices-architecture)

I have not been able to find any further documentation on how to setup a system with multiple gateways.

Therefore I suggest that the documentation should be enhanced with more information on how to implement the mentioned "Backends for Frontends" pattern.

##### **Motivation for or Use Case**

What I am ultimately after is creating a JHipster Microservice application that has mutiple frontends. Since only gateways provide a frontend (at least this is what I have understood so far) it seemed to me the only way to implement my requirement by having multiple gateways.

-   [ X] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Honestly, I don't understand very well what you want to achieve.
If you want different gateways, you just need to generate several Gateway. Then you need to code...

The documentation about "Backends for Frontends" is already linked in our doc.
You can read:
- https://www.thoughtworks.com/insights/blog/bff-soundcloud
- https://www.thoughtworks.com/radar/techniques/bff-backend-for-frontends

**Comment by pascalgrimaud** [comment]
Not sure we can do more here than what I already linked. 
That's why I'm closing this ticket.
