### ISSUE TITLE
Bitbucket Pipelines

### ISSUE THREAD

**Issue by atomfrede** [jhipster/generator-jhipster#9957]
##### Add Bitbuket Pipeliens

Should we add support for generating bitbucket pipelines configuration in ci/cd subgerator?

##### **Motivation for or Use Case**

Bitbucket is still widely used I guess, so I think it would be good to have at least a simple bitbucket pipeline generated by the ci/cd generator.
If there we agree to have that I can do that.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Yes I think it's similar to gitlab

**Comment by atomfrede** [comment]
Going to have a look during the weekend. It really looks we quite similar to gitlab ci so going to implement the same feature most likely.

**Comment by PierreBesson** [comment]
I'm not sure bitbucket pipelines is used much as you have to pay for it. IMO most people who use bitbucket do so because they want to buy the "combo" of jira, confluence and bitbucket which is pretty cheap compared to competitors offering.
As this feature was never requested by actual users, I would prefer to work on improving our existing Jenkins and Gitlab pipelines. Or even adding support for Drone which is an open source CI tool.

**Comment by atomfrede** [comment]
You have some free minutes on bitbucket I agree I forgot about drone. It looks quite good compared to when I looked at an older version.

**Comment by pascalgrimaud** [comment]
Agree with @PierreBesson : we should focus on improving our current CI. I'm not against adding Bitbucket CI if you want to keep and maintain it, @atomfrede :)
About new CI, we could support back CircleCI too, it was removed because no one wanted to migrate to v2.

**Comment by atomfrede** [comment]
Let's go for drone. Good point we removed it before to have it again.

**Comment by pvliss** [comment]
Hello team. Sorry if I am high-jacking the thread but just could not resist :smile: . I had a great experience with TeamCity in the past and its integration with the JetBrains tools is of course superb as well. If people are interested I could look into it and maintain it. Basic free version is more than enough for most projects. Also as an OSS project we could also have access to a [hosted server](https://teamcity.jetbrains.com) as well. WDYT?
