### ISSUE TITLE
pagination update problem from 6.0 to 6.1 on JDL generated entities 

### ISSUE THREAD

**Issue by leratc** [jhipster/generator-jhipster#9959]
##### **Overview of the issue**
When adding pagination via jdl, the generated java/reactjs code is broken since 6.1 
on these two method signatures belonging to the old version:
1) HttpHeaders headers = PaginationUtil.generatePaginationHttpHeaders(page, "/api/customers");
2) HeaderUtil.createEntityUpdateAlert( ENTITY_NAME, customer.getId().toString())

The source code does not compile.
For the 2nd method, the solution is easy : 
    @Value("${jhipster.clientApp.name}")
    private String applicationName;
HeaderUtil.createEntityUpdateAlert( **applicationName, true**, ENTITY_NAME, customer.getId().toString())
For the first method, the impact is more complex, we need to add theses two parameters
@RequestParam MultiValueMap<String, String> queryParams, UriComponentsBuilder uriBuilder,
to the Pageable Param, therefore the reactjs code has to adapt.
and then we could use the new signature:
HttpHeaders headers = PaginationUtil.generatePaginationHttpHeaders(uriBuilder.queryParams(queryParams), page);

the jdl that specify a pagination for Customer
service Customer
paginate Customer with pagination

It is easily reproduced with any entity with pagination.
I generated source from windows X64, via Jdl on a java/react monolith with jhipster 6.1.
The initial java/react project has correct pagination on AuditResource.java for example.
But adding new entities with pagination via jdl does not enforce good pagination, it does not even compile.

**Comment by ruddell** [comment]
Please provide your full config and entity config, as well as instructions to reproduce (fill out the template).

If I had to guess, it's that you generated your project with the old version and generated the entities with a new version.  It's expected to generate with the same version

**Comment by leratc** [comment]
Thanks for your reply.
I generated the project via start.jhipster online generator. Then, I checkout the generated project and apply jdl.
It's the entities coming from jdl that are obsolete about the pagination.

**Comment by leratc** [comment]
the JDL content (from Matt Raible I think)
/* Entities for Store */
/** Product sold by the Online store */
entity Product {
    name String required
    description String
    price BigDecimal required min(0)
    size Size required
    image ImageBlob
}
enum Size {
    S, M, L, XL, XXL
}
entity ProductCategory {
    name String required
    description String
}
entity Customer {
    firstName String required
    lastName String required
    gender Gender required
    email String required pattern(/^[^@\s]+@[^@\s]+\.[^@\s]+$/)
    phone String required
    addressLine1 String required
    addressLine2 String
    city String required
    country String required
}
enum Gender {
    MALE, FEMALE, OTHER
}
entity ProductOrder {
    placedDate Instant required
    status OrderStatus required
    code String required
    invoiceId Long
}
enum OrderStatus {
    COMPLETED, PENDING, CANCELLED
}
entity OrderItem {
    quantity Integer required min(0)
    totalPrice BigDecimal required min(0)
    status OrderItemStatus required
}
enum OrderItemStatus {
    AVAILABLE, OUT_OF_STOCK, BACK_ORDER
}
relationship OneToOne {
    Customer{user(login) required} to User
}
relationship ManyToOne {
 OrderItem{product(name) required} to Product
}
relationship OneToMany {
   Customer{order} to ProductOrder{customer(email) required},
   ProductOrder{orderItem} to OrderItem{order(code) required} ,
   ProductCategory{product} to Product{productCategory(name)}
}
service Product, ProductCategory, Customer, ProductOrder, OrderItem with serviceClass
paginate Product, Customer, ProductOrder, OrderItem with pagination
/* Entities for Invoice */
entity Invoice {
    code String required
    date Instant required
    details String
    status InvoiceStatus required
    paymentMethod PaymentMethod required
    paymentDate Instant required
    paymentAmount BigDecimal required
}
enum InvoiceStatus {
    PAID, ISSUED, CANCELLED
}
entity Shipment {
    trackingCode String
    date Instant required
    details String
}
enum PaymentMethod {
    CREDIT_CARD, CASH_ON_DELIVERY, PAYPAL
}
relationship OneToMany {
    Invoice{shipment} to Shipment{invoice(code) required}
}
service Invoice, Shipment with serviceClass
paginate Invoice, Shipment with pagination

/* Entities for notification */
entity Notification {
    date Instant required
    details String
    sentDate Instant required
    format NotificationType required
    userId Long required
    productId Long required
}
enum NotificationType {
    EMAIL, SMS, PARCEL
}
