### ISSUE TITLE
@UniqueConstraint is giving null pointer exception

### ISSUE THREAD

**Issue by svennela** [jhipster/generator-jhipster#996]
Hi,

I am using Oauth based 2.0 version.I am running mvn pulgin to generate database log for jpa. I am getting null pointer exception when i run below command.  

mvn compile liquibase:diff

@Table(name = "T_USERRELEATION",uniqueConstraints = @UniqueConstraint(columnNames = { "FROM_USER_ID", "TO_USER_ID" }))

 
@JoinColumn(name = "FROM_USER_ID", nullable = false)
    @NotNull
    private User fromUser; // (userId)
    
    
 	@JoinColumn(name = "TO_USER_ID", nullable = false)
	@NotNull
 	private User toUser; // (userId)

**Comment by jdubois** [comment]
If you have a NPE when running the Liquibase plugin, please send the ticket to Liquibase -> https://github.com/liquibase/liquibase-hibernate

You can link the ticket here, as it's always good to know when one of the tools we use has a bug.
