### ISSUE TITLE
Generator hangs when asking for app name: Upgraded to JHipster v6.1.0

### ISSUE THREAD

**Issue by tcbuzor** [jhipster/generator-jhipster#9961]
##### **Overview of the issue**
Upgraded to JHipster 6.1.0 and console hangs when generator asks for application name

The console hangs on Mac OS, when the generator requests application name
##### **Motivation for or Use Case**

I can't proceed to generate application.
##### **JHipster Version(s)**
6.1.0

6.1.0
##### **JHipster configuration**

jhipster info
INFO! Using JHipster version installed globally
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
/Users/tonero
└── (empty)

```

cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

git version 2.17.2 (Apple Git-113)

node: v8.11.1

npm: 6.9.0

yarn: 1.9.4

Docker version 19.03.0-rc2, build f97efcc

docker-compose version 1.24.0, build 0aa59064

INFO! Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

Mac OS Mojave
-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by santimanuelr** [comment]
Hi, I'm going through the same problem. MacOS Mojave too.
node: v10.16.0
npm: 6.9.0
JHipster v6.1.0

**Comment by amatosg** [comment]
this has been already resolved by https://github.com/jhipster/generator-jhipster/issues/9952

**Comment by pascalgrimaud** [comment]
yes, it has been fixed.
we'll try to do a release soon
