### ISSUE TITLE
Error while deploying to Heroku 

### ISSUE THREAD

**Issue by anshumanpurohit** [jhipster/generator-jhipster#997]
I am using jhipster v2.0.0 with Maven and Grunt. Everything seemingly works on my local can Shippable CI. However, when do `yo jhipster:heroku` it fails consistently with this following error 

...
 remote:        [INFO] Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/wagon/wagon/2.4/wagon-2.4.pom
remote:        [INFO] Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/wagon/wagon/2.4/wagon-2.4.pom (20 KB at 643.7 KB/sec)
remote:        [INFO] Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/3.0.8/plexus-utils-3.0.8.pom
remote:        [INFO] Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/3.0.8/plexus-utils-3.0.8.pom (4 KB at 122.7 KB/sec)
remote:        [INFO] Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus/3.2/plexus-3.2.pom
remote:        [INFO] Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus/3.2/plexus-3.2.pom (19 KB at 538.4 KB/sec)
remote:        [INFO] Downloading: https://repo.maven.apache.org/maven2/org/sonatype/spice/spice-parent/17/spice-parent-17.pom
remote:        [INFO] Downloaded: https://repo.maven.apache.org/maven2/org/sonatype/spice/spice-parent/17/spice-parent-17.pom (7 KB at 178.4 KB/sec)
remote:        [INFO] Downloading: https://repo.maven.apache.org/maven2/org/sonatype/sisu/sisu-inject-bean/2.3.0/sisu-inject-bean-2.3.0.jar
remote:        [INFO] Downloading: https://repo.maven.apache.org/maven2/org/sonatype/sisu/sisu-guava/0.9.9/sisu-guava-0.9.9.jar
remote:        [INFO] Downloading: https://repo.maven.apache.org/maven2/org/sonatype/sisu/sisu-guice/3.1.0/sisu-guice-3.1.0-no_aop.jar
remote:        [INFO] Downloading: https://repo.maven.apache.org/maven2/org/apache/commons/commons-exec/1.1/commons-exec-1.1.jar
remote:        [INFO] Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/2.0.6/plexus-utils-2.0.6.jar
remote:        [INFO] Downloaded: https://repo.maven.apache.org/maven2/org/apache/commons/commons-exec/1.1/commons-exec-1.1.jar (52 KB at 410.5 KB/sec)
remote:        [INFO] Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.jar
remote:        [INFO] Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/2.0.6/plexus-utils-2.0.6.jar (219 KB at 1407.7 KB/sec)
remote:        [INFO] Downloading: https://repo.maven.apache.org/maven2/org/sonatype/aether/aether-util/1.13.1/aether-util-1.13.1.jar
remote:        [INFO] Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.jar (60 KB at 260.4 KB/sec)
remote:        [INFO] Downloading: https://repo.maven.apache.org/maven2/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
remote:        [INFO] Downloaded: https://repo.maven.apache.org/maven2/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar (28 KB at 105.2 KB/sec)
remote:        [INFO] Downloading: https://repo.maven.apache.org/maven2/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
remote:        [INFO] Downloaded: https://repo.maven.apache.org/maven2/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar (14 KB at 45.0 KB/sec)
remote:        [INFO] Downloaded: https://repo.maven.apache.org/maven2/org/sonatype/sisu/sisu-inject-bean/2.3.0/sisu-inject-bean-2.3.0.jar (283 KB at 797.4 KB/sec)
remote:        [INFO] Downloaded: https://repo.maven.apache.org/maven2/org/sonatype/aether/aether-util/1.13.1/aether-util-1.13.1.jar (127 KB at 380.2 KB/sec)
remote:        [INFO] Downloaded: https://repo.maven.apache.org/maven2/org/sonatype/sisu/sisu-guice/3.1.0/sisu-guice-3.1.0-no_aop.jar (350 KB at 758.8 KB/sec)
remote:        [INFO] Downloaded: https://repo.maven.apache.org/maven2/org/sonatype/sisu/sisu-guava/0.9.9/sisu-guava-0.9.9.jar (1473 KB at 1722.0 KB/sec)
remote:        [INFO] node version :
remote:        [INFO] ------------------------------------------------------------------------
remote:        [INFO] BUILD FAILURE
remote:        [INFO] ------------------------------------------------------------------------
remote:        [INFO] Total time: 35.765 s
remote:        [INFO] Finished at: 2015-01-16T23:39:48+00:00
remote:        [INFO] Final Memory: 21M/528M
remote:        [INFO] ------------------------------------------------------------------------
remote:        [ERROR] Failed to execute goal com.github.trecloux:yeoman-maven-plugin:0.2:build (run-grunt) on project statx: Error during : node --version: Cannot run program "node" (in directory "/tmp/build_648dd954a9c29e4ae9a869e0272bd990"): error=2, No such file or directory -> [Help 1]
remote:        [ERROR]
remote:        [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
remote:        [ERROR] Re-run Maven using the -X switch to enable full debug logging.
remote:        [ERROR]
remote:        [ERROR] For more information about the errors and possible solutions, please read the following articles:
remote:        [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
remote:
remote:  !     ERROR: Failed to build app with Maven
remote:
remote:
remote:  !     Push rejected, failed to compile Java app
remote:
remote: Verifying deploy...
remote:
remote: !	Push rejected to stat-x.
remote:
To https://git.heroku.com/stat-x.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/stat-x.git'

Please help!

**Comment by gmarziou** [comment]
The error message says 'Error during : node --version: Cannot run program "node"', it looks like NodeJS is not installed in your Heroku environment or not in your path.

**Comment by jdubois** [comment]
yes, can you check with the Heroku support? Without Node, nothing is going to work anyway.
I'm closing this as this is not a JHipster bug

**Comment by anshumanpurohit** [comment]
@jdubois 
Thanks for the quick response. Also, I understand that this sub-generator is Beta status. However, I think someone should take another look at this ...

1. This was working fine on jhipster v1.7 I see that yeoman-maven-plugin was added as a 'dev' build step recently. If I remove that from maven dev profile, things work fine. Can you explain what this step do? Why do we need to run in Heroku again?
2. I followed the instruction (http://jhipster.github.io/heroku.html) to create this Heroku app (and the Procfile). Did I miss a step somewhere to enable node for my app?
3. Ref : "Without Node, nothing is going to work anyway" ... I thought the node dependency is only for build phase. Does jhipster generated app have a node dependency at runtime? This can be serious issue when I am deploying my app in cloud (without Dockers). For example, how do you define a hybrid (node+java) Heroku 'process type' using one dyno?

**Comment by jdubois** [comment]
OK, I re-opened the ticket and will have a closer look

**Comment by jdubois** [comment]
I've just tried it again, and deployed without any issue at all. I'm just doing the "yo jhipster:heroku" command, nothing else.
-> this is why I'm closing this

Now some tips, because you definitively have an issue: you could try doing "grunt test" by hand, or "bower install" and "yo doctor". When the yeoman-maven-plugin fails, like in your case, that's because grunt/bower/npm/yo is not working properly.
This plugin is very simple, it just launches the commands, but sometimes it can hide the real result.

**Comment by anshumanpurohit** [comment]
@jdubois 
I ran those commands on my local and all ran without any errors. 

BTW, did you use Compass in your test app above?

**Comment by tomhughesnice** [comment]
Hi, I would just like to say this issue is not a one off. I too am having exactly the same problem.
It appears we have to install node.js on Heruko from the error.

**Comment by benaneesh** [comment]
Hi, got the same error on two different devices. Must be a change on Heroku's side. Will try a multi buildpack with node and java when I get home.
