### ISSUE TITLE
Change Remember Me default option to "false" in Login Modal

### ISSUE THREAD

**Issue by SudharakaP** [jhipster/generator-jhipster#9977]
##### **Overview of the issue**

The remember me checkbox in the login modal defaults to true/checked. I believe we should change this to unchecked. 

##### **Motivation for or Use Case**

Normally it's good UX practice to give the user the option to click on remember me if he/she wants rather than making the login remember me option on by default. 

Example Reference: https://ux.stackexchange.com/questions/20924/why-isnt-the-remember-me-checkbox-in-login-forms-enabled-by-default

##### **Reproduce the Scenario**

Open the login modal by clicking on Account --> Sign In. 

##### **Related issues**

None.

##### **Suggest a Fix**

I suggest altering the following two files; **login.component.ts.ejs** and login.component.html.ejs

The login.component.html.ejs file should be altered to remove the checked option from the input element. 

`<label class="form-check-label" for="rememberMe">
                        <input class="form-check-input" type="checkbox" name="rememberMe" id="rememberMe" formControlName="rememberMe">
                        <span jhiTranslate="login.form.rememberme">Remember me</span>
                    </label>`

and the login.component.ts.ejs file should be modified to make the rememberMe field value to false by default. 

`export class <%=jhiPrefixCapitalized%>LoginModalComponent implements AfterViewInit {
    authenticationError: boolean;

    loginForm = this.fb.group({
        username: [''],
        password: [''],
        rememberMe: [false]
    });`

##### **JHipster Version(s)**

6.1.0

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jaypitroda12** [comment]
@SudharakaP Hi Sudhakara, my pull request for this issue is merged. [#9993](https://github.com/jhipster/generator-jhipster/pull/9993)

**Comment by vishal423** [comment]
closed by #9993

**Comment by SudharakaP** [comment]
@SudharakaP : Wonderful. 👍
