### ISSUE TITLE
adding xeditable module

### ISSUE THREAD

**Issue by bipinkishore** [jhipster/generator-jhipster#998]
Hi,
 I am trying to add the xeditable feature to my application. But When I add 
                      var jhipsterApp = angular.module('jhipsterApp', ['xeditable']); 
in my controller after installing angular-Xeditable using bower. My application is not working properly.  I couldn't able to judge, whether it is bug in the jhipster or may I have done any wrong configuration. Please any guidance will be really appreciated. Thx

**Comment by jdubois** [comment]
Please read https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md before submitting a bug.
