### ISSUE TITLE
Logs admin not displaying loggers

### ISSUE THREAD

**Issue by markvr4** [jhipster/generator-jhipster#9982]
##### **Overview of the issue**

I am not able to see the log admin interface on apps created with jhipster 6.1.0 and 6.1.2. The Logs page displays with table headers but no rows/data. Reproduced on two different Macs.

##### **Motivation for or Use Case**

The built-in log administration tool is very valuable for troubleshooting issues, and it should work if it is an option in the Administration menu.

##### **Reproduce the error**

Tested on two different Macbooks:

$ mkdir testapp
$ cd testapp
$ jhipster
-accept defaults for all questions except answer no for i18n
-run ./mvnw (build succeeds, app starts with no errors)
-Open http://localhost:8080/ in browser (Firefox, Chrome, and Safari)
-Sign in with admin/admin
-Navigate to Administration > Logs
-Page displays with:
----title "Logs"
----subtitle "There are 1384 loggers."
----text input "Filter"
----table headers "Name" and "Level"
----no table displays with logs
----footer "This is your footer".
-No javascript errors in browser console
-Browser network log shows call to loggers endpoint succeeds with 200, and loggers are visible in the response
-When I inspect the html, I see the following in the place I would expect to see html table <td> elements:
```
<!--bindings={
  "ng-reflect-ng-for-of": ""
}-->
```

##### **Related issues**

"No admin metrics and log shown #9932" reports that the metrics and logs don't display, but there were javascript errors in that case, and in my case, I am able to see the metrics page.

##### **Suggest a Fix**

The data is coming back from the service, so it seems like a javascript/html/css issue, but I'm a back-end dev and my front-end debugging skills are limited.

##### **JHipster Version(s)**

6.1.0 and 6.1.2.
I can run an app from 5.8.2 where logs display correctly on the same machine/configuration

##### **JHipster Version(s)**

```
myapp@0.0.0 /Users/ujoh429/git/jhipster/myapp
└── generator-jhipster@6.1.2 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "6.1.2",
    "applicationType": "monolith",
    "baseName": "testapp",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "xxxxx",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "11.0.3" 2019-04-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.3+12-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.3+12-LTS, mixed mode)

git version 2.21.0

node: v12.4.0

npm: 6.9.0

##### **Browsers and Operating System**

Machine 1: macOS Mojave 10.14.5; Safari, Firefox 67.0.1 and Chrome 74.0.3729.131
Machine 2: macOS Mojave 10.14.0; Safari, Firefox 67.0.0 and Chrome 71.0.3578.98

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by clement26695** [comment]
I can confirm the issue. This PR should solve it, normally : jhipster/ng-jhipster#97.

Thank you for reporting the bug !

**Comment by avdev4j** [comment]
I confirm too, I had this bug during a meetup talk :D 

@markvr4 would you like to test If the fix suggest @clement26695 fix that? If yes, we can close this issue.

**Comment by clement26695** [comment]
It won't work until the next release of ng-jhipster is included in the main project

**Comment by markvr4** [comment]
I tried to manually make the code changes in my generated app since I don't have a dev environment setup for the jhipster code currently, but I could not get it to work (based on the results of `find . -name "filter.pipe.js"` made changes in node_modules/ng-jhipster/esm5/pipe/filter.pipe.js and node_modules/ng-jhipster/esm2015/pipe/filter.pipe.js). I'm not a UI dev, but I'm assuming I would have to clone the latest ng-jhipster repo which includes the change referenced above, build/package, and then reference from my generated app?

**Comment by kaidohallik** [comment]
@markvr4 Yes, exactly.

Step 1: go to some folder where you want to clone https://github.com/jhipster/ng-jhipster and execute commands:
```
git clone https://github.com/jhipster/ng-jhipster.git
cd ng-jhipster
npm install
npm run build
cd dist
npm pack
```

Step 2: change generated project:

In `package.json` change this line:
```
"ng-jhipster": "0.10.1",
```
to something like this (use correct path to cloned ng-jhipster):
```
"ng-jhipster": "file:../../jhipster/ng-jhipster/dist/ng-jhipster-0.10.1.tgz",
```

Run `npm install` and `npm start` and started app is now using cloned version of the ng-jhipster.

**Comment by deepu105** [comment]
We need to fix this for next release as the page is useless now

**Comment by pascalgrimaud** [comment]
@deepu105 : it is already fixed by @clement26695, we just need to do a release of ng-jhipster and check here

**Comment by markvr4** [comment]
Thanks for the info, @kaidohallik! I can confirm following those steps resolved the issue for me.

**Comment by jdubois** [comment]
This seems important - I know it's already fixed, but still worth a bounty, so I'm adding one

**Comment by pascalgrimaud** [comment]
I confirm this PR https://github.com/jhipster/ng-jhipster/pull/97 fixed this issue
I'm closing this as it will be included in the next release

@clement26695 : don't forget to claim the bounty

**Comment by clement26695** [comment]
Bounty claimed at https://opencollective.com/generator-jhipster/expenses/9709
