### ISSUE TITLE
Support Alternative architectures (s390x, ppcle64, arm) for jhipster/jhipster docker image

### ISSUE THREAD

**Issue by fosslou** [jhipster/generator-jhipster#9989]
##### **Overview of the issue**

The JHipster Docker file has statements that are x86 and ARM specific.   If you change these to s390x you can build a docker image on s390x architecture

##### **Motivation for or Use Case**

Need to run JHipster on alternate architectures 

##### **Reproduce the error**

use cloud.ibm.com .  get a free account and then go to experimental services.  There is a service called hyperprotect virtual server.   These are ZLinux running ubuntu.  If you git clone the repository and try to build a docker image, it fails because of the architecture specific statements in the dockerfile

##### **Related issues**

No

##### **Suggest a Fix**

Change lines 29 and 31 to the following in the dockerfile

update-java-alternatives -s java-1.11.0-openjdk-s390x && \
  # install node.js
  wget https://nodejs.org/dist/v10.16.0/node-v10.16.0-linux-s390x.tar.gz -O /tmp/node.tar.gz && \
  

##### **JHipster Version(s)**

Latest

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by PierreBesson** [comment]
+1 As I just bought the new Raspberry Pi 4, so it's interesting for me. @fosslou can you submit a PR.

**Comment by PierreBesson** [comment]
I'm just afraid that your fix will make the docker image only compatible with s390x arch ?
We should try to cover as many arch as possible.

**Comment by fosslou** [comment]
I agree.. all architectures should be supported.    Testing it on the Pi would be great.    Let me know if you need access to s390x resources.  I may be able to help

**Comment by pascalgrimaud** [comment]
After reading closely this ticket, I think it's for a very specific use case.
So the best thing to do here would be to document it, maybe a new tips at https://www.jhipster.tech/tips/ ? -> if you want to do it, you're welcome.

Not sure we can do something on our side, that's why I'm closing this.
