### ISSUE TITLE
i want old project structure

### ISSUE THREAD

**Issue by addagulla** [jhipster/generator-jhipster#999]
Hi,

    when i generate a new project by running yo jhipster i am getting a new project structure and i wanna get old project structure how can i get back the old structure can some one helpme

thanks

**Comment by andidev** [comment]
Install the old generator with
`npm install -g generator-jhipster#1.10.2`

then try to generate your project again

**Comment by addagulla** [comment]
do i need to uninstall current jhipster generator? to install old one and to work with it

**Comment by jdubois** [comment]
No, just install the old version, like @andidev wrote, and you can use it.

**Comment by addagulla** [comment]
can i have an example command

**Comment by jdubois** [comment]
That's what @andidev already gave you
This is the ticket system if you have a bug -> if you don't know how to use NPM, look at the NPM forums or Stackoverflow

**Comment by addagulla** [comment]
hi jdubois, actually I have been tried the version of #1.10.2.But it seems its structure is similar to latest version. Actually, I am working on the old version, that is installed one month before. That uses a separate structure for scripts and view.

**Comment by boandriy** [comment]
Hi, I have the same issue. I currently have jhipster v5.2.0 installed, and this version has no social login option  when generating the app, so I would like to use older version. But after running the command:"npm install -g generator-jhipster#1.10.2" the jhipster's version is not changed.
I would like to know what I am doing wrong?
Is it possible somehowe to generate app with social login on jhipster v5.2.0?

Thanks in advance!

**Comment by deepu105** [comment]
@boandriy this issue is 3 years old and is not relevant anymore. We do not support social login anymore and the last version to have that was v4.x. So you could uninstall your current jhipster using the npm/yarn uninstall commands and install a 4.x version to get that feature

**Comment by boandriy** [comment]
@deepu105, thnks!

**Comment by boandriy** [comment]
this command changed my jhipster version from v5.2.0 to 4.14.1
yarn global add generator-jhipster@4.14.1
