### ISSUE TITLE
User Management admin pages not generated for gateway with no database

### ISSUE THREAD

**Issue by steffanolesen** [jhipster/generator-jhipster#9992]
##### **Overview of the issue**

The user management pages are not generated in my gateway microservice.
This seems to have been introduced in version 6.0.1

##### **Suggest a Fix**

If I switch to use a database with my gateway instead on no database, it seems to work.

##### **JHipster Version(s)**

```
gateway@0.0.0 /tmp4/gateway
└── (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "databaseType": "no",
    "devDatabaseType": "no",
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": [
      "en",
      "da"
    ],
    "messageBroker": false,
    "nativeLanguage": "en",
    "packageName": "dk.sware.simplecrm.gateway",
    "packageFolder": "dk/sware/simplecrm/gateway",
    "prodDatabaseType": "no",
    "searchEngine": false,
    "serviceDiscoveryType": "eureka",
    "skipClient": false,
    "skipServer": false,
    "testFrameworks": [],
    "websocket": false,
    "baseName": "gateway",
    "applicationType": "gateway",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "cacheProvider": "no",
    "buildTool": "gradle",
    "jhipsterVersion": "6.1.2",
    "skipUserManagement": false,
    "clientPackageManager": "npm",
    "serverPort": "8080",
    "clientFramework": "angularX",
    "useSass": true,
    "clientTheme": "none",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": []
  },
  "entities": [
    "Foo"
  ]
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Foo {
  bar String
}
microservice Foo with backend

</pre>
</details>

##### **Environment and Tools**

openjdk version "12.0.1" 2019-04-16
OpenJDK Runtime Environment (build 12.0.1+12)
OpenJDK 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)

git version 2.22.0

node: v10.16.0

npm: 6.9.0

yeoman: 2.0.6

yarn: 1.17.0

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
I think it's normal.
As you decided to use no database, there is no user to manage, so no user management pages.

That's why I'm closing this ticket, but we can still discuss about it.

**Comment by vishal423** [comment]
I think we should support as users are managed on `uaa` database

**Comment by pascalgrimaud** [comment]
Oh I see, it's for uaa
Maybe we should generate the user management part when:
- no database
- uaa

I don't know if it works before, I suppose yes, so it should just be a simple condition to fix
