### ISSUE TITLE
npm ERR! Maximum call stack size exceeded

### ISSUE THREAD

**Issue by eltonkent** [jhipster/generator-jhipster#9995]
##### **Environment and Tools**

java version "11.0.3" 2019-04-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.3+12-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.3+12-LTS, mixed mode)

git version 2.22.0

node: v12.4.0

npm: 6.9.0

yeoman: 2.0.0

yarn: 1.17.0

Docker version 18.09.1, build 4c52b90

docker-compose version 1.23.2, build 1110ad01

##### **Overview of the issue**

Running npm install causes  a npm ERR! Maximum call stack size exceeded error

##### **Reproduce the error**

1. Run jhipster and generate a monolith app. 
2. run npm install or ./gradlew

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "REDACTED",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.1.2",
    "applicationType": "monolith",
    "baseName": "REDACTED",
    "packageName": "REDACTED",
    "packageFolder": "REDACTED",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "react",
    "clientTheme": "cosmo",
    "clientThemeVariant": "light",
    "testFrameworks": [
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "hi",
      "mr",
      "ta",
      "te"
    ]
  }
}
</pre>
</details>

**Comment by gmarziou** [comment]
I could not reproduce.

One thing I noted is that you use node 12.4.0 while generated gradle.properties sets `node_version=10.16.0`

**Comment by gmarziou** [comment]
@eltonkent could please tryinstalling an LTS version of nodejs?

**Comment by gmarziou** [comment]
I could not reproduce either with node 12.5.0, so there is probably something wrong in your environment, you might want to try `npm cache clean --force`
