### ISSUE TITLE
jhipster 6.1.2 import-jdl always adds entities as new

### ISSUE THREAD

**Issue by jussiritamaki** [jhipster/generator-jhipster#9996]
##### **Overview of the issue**

jhipster import-jdl behavior changed from 6.0.0 to 6.1.0.
When importing incremental change for instance a simple column add on single entity version 6.0.0 detects the change correctly and generates proper liquid migration where both 6.1.0 and 6.1.2 always adds add entity migrations for all entities.

##### **Motivation for or Use Case**

If this is planned behaviour then it is not a step towards more jdl centric development and pretty much makes the jdl useless.

##### **Reproduce the error**

create app with jhipster 6.1.2
import jdl with 2 separate entities
add column to one entity
import jdl again
create entity migrations are created for both entities even if just one changed

##### **Suggest a Fix**

Seems that changeData fields always change when importing on .jhipster/*.json files so it could be related to the issue

##### **JHipster Version(s)**

Seems to be regression, 6.1.0 and 6.1.2 both tested and not working, while 6.0.0 is working

##### **JHipster Version(s)**

```
meta-2@0.0.0 /.../meta2
└── generator-jhipster@6.1.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.1.2",
    "applicationType": "monolith",
    "baseName": "meta2",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Foo {
  fooField String
}
entity Bar {
  barField String,
  newlyAddedField String
}

</pre>
</details>

##### **Environment and Tools**

java version "11.0.2" 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)

git version 2.20.1

node: v11.12.0

npm: 6.7.0

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

{
    "name": "Bar",
    "fields": [
        {
            "fieldName": "barField",
            "fieldType": "String"
        },
        {
            "fieldName": "newlyAddedField",
            "fieldType": "String"
        }
    ],
    "relationships": [],
    "changelogDate": "20190627054520",
    "entityTableName": "bar",
    "dto": "no",
    "pagination": "no",
    "service": "no",
    "jpaMetamodelFiltering": false,
    "fluentMethods": true,
    "clientRootFolder": "",
    "applications": "*"
}{
    "name": "Foo",
    "fields": [
        {
            "fieldName": "fooField",
            "fieldType": "String"
        }
    ],
    "relationships": [],
    "changelogDate": "20190627054519",
    "entityTableName": "foo",
    "dto": "no",
    "pagination": "no",
    "service": "no",
    "jpaMetamodelFiltering": false,
    "fluentMethods": true,
    "clientRootFolder": "",
    "applications": "*"
}
##### **Browsers and Operating System**

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
Could be a regression. Needs to be reproduced.

Thanks & Regards,
Deepu

**Comment by kaidohallik** [comment]
I have similar issue, JHipster generates always new changelogs when changing JDL and re-executing import-jdl. If looking into jhipster-core recent changes then this change can be culprit:  
https://github.com/jhipster/jhipster-core/commit/d39e15f0e584318c20e70caffe1ce57769ab5f1c#diff-f6c0500618fe74400adc08cfc6620eaaL131  
Looks like changelogDate from entity configuration file is not used any more which causes this problem.

**Comment by kaidohallik** [comment]
I opened PR in jhipster-core to fix this issue: https://github.com/jhipster/jhipster-core/pull/340

**Comment by pascalgrimaud** [comment]
I changed the label as @kaidohallik confirmes the ticket and made an improvement

**Comment by MathieuAA** [comment]
This is merged, I'll release a patch before this evening

**Comment by bonsmik** [comment]
Will there be a patch version including this fix? Did you forgot it @MathieuAA or change in plans?
