### ISSUE TITLE
JHipster 6 should have plural URLs for list screens

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#9997]
##### **Overview of the issue**

JHipster 6 has entity URLs like http://localhost:8080/blog instead of http://localhost:8080/blogs like v5 and v4 had. 

##### **Motivation for or Use Case**

From @jdubois:

> This is a mistake. URLs have always been pluralized, I copied Ruby on Rails for that

##### **Reproduce the error**

Generate entities, look at list screen URL.

##### **Related issues**

https://github.com/jhipster/generator-jhipster/issues/9956 No records found message should be plural.

##### **JHipster Version(s)**

```
blog@0.0.0 /Users/mraible/dev/jhipster6-demo
└── generator-jhipster@6.1.2 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "org.jhipster.blog",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.1.2",
    "applicationType": "monolith",
    "baseName": "blog",
    "packageName": "org.jhipster.blog",
    "packageFolder": "org/jhipster/blog",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": ["protractor"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en", "es"],
    "herokuAppName": "jhipster-6-demo",
    "herokuDeployType": "git"
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Blog {
  name String required minlength(3),
  handle String required minlength(2)
}
entity Entry {
  title String required,
  content TextBlob required,
  date Instant required
}
entity Tag {
  name String required minlength(2)
}
relationship ManyToOne {
  Blog{user(login)} to User,
  Entry{blog(name)} to Blog
}
relationship ManyToMany {
  Entry{tag(name)} to Tag{entry}
}

paginate Entry, Tag with infinite-scroll

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

git version 2.20.1 (Apple Git-117)

node: v10.16.0

npm: 6.9.0

yeoman: 2.0.6

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

INFO! Congratulations, JHipster execution is complete!

**Comment by pascalgrimaud** [comment]
Are you sure about that ?
Just switch to an old version of jhipster-sample-app: v5.2.0 and I got `http://localhost:8080/#/label` in URL

![Capture d’écran de 2019-06-30 18-00-19](https://user-images.githubusercontent.com/9156882/60399190-2831dc00-9b61-11e9-8b20-8261538ca9eb.png)

**Comment by jdubois** [comment]
Oh sorry, the REST API is pluralized, not the HTML5 frontend

**Comment by pascalgrimaud** [comment]
In that case, I don't see any bug as REST API is still pluralized, not the URLs.
I'm closing this, hope you're ok Matt. Feel free to reopen and discuss if it needed :-)

**Comment by mraible** [comment]
I think this should be reopened. In the v4 and v5 versions of the JHipster demo + screencasts I recorded, front end URLs were pluralized for list screens.

**Comment by jdubois** [comment]
Sorry everyone for messing up here... I definitely remember the API is pluralized, for the front-end URLs I have no idea what I did, but also I wonder if pluralizing those is a good idea. We should discuss this, at least!

**Comment by pascalgrimaud** [comment]
I investigated a little bit.
- the API are pluralized : ok for this part
- about URL:
    - AngularJS : it were pluralized
    - Angular : it is not -> so we lost the "plural" here

When I looked at your video for v5: https://youtu.be/-VQ_SVkaXbs?t=471
It is with Angular and the URLs weren't pluralized.

**Comment by mraible** [comment]
You are correct @pascalgrimaud. Even my [JHipster 4 screencast](https://youtu.be/XRREt1KB4Y8?t=414) shows they're not plural. Closing.
